### ISSUE TITLE
bug: 使用了引用消息返回消息id的版本，sk发送一条消息qq就挂了，导致无限重启

### ISSUE THREAD

**Issue by foxdad** [whitechi73/OpenShamrock#10]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

我回退到最新的dev版本
发送多个图片消息都没有不会导致qq挂掉

包含信息，图片就删除了

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by whitechi73** [comment]
您需要安装一个Xposed模块，[AppErrorTracing](https://github.com/KitsunePie/AppErrorsTracking)，并将错误日志提供。

**Comment by whitechi73** [comment]
请尝试使用最新构建版本？

**Comment by foxdad** [comment]
> 请尝试使用最新构建版本？

早上使用了最新版本构建的，还是出现发消息就闪退的问题
[v1.0.5-dev.dc2503b-all]

**Comment by callng** [comment]
在我发表评论时的最新构建的版本，在QQ里主动发送一条消息，无论是群聊还是私聊，都会导致QQ主动闪退到桌面。

**Comment by callng** [comment]
> 在我发表评论时的最新构建的版本，在QQ里主动发送一条消息，无论是群聊还是私聊，都会导致QQ主动闪退到桌面。

QQ自己内部做了崩溃处理机制，有些异常那个异常跟踪可能拦截不到。

**Comment by whitechi73** [comment]
> > 请尝试使用最新构建版本？
> 
> 早上使用了最新版本构建的，还是出现发消息就闪退的问题 [v1.0.5-dev.dc2503b-all]

QQ版本能不能提供一下？

**Comment by foxdad** [comment]
> > > 请尝试使用最新构建版本？
> > 
> > 
> > 早上使用了最新版本构建的，还是出现发消息就闪退的问题 [v1.0.5-dev.dc2503b-all]
> 
> QQ版本能不能提供一下？

8.9.83版本

**Comment by lori255** [comment]
遇到了相同的问题，8.9.83和8.9.85都遇到了发送一条消息就会闪退的情况，使用的是Shamrock-v1.0.5-dev.dc2503b-all.zip

**Comment by whitechi73** [comment]
在8.9.85测试中，未出现闪退，在最新构建中，相机功能正常

**Comment by foxdad** [comment]
> > 合并转发消息好像还是会发一条就崩溃，普通文字和图片没事 (已用最新)
> 
> 大意了，没清理虚拟机缓存，清理之后貌似好了 (心情简单)

发送消息一段时间，就发不出去了，需要重启，感觉是不会自动清理虚拟机内存的问题
