### ISSUE TITLE
bug: 模拟器LSPosed框架下无法激活Shamrock

### ISSUE THREAD

**Issue by hendrixone** [whitechi73/OpenShamrock#100]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

QQ已经登录，LSPosed框架正常安装并启动了Shamrock模块，也选择了QQ。但打开Shamrock依旧显示未激活

### 复现 Bug

通过Kitsune Mask安装Magisk，通过Magisk分别安装riru和LSPosed。安装Shamrock和Hide My Applist并在LSPosed管理器中激活。登录QQ，打开Shamrock，强制停止qq，启动QQ。Shamrock显示未激活

## 系统信息

- Shamrock 版本: 1.0.6-dev-all
- Android 版本: 9
- LSPosed 框架版本: LSPosed 1.9.2 riru
- 设备的制造商和型号: 雷电模拟器

**Comment by whitechi73** [comment]
不要Hide My Applist，对QQ隐藏Shamrock！

**Comment by hendrixone** [comment]
> 不要Hide My Applist，对QQ隐藏Shamrock！

文档里有写到隐藏，于是我就照着隐藏了，成功激活了
