### ISSUE TITLE
bug: 反检测的故障

### ISSUE THREAD

**Issue by tobycroft** [whitechi73/OpenShamrock#105]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
![Screenshot_20231128-212700_Shamrock](https://github.com/whitechi73/OpenShamrock/assets/24893075/cdb2018f-293a-40e5-9c54-5ae8607405a3)

这个错误原因我也不知道，LOG我开的是详细模式，因为这个功能我没看原理，所以不知道什么原因可能会导致这个错误

### 复现 Bug

切的最新版测试的，但是我这里不知道为什么会有这个错误原因

# 系统信息

- Shamrock 版本: 最新版
- Android 版本: 14
- LSPosed 框架版本: 最新
- 设备的制造商和型号: MI9
- 设备的 CPU 架构: ARM64

**Comment by tobycroft** [comment]
另外之前我记得有人反馈说config文件没用的问题，我发现不仅仅是config，我发现shamrock在1.0.6版本以下，是可以开启silk的，但是1.0.6之后主文件夹的audiolibraries 就没用了，无法开启（或关闭），不知道这个故障是否也是由于这个原因引起的

**Comment by Simplxss** [comment]
我没记错的话只要你安装成功了语音功能就会自动开启 你没开启肯定是装错了

**Comment by tobycroft** [comment]
> 我没记错的话只要你安装成功了语音功能就会自动开启 你没开启肯定是装错了

你试试，1.0.5版本装完需要点击开启，点击开启后，可以再关闭，除非复制文件夹错误了，才会出现需要到github查看教程的提示，1.0.6dev版本后，我不知道他是卡在了true的位置上还是自动启动的，不过点击switch想要关闭这个功能的时候会提示到github查看开启教程之类的提示，所以不知道是故障了还是如何，然后版本和版本更新后重启一下有概率会丢配置
