### ISSUE TITLE
bug: 发送只有两条消息的合并转发时仍会被打乱顺序

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#106]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

三条及三条以上似乎都不会乱

POST:
```json
{
    "action": "send_group_forward_msg",
    "echo": "send_group_forward_msg_1701243271530859000",
    "params": {
        "group_id": group_id,
        "messages": [
            {
                "data": {
                    "content": "11月29日15时31分03秒之后群group_id中最近1条at过user_id的消息："
                },
                "type": "node"
            },
            {
                "data": {
                    "content": "[@user_id] \n\n--[15:34:26]謬紗特 "
                },
                "type": "node"
            }
        ]
    }
}
```
向自己发送的时候就已经是不按顺序的了
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/343f2a2c-70c2-450d-bb6a-85b46abdaa34)

得到的结果
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/d91b2af7-a294-40dc-9c42-57de8526093b)

### 复现 Bug

在群聊发送一条只有两个消息节点的合并转发消息

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.6-dev.64c800c](https://github.com/whitechi73/OpenShamrock/actions/runs/7027114232)
- Android 版本: 14
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: Xiaomi Redmi K20 Pro
- 设备的 CPU 架构: Arm64

**Comment by Simplxss** [comment]
就是因为向自己发送的时候就已经是不按顺序的了 所以转发顺序也不对了。。。
目前发送消息采用的是异步方式 没办法保证消息顺序 改成同步可能有点麻烦 目前也就只能加个sleep或许能解决一点 但是如果包含图片大概顺序还是不准的。。。
