### ISSUE TITLE
bug: 图片发送失败，再次发送会成功

### ISSUE THREAD

**Issue by CSGA-KPX** [whitechi73/OpenShamrock#109]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

发送图片时（base64模式，png格式），第一次会发送失败并在手机端显示为感叹号。如果人工点感叹号或者bot端重发一次相同图片就能成功。

![mobile side](https://github.com/whitechi73/OpenShamrock/assets/2347318/29220d0a-2852-4380-b3db-261ce71a20f1)

### 复现 Bug

尚不清楚其他平台能否复现。摘录相关数据如下：

* 第一次发送的数据见 [req1.txt](https://github.com/whitechi73/OpenShamrock/files/13500165/req1.txt)
* 第二次发送的数据见 [req2.txt](https://github.com/whitechi73/OpenShamrock/files/13500164/req2.txt)
* 日志见 [log.txt](https://github.com/whitechi73/OpenShamrock/files/13500163/log.txt)

## 系统信息

- Shamrock 版本: Shamrock-v1.0.6-dev.64c800c-all
- Shamrock模式：ReverseWebsocket
- Android 版本:  13（API 33）
- LSPosed 框架版本: LSPatch 0.5.1(360), Framework1.8.5(6649)
- 设备的制造商和型号: lge LM-G710
- 设备的 CPU 架构: arm64-v8a，armeabi-v7a，armeabi

**Comment by CSGA-KPX** [comment]
后续：

该commit似乎按照如果失败就隔一段时间重发的机制运行。实测小图片可以在两三次重试内完成，更大的图片依然会失败。

目前确定QQ自己的图片上传机制没有问题，只在OpenShamrock下会出现这类情况。

**Comment by CSGA-KPX** [comment]
目前设置重试是4次0.1秒？大一点的图（我这边500KB）会用尽重试次数，具体取决于网速和延迟。而且应用端收不到错误信息无法判断是否真的发出去了。

看起来是图片传上去到服务器接受消息有一定的延迟。如果很难抓到上传成功的信号的话，可以考虑延长等待间隔。我这边感觉大部分图片会在第四次重试的时候成功（0.4s左右），可以考虑加用1秒左右的间隔。

**Comment by ikechan8370** [comment]
> 目前设置重试是4次0.1秒？大一点的图（我这边500KB）会用尽重试次数，具体取决于网速和延迟。而且应用端收不到错误信息无法判断是否真的发出去了。
> 
> 
> 
> 来不及分析代码，看起来是图片传上去到服务器接受消息有一定的延迟。如果很难抓到上传成功的信号的话，可以考虑延长等待间隔。我这边感觉大部分图片会在第四次重试的时候成功（0.4s左右），可以考虑加用1秒左右的间隔。

重试是附带的，那个commit主要是把发消息改成了同步的，你会收到发送结果的，如果失败也会有失败信息

**Comment by siuze** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/54578647/97ca5a37-a674-41d6-955f-29f8ea9245ed)
![image](https://github.com/whitechi73/OpenShamrock/assets/54578647/3a026eb1-542b-4ade-9cad-a8120c575691)
![image](https://github.com/whitechi73/OpenShamrock/assets/54578647/7196ef69-c785-4922-994e-d9d7a33ec680)

今天同样观察到这个问题。  
当图片尺寸较大，且是加在引用回复的消息中时更容易出现发送失败。  
也可能只是第一次发图失败第二次就好了和回不回复无关，不过这会儿复现不出来了就没办法测试。

**Comment by siuze** [comment]
频繁出现该问题
![73c83fd3cfccbbab5af68f22d93d0343](https://github.com/whitechi73/OpenShamrock/assets/54578647/aba447bb-c6b6-4b28-8379-e3dad44445c0)
![2e89b0cf12cc1306ef5f1c2c91f62a1f](https://github.com/whitechi73/OpenShamrock/assets/54578647/b4462fc1-fe75-436a-a1ee-5b5264228f55)

**Comment by Zyy955** [comment]
感叹号的图片会提示，当前图片尺寸过大，正在转为文件发送。

**Comment by siuze** [comment]
> 目前设置重试是4次0.1秒？大一点的图（我这边500KB）会用尽重试次数，具体取决于网速和延迟。而且应用端收不到错误信息无法判断是否真的发出去了。
> 
> 来不及分析代码，看起来是图片传上去到服务器接受消息有一定的延迟。如果很难抓到上传成功的信号的话，可以考虑延长等待间隔。我这边感觉大部分图片会在第四次重试的时候成功（0.4s左右），可以考虑加用1秒左右的间隔。

我将MsgSvc.kt下的retryCnt调整为10，delay调整为200，并将MessageHelper.kt下的estimateTime增加到原来的5倍后就可以正常重试发送成功了，不知道是哪一环节在起作用，有空再测试一下，若确实可行就发PR，或者等大佬修复

**Comment by siuze** [comment]
更新到
[Shamrock-v1.0.7.r199.135a7c2-all](https://github.com/whitechi73/OpenShamrock/suites/18981929360/artifacts/1109845892)后似乎可以重试成功了，我再观察一阵子看看
