### ISSUE TITLE
关于bot上报自身消息

### ISSUE THREAD

**Issue by Zyy955** [whitechi73/OpenShamrock#112]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

目前制作转发消息，使用shamrockQQ的当前设备都会上报由shamrockQQ本身发送的消息，这会造成一些比较严重的后果。

比如喵崽由一个内置指令 #添加...
例：
用户：#添加你好 
bot：请发送添加的内容
用户：#退群
bot：添加成功

随后用户可以通过触发你好，来让机器人发送`#退群`，在机器人是群主的群，此bug会导致群里直接被解散。

最好能区分下，通过shamrockQQ发送的消息不上报。

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by Simplxss** [comment]
这是你自己服务端处理的问题，你服务端写不好就别开上报自身消息

**Comment by Zyy955** [comment]
> 这是你自己服务端处理的问题，你服务端写不好就别开上报自身消息
> 另外问一句 有什么场景需要用到这个功能？
> 再加一句 你可以自己发送消息 然后直接转发消息时直接传msgid
> 最后再说一句 转发消息是给自己发的 你可以直接过滤发送来源为自己的私聊消息

用挂shamrock的QQ发消息，用得到的很多。

目前的做法就是储存通过shamrock返回的msg_id，然后在自身消息事件这边进行匹配msg_id，但是没有办法100%拦住，有时候msg_id没有返回消息已经上报过来了。

**Comment by Zyy955** [comment]
> emm，实质上，OpenShamrock已经做了区分（`message`事件和`message_sent`事件）。而这只是MiaoYunzai未进行适配导致的（一般来说，也用不到自发送消息事件的呀）

看都看不明白，不知道你在回啥

**Comment by Zyy955** [comment]
> emm，实质上，OpenShamrock已经做了区分（`message`事件和`message_sent`事件）。而这只是MiaoYunzai未进行适配导致的（一般来说，也用不到自发送消息事件的呀）

现在的情况是无论是通过shamrock发送的，shamrock挂载的QQ发送的，都会上报一次，还听不懂我也没啥好说的了。

**Comment by MoRanYue** [comment]
> > emm，实质上，OpenShamrock已经做了区分（`message`事件和`message_sent`事件）。而这只是MiaoYunzai未进行适配导致的（一般来说，也用不到自发送消息事件的呀）
> 
> 现在的情况是无论是通过shamrock发送的，shamrock挂载的QQ发送的，都会上报一次，还听不懂我也没啥好说的了。

emm，通过QQ直接发送，与通过调用Shamrick发送，都属于自发送信息。你的意思是，自发送信息的`MessageType`是`message`而非`message_sent`嘛？

**Comment by MoRanYue** [comment]
> > 这是你自己服务端处理的问题，你服务端写不好就别开上报自身消息
> > 另外问一句 有什么场景需要用到这个功能？emm，
> > 再加一句 你可以自己发送消息 然后直接转发消息时直接传msgid
> > 最后再说一句 转发消息是给自己发的 你可以直接过滤发送来源为自己的私聊消息
> 
> 用挂shamrock的QQ发消息，用得到的很多。
> 
> 目前的做法就是储存通过shamrock返回的msg_id，然后在自身消息事件这边进行匹配msg_id，但是没有办法100%拦住，有时候msg_id没有返回消息已经上报过来了。

emm，没必要呀，直接通过检查`PostType`是否为`message_sent`，可以判断了呀

![Screenshot_2023-12-09-09-10-46-130_com.termux-edit.png](https://github.com/whitechi73/OpenShamrock/assets/84905594/88f59b68-f8cd-4850-b2aa-31e63480112c)

可以看到，这里的`post_type`字段为`message_sent`而非`message`

**Comment by Zyy955** [comment]
> > > 这是你自己服务端处理的问题，你服务端写不好就别开上报自身消息
> > > 另外问一句 有什么场景需要用到这个功能？emm，
> > > 再加一句 你可以自己发送消息 然后直接转发消息时直接传msgid
> > > 最后再说一句 转发消息是给自己发的 你可以直接过滤发送来源为自己的私聊消息
> > 
> > 用挂shamrock的QQ发消息，用得到的很多。
> > 
> > 目前的做法就是储存通过shamrock返回的msg_id，然后在自身消息事件这边进行匹配msg_id，但是没有办法100%拦住，有时候msg_id没有返回消息已经上报过来了。
> 
> emm，没必要呀，直接通过检查`PostType`是否为`message_sent`，可以判断了呀
> 
> ![Screenshot_2023-12-09-09-10-46-130_com.termux-edit.png](https://github.com/whitechi73/OpenShamrock/assets/84905594/88f59b68-f8cd-4850-b2aa-31e63480112c)
> 
> 可以看到，这里的`post_type`字段为`message_sent`而非`message`

看不懂就别评论

**Comment by Simplxss** [comment]
#123 我估计你的问题可能和这个有关系 等有空修

**Comment by Simplxss** [comment]
另外我非常不建议混用QQ

**Comment by MoRanYue** [comment]
> > emm，实质上，OpenShamrock已经做了区分（`message`事件和`message_sent`事件）。而这只是MiaoYunzai未进行适配导致的（一般来说，也用不到自发送消息事件的呀）
> 
> 现在的情况是无论是通过shamrock发送的，shamrock挂载的QQ发送的，都会上报一次，还听不懂我也没啥好说的了。

emm，你的意思是，既需要使用QQ发送信息，也需要OpenShamrock发送信息，对吧？

（这样混用，其实并不好）

**Comment by Zyy955** [comment]
> 另外我非常不建议混用QQ

诶，确实

**Comment by Zyy955** [comment]
> > > emm，实质上，OpenShamrock已经做了区分（`message`事件和`message_sent`事件）。而这只是MiaoYunzai未进行适配导致的（一般来说，也用不到自发送消息事件的呀）
> > 
> > 现在的情况是无论是通过shamrock发送的，shamrock挂载的QQ发送的，都会上报一次，还听不懂我也没啥好说的了。
> 
> emm，你的意思是，既需要使用QQ发送信息，也需要OpenShamrock发送信息，对吧？
> 
> （这样混用，其实并不好）

这位大哥，我已经说了两遍了，这是第三次，不懂请你别评论，标题描述写的明明白白的东西不知道你在这扯什么，连别人说什么都搞不清楚

**Comment by Simplxss** [comment]
转发消息现在确实没什么好办法 除非有人重写成用协议发包()

**Comment by Zyy955** [comment]
> 转发消息现在确实没什么好办法 除非有人重写成用协议发包()

先这样吧，我标注一下自身这边就好，这个功能确实挺敏感的

**Comment by Simplxss** [comment]
> > 转发消息现在确实没什么好办法 除非有人重写成用协议发包()
> 
> 先这样吧，我标注一下自身这边就好，这个功能确实挺敏感的

这不是敏感不敏感的问题 如果一开始**就在服务器进行消息的合并处理 现在就没这么多diao事了
就是因为它一开始不校验真实性 导致各种插件都是通过"伪造"的方式发送合并转发消息 现在为了兼容性只能在协议端处理这些"烂摊子"
如果是插件自己进行伪造的话 实际上就能好很多了

**Comment by Simplxss** [comment]
哦 对了 我仔细看了下代码 你一开始说的那个bug之前修了 42ca1733
你问题一开始没描述清楚 我以为你是开了上报自发消息的
因为你题目开头一句"目前制作转发消息"我不小心搞错重点了 实际上这个bug的重点是 _bot会上报自己给自己发的消息_
我一开始的回答实际上是基于这点的 不好意思 但如果可以的话 我希望下次能描述清楚一点()
此外 自发消息的 PostType 现在应当为 message_sent 可以根据这点判断消息是否为自己发出的
(如果开了上报自发消息的话 没开的话服务器不会收到消息推送)
