### ISSUE TITLE
bug: QQ过久没接收到消息时重新刷新

### ISSUE THREAD

**Issue by MejiroRina** [whitechi73/OpenShamrock#115]
### 描述功能
在一些比较特别的网络环境下运行QQ时，会发生QQ运行了一段时间之后不再接收消息的问题(即使QQ仍然在前台)，并且QQ内下拉刷新只会拉取新消息，而不会继续更新消息。
以目前的观察来看，该情况发生的情况下只有重启QQ才可重新获取消息，因此需要该功能。

### 实现方法

目前能想到的方法是强行终止QQ并重新激活。

**Comment by MejiroRina** [comment]
QQ版本实测8.9.85和最新8.9.93均不行
以及该问题是QQ自身的问题，实测取消运行Shamrock也会发生

**Comment by MejiroRina** [comment]
追加信息: 刚刚使用了未经LSPatch的原版QQ测试，仍然会出现此问题
网络环境为校园网
因此这并非Shamrock的bug

**Comment by whitechi73** [comment]
在安卓系统中，当设备长时间处于待机状态时，为了节省电量，系统会采取一些措施来降低功耗。其中一个措施是断开网络连接。

当设备进入待机状态时，安卓系统会进入一种低功耗模式，称为Doze模式。在Doze模式下，系统会限制应用程序的网络访问，以减少网络活动对电池寿命的影响。这意味着应用程序在待机状态下可能无法保持网络连接。

除了Doze模式，安卓系统还引入了一种称为App Standby的机制。App Standby会根据应用程序的使用情况和用户行为来决定应用程序的运行状态。当应用程序进入App Standby状态时，系统会限制其网络访问能力，从而减少不必要的网络活动。

这些机制旨在平衡设备的待机时间和电池寿命之间的关系。虽然这些机制可以延长电池寿命，但也可能导致某些应用程序在待机状态下无法及时接收到网络数据或推送通知。为了确保应用程序在待机状态下能够正常工作，开发者可以使用一些技术，如使用后台服务或使用高优先级的推送通知。

需要注意的是，不同的安卓版本和设备厂商可能会有不同的待机策略和机制。因此，具体的底层机制可能会因设备和系统版本而有所不同。
