### ISSUE TITLE
bug: 无法填写36个字符以上的token

### ISSUE THREAD

**Issue by icecreamx89** [whitechi73/OpenShamrock#117]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
无法填写36个字符以上的token，直接粘贴显示token不符合格式，如果在配置文件内直接修改会导致QQ无法加载shamrock，
无论填写default_token还是单独配置token都会出现此问题。
### 复现 Bug
![image](https://github.com/whitechi73/OpenShamrock/assets/65714465/a84997e6-6e4a-4ba6-96d2-2221040ad700)
## 系统信息

- Shamrock 版本: Shamrock-v1.0.6-dev.2c3466b
- Android 版本: 10
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: Sony H8296
- 设备的 CPU 架构: arm64-v8a

**Comment by whitechi73** [comment]
显而易见，您的配置文件格式错了。

**Comment by icecreamx89** [comment]
> 显而易见，您的配置文件格式错了。
您好，之前启动不了我发现是配置文件adress结尾少了个“，”，现在我在自动生成的配置文件基础上修改如下：

{
  default_token: "1111111111111111111111111111111111111111111111111111111111111111",
  active_websocket: {
    address: "0.0.0.0",
    port: 5800
  },
  passive_websocket: [
    {
      address: "wss://123456789",
      heartbeat_interval: 116641
    }
  ]
}

可以正常启动，但是每次启动default_token和heartbeat_interval均会被重置，变成：

{
  default_token: "",
  active_websocket: {
    address: "0.0.0.0",
    port: 5800
  },
  passive_websocket: [
    {
      address: "wss://123456789"
    }
  ]
}
请问具体要怎么填写配置文件，主要是长token

**Comment by fuqiuluo** [comment]
看看日志？

**Comment by lindongbin** [comment]
WARN [Shamrock] unable to load XSharedPreferences
我也有这个提示，请问有什么影响吗？

**Comment by whitechi73** [comment]
> WARN [Shamrock] unable to load XSharedPreferences 我也有这个提示，请问有什么影响吗？

没有影响
