### ISSUE TITLE
bug: 配置文件错误

### ISSUE THREAD

**Issue by HollisMeynell** [whitechi73/OpenShamrock#118]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

使用指南中提示的配置路径 `Shamrock 主目录 + /config.json`
![image](https://github.com/whitechi73/OpenShamrock/assets/56613764/93b4a6e0-bb28-4fee-8783-b1a2f8264fbb)
默认配置内容非标准json (key并未被引号包围, 指南中则被引号包围)
![image](https://github.com/whitechi73/OpenShamrock/assets/56613764/b71fe2a5-ba24-4d35-a40e-287a9e3d2d55)
若修改配置文件, 重启后会被重置
强行将key使用引号包裹则无法正常启动OpenShamrock

### 复现 Bug

默认配置
![image](https://github.com/whitechi73/OpenShamrock/assets/56613764/1472e4ef-4e82-42f8-9c2c-cd5eae5dfad9)
修改后
![image](https://github.com/whitechi73/OpenShamrock/assets/56613764/93e951e8-645c-48eb-a437-f886db8650cc)
重启框架, qq 后配置重置
![gif](https://github.com/whitechi73/OpenShamrock/assets/56613764/26ead388-7753-46dc-9ebf-91be980b1b70)

## 系统信息

- Shamrock 版本: 1.0.6 dev b5a9884
- Android 版本: 12
- LSPosed 框架版本: 1.9.2 (7024)
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by fuqiuluo** [comment]
文档说明了，这里的json采用Json5标准。
