### ISSUE TITLE
bug: 戳一戳事件在部分群聊报错，尝试回复到不存在的群

### ISSUE THREAD

**Issue by lava081** [whitechi73/OpenShamrock#124]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

部分群聊收到戳一戳时报错
![Screenshot_20231203_225846_moe fuqiuluo shamrock](https://github.com/whitechi73/OpenShamrock/assets/69086800/4b00d5e4-11ca-441e-ab74-03907fb68e47)
机器人也收不到戳一戳事件

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

群聊内戳一戳机器人或其他人
机器人收不到这条戳一戳
shamrock对应出现上述报错

## 系统信息

 - Shamrock 版本： Shamrock-v1.0.7-dev.97534b0-all
 - Android 版本： 12
 - LSPosed 框架版本： LSPatch 0.5.1
 - 设备的制造商和型号： HUAWEI HONOR BMH-AN10
 - 设备的 CPU 架构： arm64-v8a

**Comment by Simplxss** [comment]
另外能试下精华消息和群名片有没有问题吗？

**Comment by lava081** [comment]
该群内多个接入shamrock的机器人接收到戳一戳时均出现了此报错，查询群打卡记录正常获取。

**Comment by Simplxss** [comment]
> 该群内多个接入shamrock的机器人接收到戳一戳时均出现了此报错，查询群打卡记录正常获取。

不是查询群打卡记录 是事件(新加的 还没写文档) 看下log

**Comment by Simplxss** [comment]
我再看看

**Comment by Simplxss** [comment]
另外能测试下精华消息和群名片吗 这俩可能也有问题

**Comment by ikechan8370** [comment]
确实 精华也是一样

**Comment by Simplxss** [comment]
试一下ci的 应该没问题了吧

**Comment by lava081** [comment]
恢复了
