### ISSUE TITLE
bug: 获取群公告时其内容未被解码

### ISSUE THREAD

**Issue by Ghost-chu** [whitechi73/OpenShamrock#126]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

参见 https://github.com/MrXiaoM/Overflow/issues/2#issuecomment-1837700468

### 复现 Bug

通过 Mirai API 获取群公告，其群公告未被解码。https://github.com/MrXiaoM/Overflow/issues/2#issuecomment-1837700468

## 系统信息

- Shamrock 版本: 1.0.7-dev-6201d12-Xposed
- Android 版本: 12 （MuMu模拟器12）
- LSPosed 框架版本: LsPatch 0.6 (398)
- 设备的制造商和型号: MuMu模拟器12 - HUAWEI MGA-AL00
- 设备的 CPU 架构: x86_64 arm64-v8a x86 armeabi-v7a armebai

**Comment by whitechi73** [comment]
#125
