### ISSUE TITLE
bug: 收到群消息会重发请求，一下子请求回调接口五六个请求，接口都是走的内网切接口状态都为200

### ISSUE THREAD

**Issue by tpa-wy** [whitechi73/OpenShamrock#13]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:32 +0800] "POST / HTTP/1.1" 200 99 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
192.168.0.103 - - [04/Nov/2023:00:59:33 +0800] "POST / HTTP/1.1" 200 12 "-" "Shamrock/1.0.5-dev.4713310"
一个消息能重发五六遍，突然就这样了一开始是正常的，今天才接入的这个框架，原先使用的是go-cqhttp
希望新增两个api，获取所有禁言的用户以及时间
获取单个用户是否被禁言

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 最新版
- Android 版本: 11
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by tpa-wy** [comment]
目前重启qq和框架已经解决，希望可以解决这个问题

**Comment by tpa-wy** [comment]
多挂了几小时，又出现了，而且重发还在增多

**Comment by JUST-HK416D** [comment]
我前两天也出现过一次，双重上报，我是被动WebSocket，相同的是，重启解决了
![NWOITSXR{_F`8D{TICPS8@D](https://github.com/whitechi73/OpenShamrock/assets/90328461/7722d43b-b0f2-435a-b18f-3d3b2b5e0737)

**Comment by tpa-wy** [comment]
是的，挂机久了就会出现，我怀疑是多次new了实例，我现在的解决方法是
 $lock = Cache::store('redis')->lock("bot-message-{$message_id}", 10); // 尝试获取一个10秒的锁
                        if (!$lock->get()) {
                            // return $data;
                            // $data["reply"] = "触发锁了";
                            return $data;
                        }
                        $data = $this->group($content);
                        $lock->release(); // 释放锁
                        写了一个锁，消息id

**Comment by CJReinforce** [comment]
同样遇到了，被动Websocket。随着挂载时间增加，会多次建立ws连接（new多个实例）。我挂载了三个小时，现在发一个`/ping`，能返回8个`pong`。

目前也是仿照[上面的锁的方法](https://github.com/whitechi73/OpenShamrock/issues/13#issuecomment-1793376550)，在消息处理的时候加锁，避免对同一个message_id处理多次。
