### ISSUE TITLE
bug: 【补充】【无法使用upload_group_file】上传群文件 返回文件不存在，关于大佬关LSSUE的补充，本地/sdcard/11.txt  或是 C:\\aa.apk的路径都尝试过不行

### ISSUE THREAD

**Issue by sd3970566** [whitechi73/OpenShamrock#131]
### 描述 Bug
使用upload_group_file 的API接口
总是返回文件不存在！

>>发送json体如下：
{
    "action": "upload_group_file",
    "params": {
    "group_id": "173123783",
    "name": "aa.apk",
    "file": "C:\\aa.apk"
    },
    "echo": "upload_group_file"
}

<<返回信息json体如下：
{
    "status": "failed",
    "retcode": 10003,
    "data": {},
    "message": "文件不存在",
    "echo": "upload_group_file"
}

### 复现 Bug
2023年12月5日 09:10  补充
【上次有个大佬关lssue，并且发了个图，说文档里说的很清楚， 图里显示着  本地！。 我用了/sdcard/11.txt  的路径依然不行啊】
大佬别关那么快啊，问题是您试过了吗？如果试过不行，能提供一下正确调用方式吗？不管是运行SC的手机 或者是 管理端windows我都试过了。您只发了个图。说是只能上传本地。 这个本地具体是哪里。除了手机和电脑端还有哪里算本地呢？

正常按文档使用！文档里没有范例，按之前CQ的格式写本地路径  C:\\\aa.apk  或者 C:\aa.apk都试过不行。 怕中文需要转utf8. 在测试的时候都不涉及中文！
如果不是BUG的话，这个本地路径是相对于运行SC框架的手机的路径吗(难道必须把文件传到手机的sdcard上！！？)？ 还是相对于开发者windows电脑的与手机WSS连接后的实际控制端路径？C:\\\aa.apk  这样的能传吗？

## 系统信息

- Shamrock 版本: 1.0.7 -dev.6201d12
- Android 版本: 安卓12
- LSPosed 框架版本: lspatch 0.5.1(360)  框架版本:1.8.5 (6649)  
- 设备的制造商和型号: vivo IQOO neo3
- 设备的 CPU 架构: arm64-v8a

**Comment by Simplxss** [comment]
先调用上传到临时目录 用返回的地址上传群文件
