### ISSUE TITLE
bug: LSPatch后QQ闪退打不开，Shamrock显示未激活

### ISSUE THREAD

**Issue by RaphaelCS** [whitechi73/OpenShamrock#132]
### 描述 Bug

LSPatch后QQ闪退，Shamrock显示未激活

### 复现 Bug

按照文档中[使用LSPatch的方法](https://whitechi73.github.io/OpenShamrock/guide/getting-started.html#%E4%BD%BF%E7%94%A8-lspatch)操作，QQ闪退（完全无法打开），Shamrock显示未激活

## 系统信息

- Shamrock 版本: v1.0.7dev
- Android 版本: Android 11/12/13/14
- LSPosed 框架版本: 0.5.1/0.6
- 设备的制造商和型号: redroid
- 设备的 CPU 架构: amd64
- QQ版本：8.9.78/8.9.85/8.9.93

**Comment by MejiroRina** [comment]
QQ只有arm64-v8a这一个架构，没有arm64转译x86_64的兼容层就会闪退，并非Shamrock的问题

**Comment by RaphaelCS** [comment]
> QQ只有arm64-v8a这一个架构，没有arm64转译x86_64的兼容层就会闪退，并非Shamrock的问题

在redroid里安装正常的QQ apk是可以启动的，是在LSPatch过后就启动不了了

确实应该不是Shamrock的问题，但是官方文档里写了可以使用redroid，所以应该有个对应的解决方案吧

**Comment by MejiroRina** [comment]
那不应该，打开Shamrock的Debug模式后重启QQ，看看有没有什么信息

**Comment by RaphaelCS** [comment]
是这么开启Shamrock的Debug模式吗？
![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/1f8b39c1-2784-4878-8725-bdf3b1c55787)

并没有看到什么信息（点QQ之后就是QQ闪退打不开），大概因为还没激活？
![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/a8b1659f-9ef5-45ff-a861-d38c44b3a8a4)

但是LSPatch里貌似是正常的
![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/d6bf3ad5-bc0c-4016-ac09-fd6d58d62134)

![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/0c6ede68-4f51-4762-80a0-19a170e29862)

**Comment by whitechi73** [comment]
不要使用本地模式，使用便携模式！

**Comment by whitechi73** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/98259561/c74d064f-6bb0-4161-83bf-46337a986132)

文档很久没更新了，本地模式有很多问题，在非真机环境上。

**Comment by RaphaelCS** [comment]
改用集成模式试了一下，QQ依旧闪退。
操作步骤如下：
1、安装redroid-12.0.0的docker镜像
2、安装shamrock 1.0.7dev、LSPatch 0.6
3、在LSPatch中patch了QQ（安装包），使用了集成模式，并嵌入了已安装的Shamrock（安装包和installed app都试过）
4、安装patch后的QQ安装包
5、先启动LSPatch、Shamrock，然后启动QQ，结果QQ闪退

以下是LSPatch和Shamrock的截图：
![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/ed5865f8-a6fe-492b-9591-8efdf5f6891f)

![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/30490e4f-dcfa-4dfc-8210-8eb027374346)

![image](https://github.com/whitechi73/OpenShamrock/assets/46233705/02f33651-0a1c-477b-be7b-0f3af9bd4767)

**Comment by whitechi73** [comment]
8.9.93的QQ请使用Actions内的shamrock测试版

**Comment by ycly901** [comment]
> > 改用集成模式试了一下，QQ依旧闪退。操作步骤如下： 1、安装redroid-12.0.0的docker镜像 2、安装三叶草 1.0.7dev、LSPatch 0.6 3、在LSPatch中patch了QQ（安装包），使用了集成模式，并嵌入了已安装的Shamrock（安装包和installed app都试过） 4、安装patch后的QQ安装包 5、先启动LSPatch、Shamrock，然后启动QQ，结果QQ闪退
> > 以下是LSPatch和Shamrock的截图：![图像](https://private-user-images.githubusercontent.com/46233705/288019264-ed5865f8-a6fe-492b-9591-8efdf5f6891f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODYyMjcsIm5iZiI6MTcwMTc4NTkyNywicGF0aCI6Ii80NjIzMzcwNS8yODgwMTkyNjQtZWQ1ODY1ZjgtYTZmZS00OTJiLTk1OTEtOGVmZGY1ZjY4OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0MTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZDc4ODkwYjI3OTY5NjhiNzFkMjBkNGVjNjA1NDcwM2UzOWY3NmY0MjQwMzE0NDNmOWM4ZjdjMWQzODBhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WaUdK2Vy8GCffMc5VarMytaRfp62Te5e2TFTJC0RiUk)
> > ![图像](https://private-user-images.githubusercontent.com/46233705/288019171-30490e4f-dcfa-4dfc-8210-8eb027374346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODYyMjcsIm5iZiI6MTcwMTc4NTkyNywicGF0aCI6Ii80NjIzMzcwNS8yODgwMTkxNzEtMzA0OTBlNGYtZGNmYS00ZGZjLTgyMTAtOGViMDI3Mzc0MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0MTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOWVmNzc4YTE1ODlhY2Q5OGY3OTI1MDE2MmNjZDE3NDAzMWM1NGM4YzNlODRkOGQ2YzZiYWVjZjkwZDViOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arfqe88kZeF_KrICJvAvY6TSs6C11zyFREFt5EJkYWc)
> > ![图像](https://private-user-images.githubusercontent.com/46233705/288019208-02f33651-0a1c-477b-be7b-0f3af9bd4767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODYyMjcsIm5iZiI6MTcwMTc4NTkyNywicGF0aCI6Ii80NjIzMzcwNS8yODgwMTkyMDgtMDJmMzM2NTEtMGExYy00NzdiLWJlN2ItMGYzYWY5YmQ0NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0MTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzExYjEzZTY5YjQzNjhiOWMyNzYxZGI0OGQ5MmMwNzZkOWQ3ZGU0YzMyNzY2NmNiZDJlNjI3N2FkNDg5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otgyjGnTh1AvSdZfmw8epMZ-YU9Nkd-kvuo2aROwOs0)
> 
> 抱歉这里忘记说QQ版本了，用的是8.9.85，不是8.9.93 刚才又尝试了一下使用最新构建（Shamrock-v1.0.7-dev.d9a045b-all），QQ依旧闪退，shamrock依旧显示未激活
> 
> 不知道在patch QQ之前是否需要先配置shamrock的设置？还是patch完再配置shamrock？
我这边遇到类似的情况，我是用本地模式安装好QQ后，然后先登录QQ把账号登陆上去，然后清掉QQ后台，在依次打开shamrock配置好后，再打开QQ，貌似QQ没有默认的登陆账号的情况下，会出现这个闪退情况，希望有帮助

**Comment by IndigoRCS** [comment]
> 我这边遇到类似的情况，我是用本地模式安装好QQ后，然后先登录QQ把账号登陆上去，然后清掉QQ后台，在依次打开shamrock配置好后，再打开QQ，貌似QQ没有默认的登陆账号的情况下，会出现这个闪退情况，希望有帮助

我这边的情况是，即使不安装Shamrock，只安装LSPatch（QQ也没安装），然后Patch QQ安装包并且安装这个Patch后的安装包，就无法打开QQ（直接闪退）

QQ: 8.9.85
LSPatch: 0.6
redroid: 12.0.0-latest
CPU架构：amd64

**Comment by Kagamia** [comment]
可以复现错误，logcat可以看到类似的Exception
```
01-31 07:25:03.366   220  1062 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.tencent.mobileqq cmp=com.tencent.mobileqq/.activity.SplashActivity} from uid 10061
01-31 07:25:03.370   220   253 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10126; state: DISABLED
01-31 07:25:03.370   220   260 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10126; state: DISABLED
01-31 07:25:03.376   127   127 D Zygote  : Forked child process 19747
01-31 07:25:03.376   220   260 I ActivityManager: Start proc 19747:com.tencent.mobileqq/u0a126 for pre-top-activity {com.tencent.mobileqq/com.tencent.mobileqq.activity.SplashActivity}
01-31 07:25:03.378 19747 19747 I Zygote  : seccomp disabled by setenforce 0
01-31 07:25:03.378 19747 19747 W encent.mobileq: Unexpected CPU variant for X86 using defaults: x86_64
01-31 07:25:03.388    78    78 E CompositionEngine: [Dim Layer for - Task=57#0] Invalid device requested composition type change: SOLID_COLOR (3) --> DEVICE (2)
01-31 07:25:03.410 19747 19747 I ndk_translation: Initialized NDK translation (aarch64)
01-31 07:25:03.454    78    78 E CompositionEngine: [Dim Layer for - Task=57#0] Invalid device requested composition type change: SOLID_COLOR (3) --> DEVICE (2)
01-31 07:25:03.483 48591 48597 I adbd    : jdwp connection from 19747
01-31 07:25:03.485   220  1062 W OomAdjuster: Fallback pre-set sched group to default: not expected top priority
01-31 07:25:03.489   143   191 E TrafficController: Failed to set the counterSet: Operation not permitted, fd: -1
01-31 07:25:03.489 19747 19747 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
01-31 07:25:03.490 19747 19747 I encent.mobileq: The ClassLoaderContext is a special shared library.
01-31 07:25:03.502 19747 19747 I LSPatch-MetaLoader: Bootstrap loader from embedment
01-31 07:25:03.520 19747 19747 D AndroidRuntime: Shutting down VM
01-31 07:25:03.521 19747 19747 E AndroidRuntime: FATAL EXCEPTION: main
01-31 07:25:03.521 19747 19747 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 19747
01-31 07:25:03.521 19747 19747 E AndroidRuntime: java.lang.ExceptionInInitializerError
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:455)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.LoadedApk.createAppFactory(LoadedApk.java:260)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:902)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.LoadedApk.getClassLoader(LoadedApk.java:982)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.LoadedApk.getResources(LoadedApk.java:1214)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6602)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-31 07:25:03.521 19747 19747 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~F2Ky6Ni02ScfLBpwJPs5tw==/com.tencent.mobileqq-SmVXmaQ8ExrgSBdyyUNkgw==/base.apk!/assets/lspatch/so/x86_64/liblspatch.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at java.lang.Runtime.load0(Runtime.java:939)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at java.lang.System.load(System.java:1628)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:404)
01-31 07:25:03.521 19747 19747 E AndroidRuntime:        ... 16 more
01-31 07:25:03.521    78    78 E CompositionEngine: [Dim Layer for - Task=57#0] Invalid device requested composition type change: SOLID_COLOR (3) --> DEVICE (2)
01-31 07:25:03.521    78    78 E CompositionEngine: [Dim Layer for - DisplayArea.Root#0] Invalid device requested composition type change: SOLID_COLOR (3) --> DEVICE (2)
01-31 07:25:03.523   220  1062 W ActivityTaskManager:   Force finishing activity com.tencent.mobileqq/.activity.SplashActivity
```

redroid已经内置了ndk_translation，个人猜测，LSPatch后（它把所有arch的liblspatch.so都打包了进去）可能出现了一些冲突，导致程序错误地在aarch64模式下引用了x86_64的so。

**Comment by chiangchingtien** [comment]
有没有解决方案，我也遇到这个问题了。在docker环境启动redroid镜像，然后使用lspatch包装apk之后启动报UnsatisfiedLinkError

**Comment by whitechi73** [comment]
> 有没有解决方案，我也遇到这个问题了。在docker环境启动redroid镜像，然后使用lspatch包装apk之后启动报UnsatisfiedLinkError

其实如果是服务器的话，内存足够是可以安装mumu模拟器什么的，只不过可能渲染会有点卡，不过不是打游戏，还是能用的。
