### ISSUE TITLE
feat: 请求支持合并转发消息

### ISSUE THREAD

**Issue by lakwsh** [whitechi73/OpenShamrock#133]
### 描述功能

请求支持合并转发消息，目前合并转发消息无法正常发送
![image](https://github.com/whitechi73/OpenShamrock/assets/13025769/fb44466b-d322-4c7e-812f-79bcb26bdf05)

**Comment by lakwsh** [comment]
普通消息转发好像没问题，我稍后再具体测试一下是什么原因

**Comment by Simplxss** [comment]
都说了不支持嵌套

**Comment by Simplxss** [comment]
暂时不打算支持 用其他替代方法吧

**Comment by lakwsh** [comment]
> 请先添加自己为好友

什么叫添加自己为好友....我这消息往群里发没有这个限制吧（而且发送者和Bot是好友啊）
PS：我同样的代码用gocq跑是没问题的（怪）
