### ISSUE TITLE
bug?: koishi android下载图片之后请求发送图片失败，该应用报错没有该文件，可能需要root?

### ISSUE THREAD

**Issue by Kesunorin** [whitechi73/OpenShamrock#135]
Shamrock 版本: 1.0.7.dev，确认是最新开发版

### 描述 Bug

koishi android我装了一个插件 `koishi-plugin-ba-plugin`
使用命令，该插件会下载相应图片发送给用户，koishi android日志显示已经找到图片，而shamrock会报错，显示文件不存在
该图片的目录是 `/data/data/cn.anillc.koishi/files/home/koishi-app/node_modules/koishi-plugin-ba-plugin/lib/ba-alin`

### 复现 Bug

使用qq向bot发送 `攻略 杂图`，koishi android控制台输出成功获取，shamrock控制台输出失败获取

### 个人猜测

首先我只了解XP的权限是比root高，但是访问`/data/data`目录下是需要root权限，xp我不清楚是否能实现，其次，该应用的存储权限已经授权也无法获取文件，我想是不是给应用root权限，就能访问`/data/data`目录下其他应用的文件?

## 系统信息

- Shamrock 版本: 1.0.7.dev
- Android 版本: 9
- LSPosed 框架版本: 1.9.2(7024) - Riru
- 设备的制造商和型号: Redmi 4 Prime
- 设备的 CPU 架构: arm64-v8a

![QQ图片20231206004404](https://github.com/whitechi73/OpenShamrock/assets/111422442/3bb58c51-4057-4872-888b-8dc458e15293)
![QQ图片20231206004400](https://github.com/whitechi73/OpenShamrock/assets/111422442/36174a29-6971-4033-a974-ad2a6cf47a80)
![QQ图片20231206004352](https://github.com/whitechi73/OpenShamrock/assets/111422442/68d08d00-2240-4a09-9bf9-8f1fa104f564)

**Comment by whitechi73** [comment]
这个目录是应用私有目录，怎么想QQ也访问不了吧？

**Comment by whitechi73** [comment]
可以尝试使用文档里面的`/download_file` API，或者把图片转base64
