### ISSUE TITLE
bug: sk挂一段时间发的消息太多，会导致能接受消息，发送不出去消息，日志也没有明显输出

### ISSUE THREAD

**Issue by foxdad** [whitechi73/OpenShamrock#14]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

这个在sk没有明显的输出，但是可以看到sk能接受到消息，但是通过接口去发送消息，sk并发送不出去消息
感觉是虚拟机内存满了，但是没有日志输出

重启就能好比之前的版本好像差了点，之前只要模拟器不挂，sk就不会挂

## 系统信息
- Shamrock 版本: 
- Android 版本:  9
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by tpa-wy** [comment]
关了？为啥呀

**Comment by tpa-wy** [comment]
我是手机挂的，我现在试试模拟器
