### ISSUE TITLE
如何在amd64架构的Linux服务器上部署OpenShamrock

### ISSUE THREAD

**Issue by IndigoRCS** [whitechi73/OpenShamrock#140]
尝试过使用redroid，但是尝试了使用LSPatch以各种方式patch之后都不成功（#132）

所以来问问如何正确地在amd64架构的Linux服务器上部署OpenShamrock
（最好是可以像redroid那样远程连接的，而不需要开启服务器本身的GUI）

**Comment by whitechi73** [comment]
只能开windows起个模拟器了，redroid有很多问题
