### ISSUE TITLE
feat: 支持Tim有可能吗？

### ISSUE THREAD

**Issue by tignioj** [whitechi73/OpenShamrock#143]
### 描述功能
有没可能支持Tim？尝试了下再redroid上运行10、11、12、13、14系统，除了11连系统都无法启动和10无法安装QQ以外，其余都能启动系统并够打开QQ，但是都是在登录时显示`com.tencent.mobileqq.msf.service.MsfService timeout`, qq版本是Android_8.9.93_64。然而Tim可以登录，所以我在想此框架能否支持Tim呢？

**Comment by aleck099** [comment]
在google官方模拟器上也是MsfService timeout捏

**Comment by tignioj** [comment]
> 在google官方模拟器上也是MsfService timeout捏

mumu模拟器可以登录最新版QQ，不知道用了什么黑科技

**Comment by whitechi73** [comment]
> > 在google官方模拟器上也是MsfService timeout捏
> 
> mumu模拟器可以登录最新版QQ，不知道用了什么黑科技

魔改了libhoudini.so，这个文件的大小和市面上流传的明显不一样。
