### ISSUE TITLE
feat: 提供扫码登录 API

### ISSUE THREAD

**Issue by lyc8503** [whitechi73/OpenShamrock#145]
### 描述功能

提供一个 API，传入一个扫码登录的二维码，自动扫码并授权登录。

可以用于某些网页如 https://qzone.qq.com/ 的快捷登录（现在账号密码和手机验证码登录都不能用了...）

**Comment by Simplxss** [comment]
为什么不直接用cookies？

**Comment by kagg886** [comment]
可以使用skey和pskey进行登录，不过这是敏感信息x

**Comment by lyc8503** [comment]
> 为什么不直接用cookies？

cookie 过期比较快, 根据我的实验一般不超过两天, 过期了就需要手动重新登陆了.

> 可以使用skey和pskey进行登录，不过这是敏感信息x

这个也是 cookie 的一部分吗?

**Comment by lyc8503** [comment]
后续使用了桌面客户端 clientKey 快速登录, 可以实现类似扫码登录的效果, 供参考
