### ISSUE TITLE
bug: 发送qq消息以后OpenShamrock没有连接到WebSocket的服务端并发送消息

### ISSUE THREAD

**Issue by hanmin0822** [whitechi73/OpenShamrock#147]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
小米9真机运行OpenShamrock，前面的步骤都ok，可以在日志里面看到接受的QQ消息了，但是设置了被动WebSocket地址以及打开被动WebSocket以后，WebSocket的服务端无法接收到消息。
已经在手机上使用ping工具确认到WebSocket服务端的通讯正常，在WebSocket服务端所在的电脑上使用go-cqhttp去访问相同地址也正常，即排除了WebSocket服务端的问题和网络问题。
顺便想知道有没有调试日志能看到WebSocket的发包情况，尝试打开【显示调试日志】也没看到

### 复现 Bug
小米9真机运行OpenShamrock。设置被动WebSocket地址 ws://192.168.2.21:8822 打开被动WebSocket选项。发送qq消息以后OpenShamrock没有连接到WebSocket的服务端并发送消息。

## 系统信息

- Shamrock 版本: v1.0.7-dev.adb7b12-arm64
- Android 版本: 11
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: 小米9
- 设备的 CPU 架构: arm

**Comment by Simplxss** [comment]
重启了吗

**Comment by hanmin0822** [comment]
抱歉回复晚了，在手机重启以后恢复正常，并且也能在log里面看到发包的情况
