### ISSUE TITLE
bug: 同步消息导致的自身消息上报

### ISSUE THREAD

**Issue by Well2333** [whitechi73/OpenShamrock#149]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

当同一账号的 **其他客户端** 发送消息时，由于QQ会多端同步消息，shamrock 会将此消息作为 **普通消息** 上报（user_id 为自己），即便 **未开启自身消息上报** 也会上报此消息。

### 复现 Bug

1. 手机登录某QQ号（例如 `123456`），并开启shamrock
2. 其他设备（例如PCQQ）也登录此QQ号
3. 使用其他设备发送消息
4. 可以观察到shamrock上报了此条消息（即便 **没开启上报自身消息**）

## 可能的修复方式

通过检查 user_id 是否为自己来判断是否为自身消息

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.7-dev.5776524-arm64](https://github.com/whitechi73/OpenShamrock/suites/18911077788/artifacts/1104414094)
- Android 版本: 12
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: 红米 K50
- 设备的 CPU 架构: arm64-v8a

**Comment by Well2333** [comment]
ref #123 #112

**Comment by Simplxss** [comment]
补充信息请直接在原issue下回复 而不是重复开issue 谢谢

**Comment by Well2333** [comment]
> 补充信息请直接在原issue下回复 而不是重复开issue 谢谢

这并不是补充信息，造成这个错误的原因并不是“上报自身消息”而是“同步消息未判明来源就上报”，其结果导致的看起来像是原issue所描述的问题，但实际上的问题根本不同。严格来说，原issue无法涵盖此问题，因此我认为开启新issue然后ref到原issue是最好的做法。
