### ISSUE TITLE
feat: 希望可以发送本地图片/语音

### ISSUE THREAD

**Issue by DDFantasyV** [whitechi73/OpenShamrock#15]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

因为OpenShamrock项目部署于虚拟机，本地文件路径无法被识别发送，导致部署在本地的bot如果需要发送图片/语音必须来源为网络。希望能够实现发送本地图片/语音的功能。

### 实现方法

设置临时资源文件夹，实现本地文件与虚拟机端文件映射

**Comment by DDFantasyV** [comment]
> NOX APP Player 模拟器 本机 /sdcard/Doenload %USERPROFILE%\Nox_share\Download

感谢回复。文件传输确实可以通过共享文件夹实现，但是bot端（以Onebot11为例）传入的文件绝对路径为本机路径，需要在发送信息时变更文件路径为虚拟机路径。

**Comment by whitechi73** [comment]
https://whitechi73.github.io/OpenShamrock/api/shamrock.html#%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6%E5%88%B0%E7%BC%93%E5%AD%98%E7%9B%AE%E5%BD%95
https://whitechi73.github.io/OpenShamrock/api/shamrock.html#%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6%E5%88%B0%E7%BC%93%E5%AD%98%E7%9B%AE%E5%BD%95
