### ISSUE TITLE
bug: 部分事件不符合Onebot V11标准

### ISSUE THREAD

**Issue by Well2333** [whitechi73/OpenShamrock#150]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

见下文

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.7-dev.5776524-arm64](https://github.com/whitechi73/OpenShamrock/suites/18911077788/artifacts/1104414094)
- Android 版本: 12
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: 红米 K50
- 设备的 CPU 架构: arm64-v8a

**Comment by Well2333** [comment]
# 群成员减少/增加

```
{'time': 1702137911, 'self_id': 1070330078, 'post_type': 'notice', 'notice_type': 'group_decrease', 'group_id': 480979583, 'target_id': 1457727761, 'user_id': 1457727761, 'sub_type': 'leave'}
```
```
{'time': 1702224083, 'self_id': 1070330078, 'post_type': 'notice', 'notice_type': 'group_increase', 'group_id': 765924234, 'sender_id': 1299226054, 'sub_type': 'approve', 'operator_id': 1299226054}
```

缺少 operator_id

文档 ：https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E6%88%90%E5%91%98%E5%87%8F%E5%B0%91

**Comment by Well2333** [comment]
# 群成员增加

```
{'time': 1702224083, 'self_id': 1070330078, 'post_type': 'notice', 'notice_type': 'group_increase', 'group_id': 765924234, 'sender_id': 1299226054, 'sub_type': 'approve', 'operator_id': 1299226054}
```

缺少 user_id

文档：https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E6%88%90%E5%91%98%E5%A2%9E%E5%8A%A0

**Comment by Well2333** [comment]
# 群禁言

```
{'time': 1702191730, 'self_id': 1070330078, 'post_type': 'notice', 'notice_type': 'group_ban', 'group_id': 1105946125, 'sender_id': 3076823485, 'target_id': 1424743018, 'user_id': 3076823485, 'sub_type': 'lift_ban', 'operator_id': 3076823485}
```

缺少 duration

文档：https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E7%A6%81%E8%A8%80

**Comment by Simplxss** [comment]
理论上这些应该都有的 能看看日志有没有报错之类的吗

**Comment by Well2333** [comment]
> 理论上这些应该都有的 能看看日志有没有报错之类的吗

没有明显的报错，例如群增加附近的三条日志

```
[00:01:22] INFO 群消息(group = GTFO礦工(765924234), uin = 1215313657, id = 892708702|895364, msg = 来个黑刺能让你难受死)
[00:01:23] INFO 群成员增加(765924234): 0, type = 130
[00:01:24] WARN 不支持的灰条类型(JSON): 1022
[00:01:24] INFO 群消息(group = GTFO礦工(765924234), uin = 198170885, id = 1285929533|895365, msg = 大家好，我是过不去R1B1的劳苦矿工一名)
```

**Comment by MoRanYue** [comment]
这里也出现了这种情况呢。

- 群聊成员增加通知：无`user_id`
- 群聊成员减少通知：无`operator_id`

**Comment by mintianzan** [comment]
> 理论上这些应该都有的 能看看日志有没有报错之类的吗
群成员减少时出现过报错：
![QQ截图20231211192149](https://github.com/whitechi73/OpenShamrock/assets/140377173/3ff2495e-a803-44d2-b00c-29c9c06072b3)

另外在onebot v11的文档里没写，get_group_member_list这个api获取的字典里应该是还有'shut_up_timestamp'记录的禁言时间戳的，shamrock获取的字典里并没有，参考nonebot插件：轮盘禁言

https://github.com/KarisAya/nonebot_plugin_russian_ban/blob/master/__init__.py#L136

136以及140两行，在shamrock环境下使用会报错KeyError

**Comment by Mythologyli** [comment]
我这里也观察到了一些错误，例如 `GroupRequestEvent` 事件：

```
12-16 22:04:12 [SUCCESS] nonebot | OneBot V11 xxxxxxx| [request.group.add]: {'time': 1702735451, 'self_id': xxxxxxx, 'post_type': 'request', 'request_type': 'group', 'flag': 'xxxxx', 'comment': 'xxxxxxx', 'sub_type': 'add', 'group_id': xxxxxxx}
```

实际上按照 onebot 11 的标准应该为：

| 字段名 | 数据类型 | 可能的值 | 说明 |
| ----- | ------ | -------- | --- |
| `time` | number (int64) | - | 事件发生的时间戳 |
| `self_id` | number (int64) | - | 收到事件的机器人 QQ 号 |
| `post_type` | string | `request` | 上报类型 |
| `request_type` | string | `group` | 请求类型 |
| `sub_type` | string | `add`、`invite` | 请求子类型，分别表示加群请求、邀请登录号入群 |
| `group_id` | number (int64) | - | 群号 |
| `user_id` | number (int64) | - | 发送请求的 QQ 号 |
| `comment` | string | - | 验证信息 |
| `flag` | string | - | 请求 flag，在调用处理请求的 API 时需要传入 |

缺少 `user_id`

**Comment by MoRanYue** [comment]
这里发现`GroupIncrease`中，时有`user_id`字段，时没有`user_id`字段。

**Comment by Simplxss** [comment]
初步判断为uin转换为QQ号的问题 应该是缓存中没有对应映射 导致返回的QQ号为空

**Comment by linya72** [comment]
遇到了相同问题，参数中缺少userid字段，大佬有办法解决吗
![IMG_20231230_145109.png](https://github.com/whitechi73/OpenShamrock/assets/107689301/5cc6a634-dacb-43ae-90a1-ae7c3c342dbd)

**Comment by MoRanYue** [comment]
> 遇到了相同问题，参数中缺少userid字段，大佬有办法解决吗 ![IMG_20231230_145109.png](https://private-user-images.githubusercontent.com/107689301/293447382-5cc6a634-dacb-43ae-90a1-ae7c3c342dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzQxMzcsIm5iZiI6MTcwMzkzMzgzNywicGF0aCI6Ii8xMDc2ODkzMDEvMjkzNDQ3MzgyLTVjYzZhNjM0LWRhY2ItNDNhZS05MGExLWFlN2MzYzM0MmRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQxMDU3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyMDk3MzM3ZWVhMDk0ODUwNGM2ZjVkOTE4MTMyNjdjMzM2ODU4NDBjOWU3Y2RlMjFlNTA2MmQ5OGYwYzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AxNberagOpXfZQ0tOve2RScaMZ2UomY3ZGriW6wazdw)

没办法解决呀，这个字段……时有时无。

现在，唯一简单一些的办法，便是将Bot后端中，将与群成员增加相关的代码去除呀。

**Comment by Well2333** [comment]
> > 遇到了相同问题，参数中缺少userid字段，大佬有办法解决吗 ![IMG_20231230_145109.png](https://private-user-images.githubusercontent.com/107689301/293447382-5cc6a634-dacb-43ae-90a1-ae7c3c342dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzQxMzcsIm5iZiI6MTcwMzkzMzgzNywicGF0aCI6Ii8xMDc2ODkzMDEvMjkzNDQ3MzgyLTVjYzZhNjM0LWRhY2ItNDNhZS05MGExLWFlN2MzYzM0MmRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQxMDU3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyMDk3MzM3ZWVhMDk0ODUwNGM2ZjVkOTE4MTMyNjdjMzM2ODU4NDBjOWU3Y2RlMjFlNTA2MmQ5OGYwYzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AxNberagOpXfZQ0tOve2RScaMZ2UomY3ZGriW6wazdw)
> 
> 没办法解决呀，这个字段……时有时无。
> 
> 现在，唯一简单一些的办法，便是将Bot后端中，将与群成员增加相关的代码去除呀。

这不是解决方法，由于这是标准中所规定的内容，就应该是错误的一方来修改相关内容，而不是要求另一方将错就错。

我不知道为什么shamrock不对发送的数据进行任何形式的校验，导致丢字段的事情时有发生，这应该**不是**kotlin无法做到导致的。

就算是因为错误导致无法正确输出对应字段，将相关id设置为0也可以作为临时的修补方案

**Comment by MoRanYue** [comment]
> > > 遇到了相同问题，参数中缺少userid字段，大佬有办法解决吗 ![IMG_20231230_145109.png](https://private-user-images.githubusercontent.com/107689301/293447382-5cc6a634-dacb-43ae-90a1-ae7c3c342dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzQxMzcsIm5iZiI6MTcwMzkzMzgzNywicGF0aCI6Ii8xMDc2ODkzMDEvMjkzNDQ3MzgyLTVjYzZhNjM0LWRhY2ItNDNhZS05MGExLWFlN2MzYzM0MmRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQxMDU3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyMDk3MzM3ZWVhMDk0ODUwNGM2ZjVkOTE4MTMyNjdjMzM2ODU4NDBjOWU3Y2RlMjFlNTA2MmQ5OGYwYzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AxNberagOpXfZQ0tOve2RScaMZ2UomY3ZGriW6wazdw)
> > 
> > 没办法解决呀，这个字段……时有时无。
> > 
> > 现在，唯一简单一些的办法，便是将Bot后端中，将与群成员增加相关的代码去除呀。
> 
> 这不是解决方法，由于这是标准中所规定的内容，就应该是错误的一方来修改相关内容，而不是要求另一方将错就错。
> 
> 我不知道为什么shamrock不对发送的数据进行任何形式的校验，导致丢字段的事情时有发生，这应该**不是**kotlin无法做到导致的。
> 
> 就算是因为错误导致无法正确输出对应字段，将相关id设置为0也可以作为临时的修补方案

可惜，这里只会js和python。并不会Kotlin，Java也只写过一点点呀。

emm，这里暂时将Bot后端的相关代码删除了。等待它修复后，再加回来呀。

**Comment by whitechi73** [comment]
![a64c1c87f73a4ae9ef0435ca38153194](https://github.com/whitechi73/OpenShamrock/assets/98259561/24ce12fa-db78-4ce8-82dc-66f111063abf)
由QQ实现可以知道，NTQQ的push推送事件推送的是一个Uid，而Ob11标准推送的是一个int64的QQ号，Shamrock会调用QQ内部的一个缓存系统去获取uid和qq的映射关系，当是一个新成员加入，qq没有缓存这个uid和qq的映射关系的时候，就会出现获取出来的qq号是`0`，这就是以上这些问题的关键所在。

**Comment by Mythologyli** [comment]
目前还是观察到了入群申请时会出现问题，表现为不符合 OneBot 标准

Shamrock 版本: [Shamrock-v1.0.7.r249.b9cfe73-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7547389186/artifacts/1173460255)
QQ 版本: 8.9.93

`{'time': 1705690876, 'self_id': 2585268770, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': xxx, 'flag': '1705690876231135;634638649;-1', 'comment': '大家好，我是xxx。'}`

缺少 `user_id`

**Comment by Simplxss** [comment]
目前在没加入之前无法获取对应uid-uin映射

**Comment by Mythologyli** [comment]
> 目前在没加入之前无法获取对应uid-uin映射

明白了~请问是否考虑再开一个 issue 追踪此问题？

**Comment by whitechi73** [comment]
> 目前还是观察到了入群申请时会出现问题，表现为不符合 OneBot 标准
> 
> Shamrock 版本: [Shamrock-v1.0.7.r249.b9cfe73-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7547389186/artifacts/1173460255) QQ 版本: 8.9.93
> 
> `{'time': 1705690876, 'self_id': 2585268770, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': xxx, 'flag': '1705690876231135;634638649;-1', 'comment': '大家好，我是xxx。'}`
> 
> 缺少 `user_id`

可以给你提供一个qqnt专属的uid，加群之后shamrock有一个api可以获取uid和uin的关系

**Comment by whitechi73** [comment]
> > 目前在没加入之前无法获取对应uid-uin映射
> 
> 明白了~请问是否考虑再开一个 issue 追踪此问题？

# 转换uid和uin的关系

端点：`get_uin_by_uid`

请求参数示例：
```json
{
    "action": "get_uin_by_uid",
    "params": {
        "uid_list": [ "u_xxx" ]
    },
    "echo": "123"
}
```

**Comment by Mythologyli** [comment]
> > 目前还是观察到了入群申请时会出现问题，表现为不符合 OneBot 标准
> > Shamrock 版本: [Shamrock-v1.0.7.r249.b9cfe73-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7547389186/artifacts/1173460255) QQ 版本: 8.9.93
> > `{'time': 1705690876, 'self_id': 2585268770, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': xxx, 'flag': '1705690876231135;634638649;-1', 'comment': '大家好，我是xxx。'}`
> > 缺少 `user_id`
> 
> 可以给你提供一个qqnt专属的uid，加群之后shamrock有一个api可以获取uid和uin的关系

感谢回复~
目前来看，是否有可能在加群之前获取 uid 和 uin 的关系呢？

**Comment by whitechi73** [comment]
> > > 目前还是观察到了入群申请时会出现问题，表现为不符合 OneBot 标准
> > > Shamrock 版本: [Shamrock-v1.0.7.r249.b9cfe73-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7547389186/artifacts/1173460255) QQ 版本: 8.9.93
> > > `{'time': 1705690876, 'self_id': 2585268770, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': xxx, 'flag': '1705690876231135;634638649;-1', 'comment': '大家好，我是xxx。'}`
> > > 缺少 `user_id`
> > 
> > 
> > 可以给你提供一个qqnt专属的uid，加群之后shamrock有一个api可以获取uid和uin的关系
> 
> 感谢回复~ 目前来看，是否有可能在加群之前获取 uid 和 uin 的关系呢？

不可以，之前伏秋洛就是因为这个东西，被调查，涉嫌窃取***

**Comment by whitechi73** [comment]
> > > 目前还是观察到了入群申请时会出现问题，表现为不符合 OneBot 标准
> > > Shamrock 版本: [Shamrock-v1.0.7.r249.b9cfe73-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7547389186/artifacts/1173460255) QQ 版本: 8.9.93
> > > `{'time': 1705690876, 'self_id': 2585268770, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': xxx, 'flag': '1705690876231135;634638649;-1', 'comment': '大家好，我是xxx。'}`
> > > 缺少 `user_id`
> > 
> > 
> > 可以给你提供一个qqnt专属的uid，加群之后shamrock有一个api可以获取uid和uin的关系
> 
> 感谢回复~ 目前来看，是否有可能在加群之前获取 uid 和 uin 的关系呢？

唯一办法就是构建一个数据库，uid不会改变，大家都把自己知道的uid和uin关系保存下来。
