### ISSUE TITLE
bug:  QQ机器人无法群聊私发群员

### ISSUE THREAD

**Issue by Yoimiyacat** [whitechi73/OpenShamrock#151]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
使用LSPatch+LSposed+shamrock搭建yunzai，群聊私发给群友报错
错误日志：
shamrock报错：
![84 ~V{ _DMV6~M7ZW28I P8](https://github.com/whitechi73/OpenShamrock/assets/135961201/300c3bdf-5b6d-4ee6-8872-ede9e7ca40b1)

云崽报错：
[MiaoYz][20:18:27.936][MARK] [[土块插件]你画我猜][ksyx] #开始你画我猜 处理完成 5ms
[MiaoYz][20:18:27.936][INFO] [喵]  发送群消息：[群号]{image:base64://...}
你画我猜已开始，请点击白布图片后，点击右下方的笔开始画画
[MiaoYz][20:18:27.938][ERRO] ApiRejection {
  code: -1,
  message: 'client not online (cmd: MessageSvc.PbSendMsg)'
}
[MiaoYz][20:18:27.948][ERRO] ApiRejection {
  code: -1,
  message: 'client not online (cmd: MessageSvc.PbSendMsg)'
}

### 复现 Bug

yunzai的你画我猜插件，机器人有管理或者群主权限，需要向群友发送题目，发送题目报错

## 系统信息

- Shamrock 版本: Shamrock-v1.0.7-dev.6201d12-all
- Android 版本: mumu模拟器
- LSPosed 框架版本: 1.9.2（7024）-Zygisk

**Comment by whitechi73** [comment]
加好友了吗？

**Comment by Yoimiyacat** [comment]
加了也聊不了，不加也聊不了

**Comment by Zyy955** [comment]
> 加了也聊不了，不加也聊不了

这和shamrock无关

**Comment by Zyy955** [comment]
> 加了也聊不了，不加也聊不了

土块的方法没有适配多bot

![Screenshot_2023-12-12-10-44-50-820_com.github.android.jpg](https://github.com/whitechi73/OpenShamrock/assets/74231782/29f22841-9ea7-4c10-9e5e-d684ade9987e)

**Comment by Yoimiyacat** [comment]
谢谢喵，我去土块提个建议！
