### ISSUE TITLE
bug: moe.fuqiuluo.shamrock-Oi4u-GDFtPf4rZo76LD_hQ==/lib/x86_64/libshamrock.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

### ISSUE THREAD

**Issue by 7125Dev** [whitechi73/OpenShamrock#153]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

X86_64架构的机器上运行redroid 11的镜像，安装了Magisk Delta并开启了Zygisk功能，也安装了LSPosed。按照文档配置好Shamorock和QQ后，qq能打开但是Shamrock提示未激活，看了LSPosed日志主要错误为标题那一行  

### 复现 Bug

（1）启动docker容器
docker run -itd --privileged \
-v ~/data11:/data \
-p 5555:5555 \
redroid/redroid:11.0.0-latest \
ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi \
ro.product.cpu.abilist64=x86_64,arm64-v8a \
ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi \
ro.dalvik.vm.isa.arm=x86 \
ro.dalvik.vm.isa.arm64=x86_64 \
ro.enable.native.bridge.exec=1 \
ro.dalvik.vm.native.bridge=libndk_translation.so \
ro.ndk_translation.version=0.2.2
（2）安装Magisk Delta
（3）安装LSPosed
（4）安装Shamrock https://github.com/whitechi73/OpenShamrock/suites/18958748442/artifacts/1108026946
（5）在LSPosed启用Shamrock模块，勾选QQ

## 系统信息

- Shamrock 版本: Shamrock-v1.0.7-dev.d388e5d-x86_64
- Android 版本: 11
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: redroid11
- 设备的 CPU 架构: X86_64

![KN{2)R_U5SBXR1WI8M9H7}6](https://github.com/whitechi73/OpenShamrock/assets/38674427/9501569e-cdc7-4f85-a66f-64360887ab32)
![E$~USX1H3%} M6E@%GVK0AV](https://github.com/whitechi73/OpenShamrock/assets/38674427/83ecf748-69c6-449d-8260-e1f8848447f2)
![V I71O`U(K7KN1243FWID71](https://github.com/whitechi73/OpenShamrock/assets/38674427/762fc1bb-2ff3-475c-b399-ee5e8cc337ed)
![FF`4T8I}(}VSSD6N7L6J5QX](https://github.com/whitechi73/OpenShamrock/assets/38674427/5d46fb23-cc0e-43fd-b5ef-977cf0aefdcf)
![P K6%G{HVYWAH{{ } OIKN6](https://github.com/whitechi73/OpenShamrock/assets/38674427/1f7e988f-bee3-4994-8644-f0055a38654c)

**Comment by fuqiuluo** [comment]
可以换ARM64版本的Shamrock试试。

**Comment by 7125Dev** [comment]
arm64的版本可以，这个版本的[QQ](https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_Android_8.9.75_64.apk)比较容易登录，其他的要不就是提示稍后重试要不就提示com.tencent.mobileqq.msf.service.msfservice timeout
![AG0X{RI5TFV(7KK(CLW60KW](https://github.com/whitechi73/OpenShamrock/assets/38674427/5b6d2c96-0202-44ee-8304-ab775c79334c)
![IW_PT6ITBCK{(YHNG{933F](https://github.com/whitechi73/OpenShamrock/assets/38674427/8218aaba-923c-4017-b65b-9334a8ccc40b)
