### ISSUE TITLE
feat: 剔除彩色昵称中的多余字符

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#154]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

彩色昵称导致群名片出现多余的字符，有部分能让控制台发声，叮叮咚咚的
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/3481fea0-dd39-4550-9d19-d732abb81ab6)
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/f559f02b-f48f-4fa1-a358-da5666c30b62)

**Comment by Simplxss** [comment]
你不用自己去掉不就行了, 其他人不要用的吗.
