### ISSUE TITLE
bug: 精华消息只能获取到一小部分

### ISSUE THREAD

**Issue by aleck099** [whitechi73/OpenShamrock#158]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

/get_essence_msg_list
只能获取到前面19条精华消息

### 复现 Bug

/get_essence_msg_list

返回：
![w](https://github.com/whitechi73/OpenShamrock/assets/33549441/9dab60fb-3c90-4fd1-970c-453de4cc7d20)
刚好对应精华消息列表拉到此处：
![E1](https://github.com/whitechi73/OpenShamrock/assets/33549441/7e2d468b-3c76-4a29-b605-aafd89cc7798)

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by ikechan8370** [comment]
可传`page`和`page_size`来分页。默认分别是0和20。文档还没有写
