### ISSUE TITLE
bug: 在MUMU模拟器上反检测启动失败

### ISSUE THREAD

**Issue by ato1815** [whitechi73/OpenShamrock#160]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

![bug](https://github.com/whitechi73/OpenShamrock/assets/149543562/ab85e77f-d0f1-4e9d-8261-0b400315acd8)

### 复现 Bug

启动QQ，在Shamrock日志里面看到错误

## 系统信息

- Shamrock 版本: 34eccda23361db4db7efd520c92d97f2dee00d79
- Android 版本: 12
- LSPosed 框架版本: 1.9.2.7049
- 设备的制造商和型号: MUMU模拟器-12
- 设备的 CPU 架构: x86_64

**Comment by whitechi73** [comment]
这个问题不会修复
