### ISSUE TITLE
bug: 发消息一次性发两条

### ISSUE THREAD

**Issue by HuaWaterED** [whitechi73/OpenShamrock#161]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

发消息一次性发两条

（如果开发者并未成功复现此bug或者其他原因，可以直接关闭此issue，造成打扰非常抱歉）

### 复现 Bug

bot框架发条消息，sm显示发两条
相关截图：
![Snipaste_2023-12-19_17-35-01](https://github.com/whitechi73/OpenShamrock/assets/116249117/23aeb5de-ef0d-45c9-8549-fceb7607ebb2)
![Snipaste_2023-12-19_17-35-45](https://github.com/whitechi73/OpenShamrock/assets/116249117/4edf2833-f49e-4410-ac13-b1d43c03724e)
![Snipaste_2023-12-19_17-36-00](https://github.com/whitechi73/OpenShamrock/assets/116249117/b364a8b9-92eb-4cbd-b5f4-a9def512c8bf)
![Snipaste_2023-12-19_17-36-34](https://github.com/whitechi73/OpenShamrock/assets/116249117/13a8bb9a-418f-42b4-ab52-86b09ce410f6)
![Snipaste_2023-12-19_17-36-45](https://github.com/whitechi73/OpenShamrock/assets/116249117/2edee4ed-89aa-4bb5-a7ff-879f93eb990e)
![Snipaste_2023-12-19_17-37-07](https://github.com/whitechi73/OpenShamrock/assets/116249117/fe567b71-8657-4b6b-b61a-511a3f569da6)
![Snipaste_2023-12-19_17-37-16](https://github.com/whitechi73/OpenShamrock/assets/116249117/b8e9609f-c0f6-4326-9f7a-2bf5093c0634)

## 系统信息

- Shamrock 版本: Shamrock-v1.0.7.r204.34eccda-all
- Android 版本: 安卓12（类原安卓）
- LSPosed 框架版本: 1.9.2（7024）
- 设备的制造商和型号: MI Mix2s
- 设备的 CPU 架构: ARM64

**Comment by Simplxss** [comment]
所以怎么复现 有什么特定条件 你发一堆聊天记录干嘛

**Comment by HuaWaterED** [comment]
触发不是次次会触发，目前这个问题比较玄学

**Comment by HuaWaterED** [comment]
触发不是次次会触发，目前这个问题比较玄学，可以关闭此issue，如果后面发现了稳定的复现方法，我会重新提issue，抱歉
