### ISSUE TITLE
bug: HTTP回调模式的响应和动作列表问题

### ISSUE THREAD

**Issue by qcnhy** [whitechi73/OpenShamrock#166]
## 系统信息

- Shamrock 版本: 1.0.7-dev.201d12
- Android 版本: 13
- LSPosed 框架版本: 1.99.2
- 设备的制造商和型号: 小米 10 Pro
- 设备的 CPU 架构: arm4-v8a

![new ducument](https://github.com/whitechi73/OpenShamrock/assets/42377311/27a83eeb-8d6e-438b-8ad0-213ee58283d6)
1. 上方错误是按照https://12.onebot.dev/connect/communication/http-webhook/返回204代码无需处理，因此没有正文
![image](https://github.com/whitechi73/OpenShamrock/assets/42377311/a08b3b0b-d1cf-4e54-9b48-9c0f0da49429)
但模块却提示Json解码相关的报错，请问HTTP回调模式下，如果无需处理应该作何响应呢？
2. 按照https://12.onebot.dev/connect/communication/http-webhook/，如有动作处理需要返回一个json列表
![image](https://github.com/whitechi73/OpenShamrock/assets/42377311/7f8ab7b2-e1c6-46c0-abb7-e8fb2e8bce2b)
但模块返回错误显示需要一个JsonObject 请问这里是否不能传递数组列表，只能单步操作呢？

**Comment by qcnhy** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/42377311/e008e51b-f410-4740-b587-23b45069b5f0)

**Comment by whitechi73** [comment]
https://github.com/whitechi73/OpenShamrock/commit/aeabc66067d329b0a55d969865a99e009a2f4b21
试试这个

**Comment by qcnhy** [comment]
> [aeabc66](https://github.com/whitechi73/OpenShamrock/commit/aeabc66067d329b0a55d969865a99e009a2f4b21) 试试这个

这个是？有点看不是很明白。
我理解了一下是只支持快速回复快速操作的那些操作嘛？

**Comment by qcnhy** [comment]
> [aeabc66](https://github.com/whitechi73/OpenShamrock/commit/aeabc66067d329b0a55d969865a99e009a2f4b21) 试试这个

![new ducument](https://github.com/whitechi73/OpenShamrock/assets/42377311/dabacc70-aad2-4fe0-8336-9a718fbb4691)

**Comment by qcnhy** [comment]
204已经不会有报错了

**Comment by qcnhy** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/42377311/935f9b9b-c0ce-44ef-8c16-8157104009ed)
没有日志报错 整不会了。。
