### ISSUE TITLE
bug: Shamrock群组成员增加事件 新增成员QQ 获取问题

### ISSUE THREAD

**Issue by nanachi-sh** [whitechi73/OpenShamrock#174]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

~1200人的群内，新入群成员的QQ获取失败，子类型为approve，user_id与target_id皆为-1
但是我新开一个测试群，仅2人的情况下(我和机器人)，新入群成员的QQ获取没问题，子类型同样是approve，user_id与target_id皆为新入群成员的QQ

## 系统信息

- Shamrock 版本: 1.0.7.r221.c28c998
- Android 版本: 9
- LSPosed 框架版本: 1.9.2 (7024) - Zygisk
- 设备的制造商和型号: BlissOS 11.13
- 设备的 CPU 架构: x86_64

**Comment by Mythologyli** [comment]
同样观察到此问题，QQ 版本为 8.9.93，群内人数 300+

**Comment by MoRanYue** [comment]
和这个#150的问题差不多呢
