### ISSUE TITLE
feat: 希望可以增加群打卡功能的消息接收和发送API

### ISSUE THREAD

**Issue by okashi-ya** [whitechi73/OpenShamrock#176]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

目前有人群打卡会有警告日志：
![image](https://github.com/whitechi73/OpenShamrock/assets/49012015/aab97750-b862-4a8c-8d30-8b7d3f44d68d)
希望可以新增一个API用来群打卡，并且当有人打卡时可以正确获取到消息~

**Comment by ikechan8370** [comment]
群打卡是有API的 https://whitechi73.github.io/OpenShamrock/api/group.html#%E7%BE%A4%E6%89%93%E5%8D%A1

**Comment by okashi-ya** [comment]
> 群打卡是有API的 https://whitechi73.github.io/OpenShamrock/api/group.html#%E7%BE%A4%E6%89%93%E5%8D%A1

啊，好的！那应该就剩下这个接收打卡消息的问题了

**Comment by Simplxss** [comment]
在设置里面把防止调用栈检测关了 再看下日志报错是什么
