### ISSUE TITLE
bug?: OutOfMemoryError

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#184]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

# [（非最新开发版）](https://github.com/whitechi73/OpenShamrock/commit/71dd9469ca60cbfec09b9088c4b61f51f4db41fb)

java.lang.OutOfMemoryError: Failed to allocate a 83886096 byte allocation with 8388608 free bytes and 49MB until OOM, target footprint 225387024, growth limit 268435456

[moe.fuqiuluo.shamrock_2024-01-02T18_10_13.989.log](https://github.com/whitechi73/OpenShamrock/files/13811912/moe.fuqiuluo.shamrock_2024-01-02T18_10_13.989.log)

不知道是不是bug，8G的RAM只开了两个四叶草和两个QQ应该不会OOM？

### 复现 Bug

双开用户，MIUI省电策略无限制，驻于后台

## 系统信息

- Shamrock 版本: [1.0.7.r223.71dd946](https://github.com/whitechi73/OpenShamrock/commit/71dd9469ca60cbfec09b9088c4b61f51f4db41fb)
- Android 版本: 14
- LSPosed 框架版本: v1.9.2-7024
- 设备的制造商和型号: Redmi K20 Pro
- 设备的 CPU 架构: arm64

**Comment by whitechi73** [comment]
不建议Shamrock App在后台挂着
