### ISSUE TITLE
bug: 加好友接口并不能顺利处理请求

### ISSUE THREAD

**Issue by aknyzsd** [whitechi73/OpenShamrock#185]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
如图所示收到了请求，但是并没有处理，shamrock和gocq的接口不是一样的嘛，而且在模拟器上手动同意加好友会被QQ自动切换回手机协议导致掉线![Screenshot_20240102_232541_com.wujie.connect_edit_1964805471740817.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/56d5a937-487e-4893-89b1-78c5f62df4b9)![Screenshot_20240102_232518_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/40670ac0-5fdb-4da4-abdd-50a8341953aa)
请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息
![Screenshot_20240103_185647_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/b5605dc8-018b-427e-9e91-1900f0f75b3b)
- Shamrock 版本: 1.0.7
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by ikechan8370** [comment]
日志里没有看到有用信息 你机器人端是怎么处理的？

**Comment by aknyzsd** [comment]
正常情况应该是bot端自动添加好友
之前在gocq下是能用的，迁移到shamrock后毫无反应，只有nb端显示收到信息运行完成但是并没有处理加好友信息
以上应该是有关的所有日志了
还是说shamrock和gocq在加好友的接口上有些差异我没注意到qwq

**Comment by mystringEmpty** [comment]
我也遇到了，看了下问题在'request_type': 'friend '上，friend后面多一个空格，所以这个事件没有被识别成好友请求

**Comment by whitechi73** [comment]
> 我也遇到了，看了下问题在'request_type': 'friend '上，friend后面多一个空格，所以这个事件没有被识别成好友请求

```kotlin
@Serializable
internal enum class RequestType {
    @SerialName("friend") Friend,
    @SerialName("group") Group,
}
```
最新构建的代码没发现问题

**Comment by aknyzsd** [comment]
> 我也遇到了，看了下问题在'request_type': 'friend '上，friend后面多一个空格，所以这个事件没有被识别成好友请求

加群也是一样的没有反馈qwq

**Comment by whitechi73** [comment]
> > 我也遇到了，看了下问题在'request_type': 'friend '上，friend后面多一个空格，所以这个事件没有被识别成好友请求
> 
> 加群也是一样的没有反馈qwq

未发现空格？空格的好像是旧的构建版本，好像之前修了

**Comment by aknyzsd** [comment]
> > > 我也遇到了，看了下问题在'request_type': 'friend '上，friend后面多一个空格，所以这个事件没有被识别成好友请求
> > 
> > 加群也是一样的没有反馈qwq
> 
> 未发现空格？空格的好像是旧的构建版本，好像之前修了

目前使用版本1.0.7-dev-620d12
有没有可能不是空格的问题，因为不只是加好友，加群貌似也无响应

**Comment by aknyzsd** [comment]
总结了一下，请求事件未能自动转为群请求事件和好友请求事件，以此之前gocq上群请求事件的部分属性和接口不能使用，如comment，approve()，get_user_id()，此外bot.get_group_info()请求出错
