### ISSUE TITLE
feat: 希望可以连接多个反向ws地址

### ISSUE THREAD

**Issue by pk4ever1** [whitechi73/OpenShamrock#188]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

希望可以连接多个反向ws地址。
目前只能填一个地址。但我想同时使用两种机器人（nonebot和koishi）。
试过使用不同连接方式同时接入，但除了反向ws都不成功。

（反向ws指的是被动ws）

**Comment by wuhen007** [comment]
不是一直都可以吗？

**Comment by pk4ever1** [comment]
> 不是一直都可以吗？

确实可以
