### ISSUE TITLE
bug: 在8.9.93版本QQ下强制pad协议失效

### ISSUE THREAD

**Issue by aknyzsd** [whitechi73/OpenShamrock#190]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
使用lspatch安装，没有使用shizuku框架，嵌入模式加载模块但是不能使用pad协议，手机被顶下线了![Screenshot_20240105_190944_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/cf18f5cc-e2f7-44d1-90de-7394baf3c537)![Screenshot_20240105_191004.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/fc49d1a4-c237-4702-9e32-a1a27072e580)

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.0.7
- Android 版本: 13
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构: x86_64

**Comment by aknyzsd** [comment]
之前8.9.88版本也不能使用pad协议了![Screenshot_20240106_070527_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/62d16bc1-43e9-4871-86e3-da4d6797a231)![Screenshot_20240106_070550_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/5e8aa748-153d-4bbd-beb5-7aa36731ef13)

**Comment by aknyzsd** [comment]
之前备份过的模拟器被禁止登录![Screenshot_20240106_071028_com.wujie.connect.jpg](https://github.com/whitechi73/OpenShamrock/assets/121467598/6e3973ee-9da3-469a-9bf2-7c23f52750d9)

**Comment by send-97** [comment]
模拟器禁止登录我的解决方案是卸载当前版本qq换一个可用的其他版本qq再进行登录
