### ISSUE TITLE
feat: 支持qq官方机器人大图模板

### ISSUE THREAD

**Issue by wuuconix** [whitechi73/OpenShamrock#192]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

请问是否有机会支持发送 官方QQ机器人支持的相关特殊消息，如[37 大图模板](https://bot.q.qq.com/wiki/develop/api/openapi/message/template/template_37.html)

### 实现方法

通过观察官方QQ机器人返回的message内容，也许可以实现重放。

**Comment by whitechi73** [comment]
QQ客户端无法发送Markdown，除非某天官方放开限制。
