### ISSUE TITLE
feat: 希望添加QQ重启按钮

### ISSUE THREAD

**Issue by wdssfff00** [whitechi73/OpenShamrock#195]
### 描述功能

修改完Shamrock的WebSocket相关的所有配置都需要重新启动生效，每次都得手动去QQ软件信息那里点结束运行，希望shamrock软件内增加重启按钮方便QQ重启（我是MIUI14应用多开，多开QQ和多开shamrock实现机器人和大号不冲突，希望重启功能对分身QQ也有效）

### 实现方法

类似面具和dia右上角重启方案（面具是系统重启，dia对话框取消模块是软件重启、杀死、启动，并且有root方案）

**Comment by callng** [comment]
manual reboot
