### ISSUE TITLE
bug: 向不存在的群聊发送消息时，会尝试发送多条消息

### ISSUE THREAD

**Issue by PaienNate** [whitechi73/OpenShamrock#196]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
如题，在部署骰子时，需要退出部分群，而这些群可能是解散的群聊。此时调用send_group_msg会导致发送多条消息。

（下图为复现时抓包正向WS的图）

![image](https://github.com/whitechi73/OpenShamrock/assets/68044286/0ddf7eb4-4ae4-4403-8a54-b656407c92fb)

此时其会尝试发送多条消息：

![image](https://github.com/whitechi73/OpenShamrock/assets/68044286/7afb622a-f45b-4447-af0e-4b0016fcb9b9)

同样的代码，在群聊存在时正常：

![image](https://github.com/whitechi73/OpenShamrock/assets/68044286/bc63257f-5542-42bd-a1cd-7cdd8ef462c3)

此时的部分日志如下：（注：946449819为已经不存在的群号）
![image](https://github.com/whitechi73/OpenShamrock/assets/68044286/33326804-9312-40ce-a698-b779c2f86081)

![image](https://github.com/whitechi73/OpenShamrock/assets/68044286/99b5d7f9-6ac8-48ec-97fa-10efb7878351)

### 复现 Bug

B号拉A号进群，然后踢出A号或解散群聊，之后再次尝试调用发送群聊消息的接口。

## 系统信息
（注：在模拟器上亦复现，模拟器为MuMu12.）
- Shamrock 版本: 1.0.7.R244.fdd769d
- Android 版本: 13
- LSPosed 框架版本: 1.9.2[7024]
- 设备的制造商和型号: XiaoMi Star(Mi11 Ultra)
- 设备的 CPU 架构: arm64
- QQ版本：8.9.83

**Comment by Simplxss** [comment]
因为发送失败会自动重试 你不应该自己考虑下为什么会向不存在的群聊发消息吗
