### ISSUE TITLE
bug: 会睡死？我不确定是我的设备问题还是软件问题

### ISSUE THREAD

**Issue by Fahaxikiii** [whitechi73/OpenShamrock#197]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

息屏后软件运行一段时候后就会睡死，虽然保持在软件界面但不能接受消息，日志没有输出

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.0.7.r244.fdd769d
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7058)
- 设备的制造商和型号: xiaomi munch
- 设备的 CPU 架构: arm64
  

另外我做了个模块来保证软件一直运行，麻烦指正一下，
![image](https://github.com/whitechi73/OpenShamrock/assets/93320886/96287a03-45f3-4e98-8a76-682c3394edc8)

**Comment by MoRanYue** [comment]
（何不使用LSPosed模块 AppRetention 来进行保活呀？）

**Comment by Fahaxikiii** [comment]
> （何不使用LSPosed模块 AppRetention 来进行保活呀？）
> 
> emm，如果，大多数睡死的情况，还是因为系统的Doze模式呀。建议打开OpenShamrock 实验室 分栏中的“禁用Doze模式”呀。
> 
> 也可以将QQ加入游戏中心，使用游戏中心的“息屏挂机”功能呀

我开了禁用doze模式。我是红米刷的Flyme（可能是这个原因？）。现在用模块已经可以清后台使用了。我QQ没有问题，就是shamrock息屏几个小时之后就会睡死。感谢你提醒我游戏中心的息屏挂机，Flyme10没有永不锁屏，导致我之前刷了个假装息屏没有用。
