### ISSUE TITLE
feat: 在app中可以修改配置文件信息

### ISSUE THREAD

**Issue by eiriksgata** [whitechi73/OpenShamrock#198]
### 描述功能

为了方便用户使用，可以考虑在app中修改websocket的连接地址、端口号、token等信息。
增加一个新的按钮，用于启动和关闭连接websocket client。
修改配置信息后，保存至用户本地配置文件，并重新载入配置信息。

**Comment by Simplxss** [comment]
![c1d091e279003e2d87d26ffb0f26a1be](https://github.com/whitechi73/OpenShamrock/assets/44570052/9e8b8933-2f20-4f4a-9426-e48888e068d5)
