### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by qpdbzzz** [whitechi73/OpenShamrock#20]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

lsposed 7034，安卓14，QQ8.9.78，shamrock刚下的最新版，频道在看了两眼时必定闪退

### 复现 Bug

打开频道等几秒闪退

## 系统信息

- Shamrock 版本: 1.0.5
- Android 版本: 14
- 设备的制造商和型号: oppo/oppor11st
- 设备的 CPU 架构: 骁龙660

**Comment by LinBoyan** [comment]
[ShamrockLog.log](https://github.com/whitechi73/OpenShamrock/files/13260439/ShamrockLog.log)
尝试使用adb logcat捕获日志，Shamrock 版本: Shamrock-v1.0.5-dev.3988ad3-all，Android 版本: 12，设备的制造商和型号: HUAWEI/HONOR BMH-AN10，设备的 CPU 架构: 麒麟985
