### ISSUE TITLE
feat: 白名单群聊机器人消息定时撤回

### ISSUE THREAD

**Issue by TU-O0T** [whitechi73/OpenShamrock#201]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

在白名单指定的群聊中，机器人消息在设定时间后自动撤回

### 实现方法

有类似插件依赖数据库记录id和时间戳实现记录

**Comment by whitechi73** [comment]
已实现 https://whitechi73.github.io/OpenShamrock/api/message.html
