### ISSUE TITLE
想问一下 hook qq 的部分怎么实现的

### ISSUE THREAD

**Issue by MCredbear** [whitechi73/OpenShamrock#202]
我的 Android Stuidio 和 Idea 在这个工程上代码洞察几乎全程罢工，勉强找了一个像
`
            val service = QRoute.api(IMsgService::class.java)
            return suspendCoroutine {
                service.sendMsg(contact, uniseq.second, msg) { code, why ->
                    it.resume(code to uniseq.second)
                }
            }
`
这样的操作，但是原理理解不了一点，救救孩子吧（）
（为什么不在论坛问，因为我做了半个小时的人机验证都没有通过（绝望））

**Comment by whitechi73** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/98259561/493d82b1-fe11-4f5c-8780-913559c71996)
