### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by luosheng520qaq** [whitechi73/OpenShamrock#203]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
在正常的运行次下，挂机一段时间后，shamrock会接收到消息，但是不会向nonebot端上报消息，日志也没有打印类似于释放服务相关的错误日志，并且能确保当时shanmrock是存活的，因为发送ping 命令得到了回复。
请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug
每次在熄屏挂机一段时间后必然复现，并且已打开免死金牌与防止系统进入休眠等保护措施》

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本:1.0.7 r253.81be383 
- Android 版本: 9
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: mi 6x
- 设备的 CPU 架构: arm64

**Comment by luosheng520qaq** [comment]
检查了nb端日志 发现nb是接受到消息的 但是nb端显示正常处理之后 sm日志并没有打印预发送消息等相关日志 而且发现sm接受到一条消息 向nb端重复上报了两次

**Comment by whitechi73** [comment]
有没有提示
```kotlin
 LogCenter.log("WebSocketClient onOpen: ${handshakedata?.httpStatus}, ${handshakedata?.httpStatusMessage}")
```
类似于这种的日志呢？

**Comment by luosheng520qaq** [comment]
并没有相关错误日志 在重启设备后才正常恢复

**Comment by whitechi73** [comment]
尝试一下最新版本构建

**Comment by luosheng520qaq** [comment]
您说的最新版本构建是指[Shamrock-v1.0.7.r256.0c91028-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7592831156/artifacts/1182771553) 吗？ 已经尝试过了 并没有得到解决 不过退回1.0.6版本后似乎没遇到这个问题了

**Comment by luosheng520qaq** [comment]
好的

**Comment by luosheng520qaq** [comment]
您好 目前观察下来 问题已经解决了 没有再遇到无法上报消息的问题了
