### ISSUE TITLE
feat:寻求一个可在同台android设备上运行 shamrock和插件的方案

### ISSUE THREAD

**Issue by send-97** [whitechi73/OpenShamrock#204]
android上运行shamrock  然后需要在windows上运行插件  或者模拟器 单对于较低配置的服务器   貌似方案就不可行了

**Comment by send-97** [comment]
有自行尝试更新 在开源项目中  但是开源项目的环境配置 失败了 无法进行编译

**Comment by whitechi73** [comment]
termux欢迎您

**Comment by MoRanYue** [comment]
> 有自行尝试更新 在开源项目中  但是开源项目的环境配置 失败了 无法进行编译

Termux, please
