### ISSUE TITLE
bug: 发送消息报错

### ISSUE THREAD

**Issue by zzj2039** [whitechi73/OpenShamrock#205]
### 描述 Bug
发送消息时报错
`Expected STRING but was BEGIN_ARRAY at path $.message`

## 系统信息

- Shamrock 版本: 1.0.7 r256
- Android 版本: 9
- LSPosed 框架版本: 1.9.2 7024
- 设备的制造商和型号: pve虚拟机
- 设备的 CPU 架构: pve虚拟机

**Comment by whitechi73** [comment]
有没有详细错误日志

**Comment by zzj2039** [comment]
> 有没有详细错误日志

使用的是[https://github.com/mcdoeswhat/AmazingBot-4](url)对接的本框架

**Comment by DoyoDia** [comment]
@zzj2039 
我让amazingbot兼容了array格式。你可以来[这里](https://github.com/DoyoDia/AmazingBot-4/releases/tag/array)下载我修改好的版本，或者等待原作者合并我的[PR](https://github.com/mcdoeswhat/AmazingBot-4/pull/9)
