### ISSUE TITLE
bug: 字体颜色错误，难以阅读

### ISSUE THREAD

**Issue by zzj2039** [whitechi73/OpenShamrock#206]
### 描述 Bug
![QQ截图20240123144415](https://github.com/whitechi73/OpenShamrock/assets/98182517/b1ae2749-61cf-4614-b819-a0cb7de321d0)

## 系统信息

- Shamrock 版本: 1.0.7 r256
- Android 版本: 9
- LSPosed 框架版本: 1.9.2 7024
- 设备的制造商和型号: pve虚拟机
- 设备的 CPU 架构: pve虚拟机

**Comment by whitechi73** [comment]
Compose UI问题，无法修复，未知BUG
