### ISSUE TITLE
bug: 在使用ws反向时消息不同步

### ISSUE THREAD

**Issue by zzj2039** [whitechi73/OpenShamrock#208]
### 描述 Bug

使用sk链接反向端时不同步消息

### 复现 Bug

1.开启反向端
2.打开sk进行链接，此时消息同步正常
3.重启反向端但不对sk进行重启，sk可以重新链接到反向端，但此时反向端收不到消息
PS:比较奇怪的是在这种情况下，我等个几个小时消息又可以同步了

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by whitechi73** [comment]
请标注shamrock版本

**Comment by zzj2039** [comment]
> 请标注shamrock版本

Shamrock 版本: 1.0.7 r256
Android 版本: 9
LSPosed 框架版本: 1.9.2 7024
设备的制造商和型号: pve虚拟机
设备的 CPU 架构: pve虚拟机

**Comment by whitechi73** [comment]
切换到r259及以上试试看，还有没有这个问题
