### ISSUE TITLE
feat: 请求添加事件过滤器（filter）功能

### ISSUE THREAD

**Issue by Moetazhxi** [whitechi73/OpenShamrock#212]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

这个事件过滤器功能是我在 go-cqhttp 中见到的，个人感觉很实用，不知道 Shamrock 这边有没有啥想法🤔
相关功能的话请参见 go-cqhttp 的文档：https://docs.go-cqhttp.org/guide/eventfilter.html

下图来自 go-cqhttp 配置文件，框起来的这个地方：

![image](https://github.com/whitechi73/OpenShamrock/assets/89954416/128347d1-28c1-4b52-92ea-2f88444768ed)

**Comment by callng** [comment]
这个网址打不开了吗

**Comment by whitechi73** [comment]
实现繁琐

**Comment by Moetazhxi** [comment]
> 这个网址打不开了吗

我这边打得开呀，或者这里
https://github.com/ishkong/go-cqhttp-docs/blob/main/docs/guide/eventfilter.md

**Comment by Moetazhxi** [comment]
> 实现繁琐

也是，确实是比较难搞（哭）
说起来鸡肋，不过有时候还是真挺有用的
或是等未来 Shamrock 壮大之后再说吧，也不算个什么很重要的功能

**Comment by callng** [comment]
这些东西可以在客户端处理不是吗

**Comment by Moetazhxi** [comment]
> 这些东西可以在客户端处理不是吗

嗯，只不过在某些小情况下就不行了，比如说连接到别人提供的反向ws服务器时（机器人分身），可能也是我太依赖于之前的gocq

**Comment by whitechi73** [comment]
> > 这些东西可以在客户端处理不是吗
> 
> 嗯，只不过在某些小情况下就不行了，比如说连接到别人提供的反向ws服务器时（机器人分身），可能也是我太依赖于之前的gocq

可以求个PR？

**Comment by Moetazhxi** [comment]
> > > 这些东西可以在客户端处理不是吗
> > 
> > 
> > 嗯，只不过在某些小情况下就不行了，比如说连接到别人提供的反向ws服务器时（机器人分身），可能也是我太依赖于之前的gocq
> 
> 可以求个PR？

也不是不行草👀
那这个就先close掉吧，完后再看着来需不需要实现，确实是。。有了只会方便写完，没有也不会有什么影响的功能
