### ISSUE TITLE
feat: 收到图片消息时，希望能增加subType以表明是普通图片或是表情包等

### ISSUE THREAD

**Issue by uioasn** [whitechi73/OpenShamrock#213]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

在某些只需要处理图片的场景中，方便过滤掉部分表情包图片。
可参考[cqhttp的图片拓展](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md)

**Comment by callng** [comment]
很好的想法，爱来至瓷器。
