### ISSUE TITLE
bug: 踢人API的 reject_add_request 是否拒绝再次加群 没有生效

### ISSUE THREAD

**Issue by kaifadoushifeifa** [whitechi73/OpenShamrock#214]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

![image](https://github.com/whitechi73/OpenShamrock/assets/63245149/a1d87f35-48e0-41d6-8c34-df3b9414d56d)

踢人后，reject_add_request 参数设置为true ,但是被踢后的人还是能立马加入该群。容易导致该人来举报裙

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.07
- Android 版本: 9
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: 雷电模拟器
- 设备的 CPU 架构:

**Comment by whitechi73** [comment]
您使用的是HTTP API吗？

**Comment by kaifadoushifeifa** [comment]
对的 使用的是http api
