### ISSUE TITLE
feat: 反向websocket支持群戳一戳

### ISSUE THREAD

**Issue by vitechliu** [whitechi73/OpenShamrock#218]
### 描述功能

希望反向websocket实现group_touch [群戳一戳](https://whitechi73.github.io/OpenShamrock/api/group.html#%E7%BE%A4%E6%88%B3%E4%B8%80%E6%88%B3)

### 实现方法

不熟悉java，我简单看了看代码，看有一部分api是onebot的，用@OneBotHandler实现，有一部分是独有的用getpost实现，但是文档并没有说清楚，也就是说我从文档并不能看出
比如send_group_msg群签到请求，两个都有，所以支持http和websocket，
但是group_touch群戳一戳这个，只有getpost的部分，所以websocket发送这个请求会报错
`{"status":"failed","retcode":10002,"data":[],"message":"不支持的Action","echo":197}`

**Comment by MoRanYue** [comment]
根据源代码，有1个接口，叫做`poke`，它似乎是`group_touch`在WebSocket上的替代呀。

Action（动作）：`poke`  
参数：group_id 群号，user_id 目标用户QQ号  
返回：`data`字段无数据

**Comment by vitechliu** [comment]
> 根据源代码，有1个接口，叫做`poke`，它似乎是`group_touch`在WebSocket上的替代呀。
> 
> Action（动作）：`poke` 参数：group_id 群号，user_id 目标用户QQ号 返回：`data`字段无数据
> 
> （这个接口，并未在文档中呀）

好像是这样的。感谢，不过这种最好还是统一一下吧， 不然看文档的会有困扰
