### ISSUE TITLE
bug: 视频、音频组合发送时失败

### ISSUE THREAD

**Issue by ikechan8370** [whitechi73/OpenShamrock#22]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

当组合发送视频、音频消息时会失败

### 复现 Bug

例如调用send_group_msg，消息体为：
```
{
    "group_id": 群号,
    "message": [
        {
            "type": "video",
            "data": {
                "file": "file:///storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/Shamrock/tmpfiles/A679/FADCD7CA9D0EC94549E5F4CBB423A679"
            }
        },
        {
            "type": "text",
            "data": {
                "text": "xxx"
            }
        }
    ]
}
```
这样发出来的会变成“该消息只支持手机端查看”和一个“xxx"。如果删掉那个text消息，单独发送视频是成功的。record同理。

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by callng** [comment]
额，视频消息只能是单独发出.

**Comment by ikechan8370** [comment]
> 额，视频消息只能是单独发出.

是的。只是刚好代码处理问题发了复合的消息，多了一个空的text消息。然后没有报错之类的，只是那边提示该消息只支持手机端查看，找了半天。
