### ISSUE TITLE
bug: 作为管理员获取加群信息的时候，出现获取不到申请人qq的情况

### ISSUE THREAD

**Issue by HollisMeynell** [whitechi73/OpenShamrock#222]
### 描述 Bug

![image](https://github.com/whitechi73/OpenShamrock/assets/56613764/bbd9aac4-ffe0-4e18-b0f2-40a651f1d4e6)

获取的user_id是0

### 复现 Bug
发现能触发的请求是请求人完全没有与bot在同一个群以及加过好友，但是不确定是否为必要条件，已知如果与bot共在一个群或者有好友则正常获取到qq

## 系统信息

- Shamrock 版本: 1.0.8.r282.262af41 - Xposed
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by HollisMeynell** [comment]
[疑似相似的情况](https://github.com/whitechi73/OpenShamrock/issues/185#issuecomment-1916901468)

但是应该开一个新issue

**Comment by whitechi73** [comment]
这个是因为逐渐废弃qq号，转向uid，shamrock已经开始提供uid了

**Comment by HollisMeynell** [comment]
请问这部分相关的代码大概在哪个文件，因为目前还是有很多需要记录qq号的场景还是比较需要，我尝试一下看看

**Comment by whitechi73** [comment]
> 请问这部分相关的代码大概在哪个文件，因为目前还是有很多需要记录qq号的场景还是比较需要，我尝试一下看看

https://github.com/whitechi73/OpenShamrock/blob/db252b6b6cc38dc6af3020a4ca03586ffe0abf4c/xposed/src/main/java/moe/fuqiuluo/shamrock/helper/ContactHelper.kt#L30

**Comment by HollisMeynell** [comment]
> 这个是因为逐渐废弃qq号，转向uid，shamrock已经开始提供uid了

没搞明白这部分实现，应该是在qq里，请问有没有通过uid查询qq号的办法或者接口

**Comment by Mythologyli** [comment]
> 这里貌似可以通过ReqSystemMsgNew再查一遍拿到 我有空加一下试试

```
val flag = try {
    var reqs = requestGroupSystemMsgNew(10, 1)
    val riskReqs = requestGroupSystemMsgNew(5, 2)
    reqs = reqs + riskReqs
    val req = reqs.firstOrNull {
        it.msg_time.get() == time && it.msg?.group_code?.get() == groupCode
    }
    val seq = req?.msg_seq?.get() ?: time
    if (applier == 0L) {
        applier = req?.req_uin?.get() ?: 0L
    }
    "$seq;$groupCode;$applier"
} catch (err: Throwable) {
    "$time;$groupCode;$applier"
}
```

可以从 `requestGroupSystemMsgNew` 中拿到，但是不知道开发者不这样实现是否有一些理由（
