### ISSUE TITLE
bug: 无法批量撤回

### ISSUE THREAD

**Issue by bowen99** [whitechi73/OpenShamrock#224]
![image](https://github.com/whitechi73/OpenShamrock/assets/50953435/a076ca8a-5b96-4c94-b460-c4758c10aeb5)

### 描述 Bug

连接onebot以后，使用nonebot_plugin_admin插件时，发送撤回@xxx 10，提示如上信息

### 复现 Bug

通过 回复消息，撤回，可以撤回一条消息，不能批量撤回

## 系统信息
小米k30rpo,,s
- Shamrock 版本: 1.0.8
- Android 版本: 13
- LSPosed 框架版本: 1.9.0（7024）
- 设备的制造商和型号: 小米k40pro+
- 设备的 CPU 架构: 骁龙888

**Comment by Simplxss** [comment]
发shamrock日志

**Comment by bowen99** [comment]
![4D0DB74CE5D845317CF6DE55A85EAEAF](https://github.com/whitechi73/OpenShamrock/assets/50953435/8234b97d-7acd-4556-a8d7-9b23ffaefa4a)
![image](https://github.com/whitechi73/OpenShamrock/assets/50953435/3cde1150-a166-461c-a3cf-07a2e3af88dd)

**Comment by bowen99** [comment]
不知道是不是这个？

**Comment by Simplxss** [comment]
试一下最新的ci版 如果还是有问题 请发shamrock日志

**Comment by bowen99** [comment]
![CSC8VT$R`RV L$P}%%~Y3W5_tmb](https://github.com/whitechi73/OpenShamrock/assets/50953435/015b6113-539a-48e0-8c16-7e5e5598f6b5)

**Comment by bowen99** [comment]
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_group_msg_history timeout')
发送撤回@xx 10提示如上问题，shamrock日志里没有提示

**Comment by MoRanYue** [comment]
> nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_group_msg_history timeout')
> 发送撤回@xx 10提示如上问题，shamrock日志里没有提示

只是网络错误，应该，并不是OpenShamrock的问题呀

**Comment by Simplxss** [comment]
duplicate with #235
