### ISSUE TITLE
feat: 请求消息段格式可选array

### ISSUE THREAD

**Issue by MoonofBridge24** [whitechi73/OpenShamrock#226]
因为某个llbds插件(SparkBridge)用的是array格式进行通信的，在他们开发者群里也有尝试做过string格式的适配但是好像没得下文了，如果方便且有空的话，能不能帮添加一个可选消息段格式的选项

**Comment by whitechi73** [comment]
请详细描述

**Comment by whitechi73** [comment]
`shamrock`消息段的确使用的是`array`
```json5
{
    // ...
    [
        {
            "type": "text",
            "data": { "text": "ABCD" } 
        }
    ]
   // ...
}
```

**Comment by MoonofBridge24** [comment]
对不起，可能是之前网络状况或者其他原因没成功，但是我回去复现的时候发现居然能连上了。在这之前他们说的是因为sr消息段是srting所以连不上，我才来提的issue。非常抱歉打扰到您
