### ISSUE TITLE
bug: 发送群聊合并信息的时候，无法撤回

### ISSUE THREAD

**Issue by NAOLIU** [whitechi73/OpenShamrock#229]
### 描述 Bug

任何一个插件发送群聊合并信息的时候，无法撤回，未出现WARN和报错

## 系统信息

- Shamrock 版本: 1.0.8
- MuMu模拟器 版本:最新V3.8.1 
- 
- LSPosed 框架版本: 
- 显示已激活1.0.8.r296.e68a1ff - Xposed
- Zygisk - LSPosed v1.9.2(7024)

**Comment by Simplxss** [comment]
合并转发消息目前无法获取到msgid 年后会重构
