### ISSUE TITLE
feat: 是否可以操作QQ空间 或者获取Cookie以在后端进行QQ空间业务处理呢？

### ISSUE THREAD

**Issue by qcnhy** [whitechi73/OpenShamrock#232]
### 描述功能

您好，我原先使用易语言框架进行表白墙机器人的开发，切换到该模块后暂时使用群消息进行代替，请问是否可以支持QQ空间的操作或者获取Cookie以在业务后端进行QQ空间的操作？

### 实现方法
获取Cookie （较简单）
开发QQ空间操作API（不属于OneBot规范）

**Comment by whitechi73** [comment]
Shamrock支持获取cookie，空间的api经常变化，维护比较繁琐，建议开发者自行处理

**Comment by qcnhy** [comment]
> Shamrock支持获取cookie，空间的api经常变化，维护比较繁琐，建议开发者自行处理

请问获取方法有文档么

**Comment by qcnhy** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/42377311/4f56ee18-860b-4406-9766-b76a422da562)
