### ISSUE TITLE
bug: 接收来自新版手机QQ发送的图片时url不正确（multimedia.nt）

### ISSUE THREAD

**Issue by siuze** [whitechi73/OpenShamrock#236]
### 描述 Bug

遇到一个用户（使用安卓手机QQV9.0.17.15190）发送图片后，Openshamrock给出的图片url（如http://gchat.qpic.cn/gchatpic_new/0/0-0-571F2BC337589E28A54D2F45D436842B/0?term=2 ）无法正常打开，url访问提示404。   
  
但是该图片在本地的QQ官方客户端内可以正常查看。   
经telegram群询问，有大佬表示可能是使用的获取直链的方式旧了，该用户发的图片直链网址可能基于新版NTQQ下的 `https://multimedia.nt.qq.com.cn/ ` ，旧的方式得到的图片直链就无法访问。

### 复现 Bug

似乎难以在其他用户上复现，我让其他一些用户（同样是使用上述版本的手机QQ）发图，得到的以 `http://gchat.qpic.cn/` 开头的图片直链都可以正常打开，就那个用户比较特殊。   
但也确实是个问题，以下相关项目代码可能会对问题排查解决有帮助：  
https://github.com/fumiama/NanoBot/blob/c22d8183efca9f3fc3ca43ceb0298390db565384/helper.go#L151
https://github.com/LagrangeDev/Lagrange.Core/blob/beca0917022860368a0e6d546800d0550810cfb5/Lagrange.Core/Message/Entity/ImageEntity.cs#L17

## 系统信息

- Shamrock 版本: 1.0.8.r297.b03e026
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: honor ANE-LX1
- 设备的 CPU 架构: ARM

**Comment by siuze** [comment]
感谢大佬跟进，但好像还是不行。   
这版commit修复后我这边得到的图片数据为：
```
 OneBot V11 2549983600 | [message.group.normal]: Message 876533074 from 254014047@[群:83860001] '[image:file=afecc310c5c702efbc550802048132bb,subType=0,type=show,url=https://gchat.qpic.cn/download?appid=1407&fileid=CgkyNTQwMTQwNDcSFOs9Jn1i-uHDJ6J524CBpMxc99WeGLKDLCD_Cij9gJmhrrGEA1CAvaMB&spec=0]'
```  

域名不对，也缺乏rkey信息。修改域名后访问结果返回如下：
```
http://multimedia.nt.qq.com/download?appid=1407&fileid=CgkyNTQwMTQwNDcSFOs9Jn1i-uHDJ6J524CBpMxc99WeGLKDLCD_Cij9gJmhrrGEA1CAvaMB&rkey=0


{
"retcode": -5503011,
"retmsg": "invalid rkey",
"retryflag": 1
}
```

**Comment by siuze** [comment]
这一版commit在发送合并转发消息时还出现如下报错：
![6b82515a133724453865c44d2f4d3247](https://github.com/whitechi73/OpenShamrock/assets/54578647/1af9635d-5bb8-4728-ac75-1a26d8ea8b10)

**Comment by whitechi73** [comment]
rkey由腾讯提供，如果没有，shamrock也没办法

**Comment by whitechi73** [comment]
请使用最新的提交的构建，并切换到debug模式记录一个
![image](https://github.com/whitechi73/OpenShamrock/assets/98259561/72f6c3d9-4d7f-4aa4-85ae-e7e145ee872a)
类似于这样子的日志

**Comment by siuze** [comment]
> 请使用最新的提交的构建，并切换到debug模式记录一个 ![image](https://private-user-images.githubusercontent.com/98259561/305609947-72f6c3d9-4d7f-4aa4-85ae-e7e145ee872a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjMxNDAsIm5iZiI6MTcwODE2Mjg0MCwicGF0aCI6Ii85ODI1OTU2MS8zMDU2MDk5NDctNzJmNmMzZDktNGQ3Zi00YWE0LTg1YWUtZTdlMTQ1ZWU4NzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA5NDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzkzY2E2NDc4M2ZiYzAzYmJkMGJhYWI3N2Q2OGZkMjE1MjM0YjdjZWVhODk3ZGI5YTJmNTJhZjhlNGFkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VGd0edDUsX-Lwe4c9o8BqOSilCc87DmLwvJgCswkRPA) 类似于这样子的日志

```
[17:34:38] DEBUG receive image: PicElement{picSubType=0,fileName=5E6BA478D12B63C4D78A8A2FBC726781.jpg,fileSize=385089,picWidth=1920,picHeight=1440,original=false,md5HexStr=5e6ba478d12b63c4d78a8a2fbc726781,sourcePath=null,thumbPath=null,transferStatus=0,progress=0,picType=1000,invalidState=0,fileUuid=CgkyNTQwMTQwNDcSFBsVMcbl77EmrdKYhDN1T3x9KZ96GMHAFyD_CijUqoyNibKEA1CAvaMB,fileSubId=,thumbFileSize=0,fileBizId=null,downloadIndex=null,summary=,emojiFrom=0,emojiWebUrl=,emojiAd=EmojiAD{url=,desc=,},emojiMall=EmojiMall{packageId=0,emojiId=0,},emojiZplan=EmojiZPlan{actionId=0,actionName=,actionType=0,playerNumber=0,peerUid=0,bytesReserveInfo=,},originImageMd5=49EF9824E37CD8F7AB7C655D35862588,originImageUrl=/download?appid=1407&fileid=CgkyNTQwMTQwNDcSFBsVMcbl77EmrdKYhDN1T3x9KZ96GMHAFyD_CijUqoyNibKEA1CAvaMB&spec=0,importRichMediaContext=null,isFlashPic=null,storeID=1,}
```

**Comment by whitechi73** [comment]
现在没办法修复，只能在结尾拼一段rkey修复`&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64`

**Comment by siuze** [comment]
> 现在没办法修复，只能在结尾拼一段rkey修复`&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64`

感谢，现在暂时可以了，但确也不是什么长久之计，想问一下rkey缺失的问题在您那边是可以复现的吗，我还是不知道那个用户是极端个例还是普遍存在。

**Comment by whitechi73** [comment]
> > 现在没办法修复，只能在结尾拼一段rkey修复`&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64`
> 
> 感谢，现在暂时可以了，但确也不是什么长久之计，想问一下rkey缺失的问题在您那边是可以复现的吗，我还是不知道那个用户是极端个例还是普遍存在。

QQ后端没有给Shamrock提供rkey而是自己偷偷保存了起来，只能让QQ后端把图片下载。

**Comment by whitechi73** [comment]
> > 现在没办法修复，只能在结尾拼一段rkey修复`&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64`
> 
> 感谢，现在暂时可以了，但确也不是什么长久之计，想问一下rkey缺失的问题在您那边是可以复现的吗，我还是不知道那个用户是极端个例还是普遍存在。

测试一下新的提交还有没有问题，提供一下日志，加群反馈：151497347

**Comment by ghislaine-laios** [comment]
话说rkey是个什么性质的东西，用户的标识符吗？

**Comment by fuqiuluo** [comment]
> 话说rkey是个什么性质的东西，用户的标识符吗？

https://blog.xinrao.moe/archives/qqxie-yi-ji-shi#2024-04-29-bdh%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90

**Comment by ghislaine-laios** [comment]
> > 话说rkey是个什么性质的东西，用户的标识符吗？
> 
> https://blog.xinrao.moe/archives/qqxie-yi-ji-shi#2024-04-29-bdh%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90

谢谢
