### ISSUE TITLE
feat: 请求添加关闭ssl认证

### ISSUE THREAD

**Issue by 1143910315** [whitechi73/OpenShamrock#237]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

希望能添加界面选项以关闭ssl验证。

在模块中配置被动WebSocket，如果使用wss开头，则会使用ssl加密。但此时可能因为服务器ssl证书是无效的（自建服务器往往没有有效证书），从而拒绝连接。

我仅使用了WebSocket方案，http不确定

### 实现方法
在moe.fuqiuluo.shamrock.remote.service.WebSocketClientService的init里面，添加以下代码，即可关闭ssl验证
![image](https://github.com/whitechi73/OpenShamrock/assets/20817444/b8ff2c1e-057c-4e73-bdfe-4a451738376f)

    val sslContext = SSLContext.getInstance("TLSv1.2")
    sslContext.init(null, arrayOf<TrustManager>(@SuppressLint("CustomX509TrustManager")
        object : X509TrustManager {

            @SuppressLint("TrustAllX509TrustManager")
            override fun checkClientTrusted(chain: Array<X509Certificate?>?, authType: String?) {
            }

            @SuppressLint("TrustAllX509TrustManager")
            override fun checkServerTrusted(chain: Array<X509Certificate?>?, authType: String?) {
            }

            override fun getAcceptedIssuers(): Array<X509Certificate> {
                return arrayOf()
            }
        }), null)
        setSocketFactory(sslContext.socketFactory)

**Comment by whitechi73** [comment]
pr上来
