### ISSUE TITLE
bug: 如果设置 `token` 中带有特殊符号会出现校验错误的情况

### ISSUE THREAD

**Issue by huankong233** [whitechi73/OpenShamrock#238]
### 描述 Bug

通过 主动`websocket` 链接, 会出现鉴权失败

### 复现 Bug

在接口信息中设置 `token` 为 `123,` 

使用 `postman` 的 `websocket` 链接 会出现鉴权失败

但是如果使用 `token` 为 `123` 即可通过鉴权

## 系统信息

- Shamrock 版本: 最新构建版 [2c8094c](https://github.com/whitechi73/OpenShamrock/commit/2c8094c8c8337fcd7d4afbc68e40746accfb5b79)
- Android 版本: 12
- LSPosed 框架版本: 1.8.6-Zygisk
- 设备的制造商和型号: 红米K30SU
- 设备的 CPU 架构: arm64-v8a,armeabi-v7a,armeabi

**Comment by whitechi73** [comment]
```kotlin
           var accessToken = handshake.getFieldValue("access_token")
                .ifNullOrEmpty(handshake.getFieldValue("ticket"))
                .ifNullOrEmpty(handshake.getFieldValue("Authorization"))
                ?: throw ErrorTokenException
            if (accessToken.startsWith("Bearer ", ignoreCase = true)) {
                accessToken = accessToken.substring(7)
            }
            val tokenList = token.split(",", "|", "，")
            if (!tokenList.contains(accessToken)) {
                conn.close()
                LogCenter.log({ "WSServer连接错误(${conn.remoteSocketAddress.address.hostAddress}:${conn.remoteSocketAddress.port}) 没有提供正确的token, $accessToken。" }, Level.ERROR)
                return
            }
```

**Comment by whitechi73** [comment]
```json
{
    "rules": {
        "group_rule": {
            "black_list": [12345678], // 如果群号是`12345678`就跳过了哦！
            "white_list": []
        },
        "private_rule": {
            "black_list": [12345678],
            "white_list": []
        }
    },
    "default_token": null,
    "active_websocket": {
        "port": 5800, // 主动WS监听的端口
        "token": "aaaa1111,bbbb1111", // 同时允许两个token可使用|或,作为分割
        "tokens": ["aaaa1111", "aaaa2222"], // 使用tokens实现多token，优先级比上面那个高
        "heartbeat_interval": 15000 // 设置为null则默认15000毫秒作为心跳间隔，0则为无心跳
    },
    "passive_websocket": [
        {
            "address": "ws://xxxxxxxxx" // 这里是个例子，如果默认tk存在则使用默认token鉴权
        },
        {
            "address": "ws://aaaaaaaaa",
            "token": "aaa666", // 提供了特例化token，将不使用默认token
            "heartbeat_interval": 15000 // 设置为null则默认15000毫秒作为心跳间隔，0则为无心跳
        }
    ],
    "allow-temp-session": false // 是否允许临时消息
}
```

**Comment by huankong233** [comment]
> ```kotlin
>            var accessToken = handshake.getFieldValue("access_token")
>                 .ifNullOrEmpty(handshake.getFieldValue("ticket"))
>                 .ifNullOrEmpty(handshake.getFieldValue("Authorization"))
>                 ?: throw ErrorTokenException
>             if (accessToken.startsWith("Bearer ", ignoreCase = true)) {
>                 accessToken = accessToken.substring(7)
>             }
>             val tokenList = token.split(",", "|", "，")
>             if (!tokenList.contains(accessToken)) {
>                 conn.close()
>                 LogCenter.log({ "WSServer连接错误(${conn.remoteSocketAddress.address.hostAddress}:${conn.remoteSocketAddress.port}) 没有提供正确的token, $accessToken。" }, Level.ERROR)
>                 return
>             }
> ```

收到
