### ISSUE TITLE
bug: 发送带有图片的合并转发时图片上传速度极慢

### ISSUE THREAD

**Issue by siuze** [whitechi73/OpenShamrock#239]
### 描述 Bug

在使用包括最新构建[Shamrock-v1.0.8.r320.2c8094c](https://github.com/whitechi73/OpenShamrock/actions/runs/7941394844)、[Shamrock-v1.0.8.r317.63ce2d4](https://github.com/whitechi73/OpenShamrock/actions/runs/7925364323/artifacts/1250017517)在内的几个构建版本时发现：   
  
如果发送合并转发消息且消息中带有图片（这里假设是先发给自己再转发出去），则会在先发送图片消息给自己这一步上非常卡慢，需要**几十秒甚至一两分钟才能完成一张图片的发送**。完成所有的消息发送再转发需要数分钟之久。   这造成对面的机器人后端以为API调用超时。     

但是shamrock这边日志并无任何报错，只是单纯的卡慢，在很久很久以后，图片上传完成时也能正常给出图片上传完成的相关debug日志。并在所有图片缓慢发送完成后进行合并转发。     

该版本下非合并转发的**普通带图片消息的发送功能没有问题**，都是正常的速度，即把上述合并转发的数据直接当做普通消息发送出来，能在几秒内就完成。    

我尝试进行版本回退，发现 **版本[1.0.8.r297.b03e026](https://github.com/whitechi73/OpenShamrock/actions/runs/7785847658) 并没有上述问题** ，合并转发消息发送图片的速度是正常的，并不会在发消息给自己的这一步卡慢

### 复现 Bug

使用最新构建版本发送带有图片的合并转发消息

## 系统信息

- Shamrock 版本: v1.0.8.r320.2c8094c
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: honor ANE-LX1
- 设备的 CPU 架构: arm64-v8

**Comment by MoRanYue** [comment]
emm，因为，@whitechi73 认为，若直接发送合并转发消息，则会导致伪造聊天记录的发生呀

**Comment by siuze** [comment]
> emm，因为，@whitechi73 认为，若直接发送合并转发消息，则会导致伪造聊天记录的发生呀

是的啊，所以我知道应该要先发送给自己再转发的呀

**Comment by MoRanYue** [comment]
> > emm，因为，@whitechi73 认为，若直接发送合并转发消息，则会导致伪造聊天记录的发生呀
> 
> 是的啊，所以我知道应该要先发送给自己再转发的呀。旧版本发送给自己的这一步并不会卡慢，就像正常发消息那样快的

（好奇怪呀，这里亦需要，花费1分钟，才可发出消息呀
而这里，使用的OpenShamrock版本，并不是第1条评论所提供的呀）

**Comment by whitechi73** [comment]
需要等 @Simplxss 完善完整的协议上传合并转发消息。

**Comment by Cathgao** [comment]
目前用v1.0.8.r334.c70f3ea版本发送带有图片的合并转发消息日志会报“不支持的消息类型：image”，然后返回错误给bot后端
是正在修改此功能吗？

**Comment by Simplxss** [comment]
图片类型目前已完成 请测试下action中最新构建的shamrock

**Comment by siuze** [comment]
> 图片类型目前已完成 请测试下action中最新构建的shamrock

试了一下现在应该没问题了
