### ISSUE TITLE
bug: 插件艾特群成员功能，没有反应

### ISSUE THREAD

**Issue by bowen99** [whitechi73/OpenShamrock#240]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

nonebot提示：
**nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo='4')**
sharmrock提示：
![image](https://github.com/whitechi73/OpenShamrock/assets/50953435/16156cb3-6f1e-4542-87f3-f69fd2d90f79)

### 复现 Bug

艾特群成员

## 系统信息

mumu模拟器

Shamrock 版本: 1.0.8 r320 2c8094c
LSPosed 框架版本: 1.9.0（7024）

**Comment by whitechi73** [comment]
缺失消息参数`type`，你应该是发送了`poke`消息，这个消息和go-cqhttp的定义不同，这个是私聊的那个戳一戳。
亦或许，你发送了`music`消息，这个消息也强制你输入type。这个不是艾特消息的问题，因为艾特不会触发缺失参数`type`。

**Comment by bowen99** [comment]
是的，发现是触发了群聊戳一戳导致的，只设置插件艾特是没有问题的
