### ISSUE TITLE
如何在被动WS中调用upload_file？

### ISSUE THREAD

**Issue by Cathgao** [whitechi73/OpenShamrock#247]
Shamrock版本：1.0.8.r344.c70f3ea
Magisk版本：27.0
QQ版本：8.9.83

文档中只说`以file格式上传文件，不要使用binary。`，并没有说明参数字段。这个API只支持http调用无法使用call_action()调用吗？

**Comment by whitechi73** [comment]
对的，目前是无法在ws中使用上传文件到shamrock接口的，仅仅可以通过
```json
{
    "type": "file",
    "data": {
        "file": "base64://***"
    }
}
```
纯WS的话，只能这样

**Comment by whitechi73** [comment]
#248
