### ISSUE TITLE
feat: 希望可以支持Ark签名

### ISSUE THREAD

**Issue by 2045632193** [whitechi73/OpenShamrock#250]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

发送json消息需要进行ark签名后获取token值，所以希望可以支持ark签名

### 实现方法

不知道怎么实现，但是看这个issue有提到https://github.com/mamoe/mirai/issues/2279

**Comment by whitechi73** [comment]
腾讯已经封死token签名接口了，现在只能特点格式的json签名

**Comment by 2045632193** [comment]
> 腾讯已经封死token签名接口了，现在只能特点格式的json签名

是这样吗？但是我看这个用腾讯文档的api还可以正常签名,并且可以正常发送http://api.xn--7gqa009h.top/doc/card_token.html
![2de4e123786838aaf0cb69f55777fb84](https://github.com/whitechi73/OpenShamrock/assets/105954191/2a327aa8-8c75-4412-aac9-b6a236aa2b0c)
![a00d7f62e8f4908267d52e59e8237ecb](https://github.com/whitechi73/OpenShamrock/assets/105954191/1c0f22d5-bdb0-4ea3-91e4-c964097ba4ac)

**Comment by whitechi73** [comment]
这个好像有白名单

**Comment by whitechi73** [comment]
> > 腾讯已经封死token签名接口了，现在只能特点格式的json签名
> 
> 是这样吗？但是我看这个用腾讯文档的api还可以正常签名,并且可以正常发送http://api.xn--7gqa009h.top/doc/card_token.html ![2de4e123786838aaf0cb69f55777fb84](https://private-user-images.githubusercontent.com/105954191/307106749-2a327aa8-8c75-4412-aac9-b6a236aa2b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTkwOTcsIm5iZiI6MTcwODY1ODc5NywicGF0aCI6Ii8xMDU5NTQxOTEvMzA3MTA2NzQ5LTJhMzI3YWE4LThjNzUtNDQxMi1hYWM5LWI2YTIzNmFhMmIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwMzI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDAwZGUwZDIzYWFmMmRhNDFkNGE1NWQ5MDA5OGQ4ZWM2MGUwM2MyNzIwZTAzZDcxZDIyMDJhMDRhMGViODQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.viuQX9kX8RCYEzkAbgkq7dr66hIOq79CFsr9J7K1lrs) ![a00d7f62e8f4908267d52e59e8237ecb](https://private-user-images.githubusercontent.com/105954191/307107002-1c0f22d5-bdb0-4ea3-91e4-c964097ba4ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTkwOTcsIm5iZiI6MTcwODY1ODc5NywicGF0aCI6Ii8xMDU5NTQxOTEvMzA3MTA3MDAyLTFjMGYyMmQ1LWJkYjAtNGVhMy05MWU0LWM5NjQwOTdiYTRhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwMzI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzFiMTA3ZWYyNjY2YWZlNjU1NDdlNzNjOWYyZjY4MWY1Y2QzMjdhMTY0OTVmODRhNDE3NWIxY2NmYzI4NGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5LD2jiXzUs_-os2PIG-TxgJkD7ShjHv57vBT6YVIS_4)

这个是通过一个HTTP请求实现的

**Comment by SovhVgso** [comment]
可以通过腾讯文档的这个https://docs.qq.com/v2/push/ark_sig官方接口进行签名，需要提交包括skey等以及腾讯文档的cookie，且被签名的卡片中需要验证object_id这个参数，也许可以通过已有的文件进行获取，除此之外，改变其他内容并不影响卡片的发送

**Comment by NovaShen555** [comment]
mark

**Comment by Controllerdestiny** [comment]
> 可以通过腾讯文档的这个[https://docs.qq.com/v2/push/ark_sig官方接口进行签名，需要提交包括skey等以及腾讯文档的cookie，且被签名的卡片中需要验证object_id这个参数，也许可以通过已有的文件进行获取，除此之外，改变其他内容并不影响卡片的发送](https://docs.qq.com/v2/push/ark_sig%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%AD%BE%E5%90%8D%EF%BC%8C%E9%9C%80%E8%A6%81%E6%8F%90%E4%BA%A4%E5%8C%85%E6%8B%ACskey%E7%AD%89%E4%BB%A5%E5%8F%8A%E8%85%BE%E8%AE%AF%E6%96%87%E6%A1%A3%E7%9A%84cookie%EF%BC%8C%E4%B8%94%E8%A2%AB%E7%AD%BE%E5%90%8D%E7%9A%84%E5%8D%A1%E7%89%87%E4%B8%AD%E9%9C%80%E8%A6%81%E9%AA%8C%E8%AF%81object_id%E8%BF%99%E4%B8%AA%E5%8F%82%E6%95%B0%EF%BC%8C%E4%B9%9F%E8%AE%B8%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87%E5%B7%B2%E6%9C%89%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%9B%E8%A1%8C%E8%8E%B7%E5%8F%96%EF%BC%8C%E9%99%A4%E6%AD%A4%E4%B9%8B%E5%A4%96%EF%BC%8C%E6%94%B9%E5%8F%98%E5%85%B6%E4%BB%96%E5%86%85%E5%AE%B9%E5%B9%B6%E4%B8%8D%E5%BD%B1%E5%93%8D%E5%8D%A1%E7%89%87%E7%9A%84%E5%8F%91%E9%80%81)
请问这个API怎么抓到的，我弄了半天也没抓到。
