### ISSUE TITLE
bug: download_file的ws接口问题、私聊文件导致QQ崩溃问题和上传群聊文件无响应问题

### ISSUE THREAD

**Issue by xunxun2001** [whitechi73/OpenShamrock#253]
### 描述 Bug

1. 当我使用 `download_file` 的 WebSocket (ws) 接口，并传入 `name` 参数时，接口没有任何反应。不论我是否设置该参数，结果似乎总是返回一个MD5值，而非我所期望的文件名。
2. 在私聊中发送文件后，QQ应用会崩溃。这个问题在我尝试多次后持续出现。
3. 使用 `upload_group_file` 接口尝试上传文件至群聊时，没有收到任何响应，日志中仅显示“Session created”且没有“Session resume”的后续动作。

#### download_file的ws接口问题
1. 连接到Shamrock的WebSocket接口。
2. 发送包含 `download_file` 命令和 `name` 参数的消息。
3. 观察返回结果，无法得到预期的文件名，而是返回MD5值。

#### 私聊文件导致QQ崩溃
1. 在任何私聊对话中使用`upload_private_file`选择一个文件发送。
2. 文件发送后，QQ应用立即崩溃。

伪代码如下：
```python
async def on_event(self, event: PrivateMessage):
    if event.raw == 'file':
        await event.reply(self.file)
    if event.raw == 'download':
        self.file = await Bot().shamrock_download_file(
            url='https://i.pixiv.re/img-original/img/2021/07/30/22/23/51/91606424_p0.jpg'
            , name='test.jpg')
        logger.info(f'[FilePlugin] file downloaded: {self.file}')
    if event.raw == 'upload':
        await Bot().upload_private_file(user_id, self.file, 'test.jpg')
```
![27e3bc5aeca545d66c1da9753240f577](https://github.com/whitechi73/OpenShamrock/assets/55039957/d79fb65c-cb36-48f1-8677-6e415039f89a)
![4a3f345029dd5141f5b85432490cc25a](https://github.com/whitechi73/OpenShamrock/assets/55039957/6a5e6ddd-de59-4f7d-9925-1d67048a1a01)

#### 上传群聊文件无响应
1. 在任何群聊对话中使用`upload_group_file`选择一个文件发送。
2. 文件发送后，QQ应用没有任何响应，log也没任何动静

### 系统信息

- Shamrock 版本: 1.0.9.r357.68ea62e
- Android 版本: 9
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号:夜神模拟器
- 设备的CPU架构: x86_64

**Comment by whitechi73** [comment]
```
私聊文件导致QQ崩溃
在任何私聊对话中使用upload_private_file选择一个文件发送。
文件发送后，QQ应用立即崩溃。
```

没有复现

**Comment by whitechi73** [comment]
https://github.com/whitechi73/OpenShamrock/commit/252a3527a82104012078b00040d4f5da2ad18f56 请尝试该提交，并说明QQ版本。
