### ISSUE TITLE
feat: download_file支持指定语音目录

### ISSUE THREAD

**Issue by Zyy955** [whitechi73/OpenShamrock#256]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

通过指定语音目录，实现一键配置语音

**Comment by whitechi73** [comment]
https://whitechi73.github.io/OpenShamrock/api/shamrock.html#%E8%AE%A9shamrock%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6%E5%88%B0%E7%BC%93%E5%AD%98%E7%9B%AE%E5%BD%95
