### ISSUE TITLE
bug: Cookies获取失败

### ISSUE THREAD

**Issue by qcnhy** [whitechi73/OpenShamrock#259]
### 描述 Bug

{
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/get_cookies",
        "error": "Field 'com.tencent.qqnt.kernel.nativeinterface.BigDataTicket.sessionKey' is inaccessible to class 'moe.fuqiuluo.shamrock.remote.action.handlers.GetCookies' (declaration of 'moe.fuqiuluo.shamrock.remote.action.handlers.GetCookies' appears in Anonymous-DexFile@2112143494!classes4.dex)"
    }
}

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

Shamrock 版本: 1.0.9.r374.0262648
Android 版本: 13
LSPosed 框架版本: 1.9.2
设备的制造商和型号: mumu模拟器
设备的 CPU 架构: x86

**Comment by qcnhy** [comment]
bigdata_ticket 是啥

**Comment by qcnhy** [comment]
{
	"time": 1709026594,
	"self_id": 1029374115,
	"post_type": "message_sent",
	"message_type": "private",
	"sub_type": "friend",
	"message_id": 224051699,
	"target_id": 1013960147,
	"peer_id": 1029374115,
	"user_id": 1029374115,
	"message": [{
		"data": {
			"text": "测试以上"
		},
		"type": "text"
	}, {
		"data": {
			"file": "E17B4AFB92EDBF82A351485EDC06FEE9",
			"subType": 0,
			"type": "original",
			"url": "https://c2cpicdw.qpic.cn/offpic_new/0/123-0-E17B4AFB92EDBF82A351485EDC06FEE9/0?term=2"
		},
		"type": "image"
	}, {
		"data": {
			"file": "CC95237DB78D7DA2F9C93F3033B01051",
			"subType": 0,
			"type": "original",
			"url": "https://c2cpicdw.qpic.cn/offpic_new/0/123-0-CC95237DB78D7DA2F9C93F3033B01051/0?term=2"
		},
		"type": "image"
	}],
	"raw_message": "测试以上[CQ:image,file=E17B4AFB92EDBF82A351485EDC06FEE9,subType=0,type=original,url=https://c2cpicdw.qpic.cn/offpic_new/0/123-0-E17B4AFB92EDBF82A351485EDC06FEE9/0?term=2][CQ:image,file=CC95237DB78D7DA2F9C93F3033B01051,subType=0,type=original,url=https://c2cpicdw.qpic.cn/offpic_new/0/123-0-CC95237DB78D7DA2F9C93F3033B01051/0?term=2]",
	"font": 0,
	"sender": {
		"user_id": 1029374115,
		"nickname": " ",
		"card": "",
		"role": "member",
		"title": "",
		"level": ""
	},
	"temp_source": -1
}

**Comment by whitechi73** [comment]
> bigdata_ticket 是啥

上传文件什么的资源用的。
