### ISSUE TITLE
bug: `real_id` 似乎为空值？

### ISSUE THREAD

**Issue by mas-alone** [whitechi73/OpenShamrock#260]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

群员使用回复功能回复任何消息，似乎无法获取到 `real_id`
似乎是在这个版本开始才会的 https://github.com/whitechi73/OpenShamrock/actions/runs/8036123597
![QQ截图20240227221050](https://github.com/whitechi73/OpenShamrock/assets/52590027/2324bb2c-e8db-4592-95ff-9e0f719ffe72)

### 复现 Bug

群员使用回复功能回复任何消息，Onebot v11+gocq，

## 系统信息

- Shamrock 版本: r375
- Android 版本: 12
- LSPosed 框架版本: 
- 设备的制造商和型号: mumu模拟器
- 设备的 CPU 架构:

**Comment by whitechi73** [comment]
shamrock的real_id的名字叫做`message_seq`，将在最新提交添加`real_id`字段

**Comment by mas-alone** [comment]
> shamrock的real_id的名字叫做`message_seq`，将在最新提交添加`real_id`字段

似乎还是无法获取
![QQ截图20240227225804](https://github.com/whitechi73/OpenShamrock/assets/52590027/4dee0122-d58b-48ca-b5ad-41aa0ecdd6e2)

**Comment by whitechi73** [comment]
https://github.com/whitechi73/OpenShamrock/commit/4dc83fdebaf7b319680cbedca88f4865a11d0a46 试试这个，安装shamrock，彻底关闭qq后再试

**Comment by mas-alone** [comment]
> [4dc83fd](https://github.com/whitechi73/OpenShamrock/commit/4dc83fdebaf7b319680cbedca88f4865a11d0a46) 试试这个，安装shamrock，彻底关闭qq后再试

这个版本已修复，辛苦了！
