### ISSUE TITLE
bug: arm64发送语音报错

### ISSUE THREAD

**Issue by KeluIsAfkeru** [whitechi73/OpenShamrock#261]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

arm64发送语音时出现报错
![b9022ac44a29247e691d2517f01d578e](https://github.com/whitechi73/OpenShamrock/assets/107661829/5e6869d3-c693-4115-ae3b-65fe644b8b97)
![6374d984c0a20953c8c1002521e8b9ba](https://github.com/whitechi73/OpenShamrock/assets/107661829/eb869a22-2f55-48f6-9efd-f22e751fd4df)
![c4e683816b3baedfb63a1f43585768a3](https://github.com/whitechi73/OpenShamrock/assets/107661829/9743d850-c7d7-47b6-a9dc-0241a983a10d)

## 系统信息

- Shamrock 版本: Shamrock-v1.0.9.r375.a3171b3-all
- Android 版本: Android10
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: redmi7

**Comment by whitechi73** [comment]
卸载shamrock重新安装大概就能解决，或者更换一个版本

**Comment by Simplxss** [comment]
你安装语音模块了吗？
