### ISSUE TITLE
bug: 疑似不能接收戳一戳消息（安卓端群聊双击头像）

### ISSUE THREAD

**Issue by MWTJC** [whitechi73/OpenShamrock#264]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

1.0.8正式版时，之前一段时间（最后一次确认没问题是2月6日）是能接收戳一戳消息的，但是今天突然发现OpenShamrock戳一戳没反应，日志都没，遂更开发版（1.0.9.r381 actions/runs/8084491676）但不济事，这期间没主动更新过QQ（9.0.17.15190），相关测试日志如图
![image](https://github.com/whitechi73/OpenShamrock/assets/74529082/aa82e6ac-600f-44e5-87f5-bc1ba12c0dce)
![image](https://github.com/whitechi73/OpenShamrock/assets/74529082/0e46d626-65c1-4f24-af17-0e4b8190cfd6)

### 复现 Bug

安卓端在群聊中双击bot头像戳一戳

## 系统信息

- Shamrock 版本: 1.0.9.r381-all
- Android 版本: 12
- LSPosed 框架版本: Shizuku(13.5)+Lspatch(0.5.1(360))
- 设备的制造商和型号: mumu模拟器（win11）
- 设备的 CPU 架构: ARM64(mumu)

**Comment by whitechi73** [comment]
无法复现

**Comment by MWTJC** [comment]
> 无法复现

懂了，
佬是用的甚么环境？我想照着重装试下看行不行

**Comment by whitechi73** [comment]
真机LSPosed+Zygisk 9.0.17

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
