### ISSUE TITLE
feat: 账号切换接口

### ISSUE THREAD

**Issue by PA733** [whitechi73/OpenShamrock#27]
### 描述功能

对于只有一个真机，且无法使用 虚拟机/模拟器（新号会被封）的用户，希望能添加切换账号的功能。
可以在需要时，通过此接口切换到机器人账号并发送消息。

### 实现方法

在QQ主界面，长按头像会打开账号控制面板，在此可以快速切换已认证的账号。

**Comment by whitechi73** [comment]
https://whitechi73.github.io/OpenShamrock/api/shamrock.html#%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7

**Comment by PA733** [comment]
好耶，谢谢白池佬！
