### ISSUE TITLE
bug: 端点get_group_member_list调用异常

### ISSUE THREAD

**Issue by JUST-HK416D** [whitechi73/OpenShamrock#273]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

通过Http调用/get_group_member_list时返回异常，调用方法时参数类型错误？
![image](https://github.com/whitechi73/OpenShamrock/assets/90328461/a6674db8-343d-45bc-a526-8fd3979bb9b4)

### 复现 Bug

直接调用/get_group_member_list端点并代入有group_id的json

## 系统信息

- Shamrock 版本: Shamrock-v1.0.9.r374.0262648
- Android 版本: 9.0
- LSPosed 框架版本: LSPosed-v1.9.2-7024-zygisk
- 设备的制造商和型号: 雷电模拟器
- 设备的 CPU 架构: 雷电模拟器

**Comment by whitechi73** [comment]
#265
