### ISSUE TITLE
bug: 发送合并转发消息（send_forward_msg）会出现  创建临时会话失败

### ISSUE THREAD

**Issue by ryujou** [whitechi73/OpenShamrock#278]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
发送合并转发消息（send_forward_msg）会出现  创建临时会话失败
请清晰地描述此 Bug 的具体表现，并提供错误日志。
![image](https://github.com/whitechi73/OpenShamrock/assets/30500241/d0e736b1-5574-4aa7-bdff-66743b391b43)
![image](https://github.com/whitechi73/OpenShamrock/assets/30500241/60e821c5-bc0a-4c54-937a-ae348f21b1b0)

### 复现 Bug
        await bot.send_forward_msg(
            user_id=event.user_id if isinstance(event, PrivateMessageEvent) else 0,
            group_id=event.group_id if isinstance(event, GroupMessageEvent) else 0,
            messages=msgs,
        )
请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.9.r404.d92d1da]
- Android 版本: 
- LSPosed 框架版本: 
- 设备的制造商和型号: MuMu12
- 设备的 CPU 架构: X86-64

**Comment by whitechi73** [comment]
发送合并转发，不要同时携带`group_id`和`user_id`否则，将会被判定为群临时会话
