### ISSUE TITLE
QQ 于模拟器崩溃

### ISSUE THREAD

**Issue by PisLuanyao** [whitechi73/OpenShamrock#279]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

QQ 再次一打开就闪退

### 复现 Bug

模拟器QQ 把反检测加强打开

## 系统信息

- Shamrock 版本: r404
- Android 版本: 9
- LSPosed 框架版本: 最新
- 设备的制造商和型号: Nox v7-0-5-9
- 设备的 CPU 架构: x86_64

```
Generated by AppErrorsTracking 1.3(6)
[Package Name]: com.tencent.mobileqq
[Version Name]: 9.0.20
[Version Code]: 5844
[Target SDK]: 31
[Min SDK]: 23
[Error Type]: Native
Revision: '0'
ABI: 'x86_64'
pid: 4181, tid: 4213, name: NtStartup_pool_  >>> com.tencent.mobileqq <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'x86_insn_decode.c:450: void x86_insn_decode_opcode(x86_insn_reader_t *, x86_insn_decode_t *, x86_options_t *): assertion "0" failed'
    rax 0000000000000000  rbx 0000000000001075  rcx 00007f62155a8be8  rdx 0000000000000006
    r8  00007f621567ef00  r9  00007f621567ef00  r10 00007f621567ef00  r11 0000000000000246
    r12 0000000000000000  r13 00007f618a968fa8  r14 0000000000001055  r15 00007f6178195898
    rdi 0000000000001055  rsi 0000000000001075
    rbp 0000000000000200  rsp 00007f6178195888  rip 00007f62155a8be8
```

**Comment by ohuo133233** [comment]
在Mumu模拟器、逍遥模拟器......各种模拟器，其中对Shamrock兼容较好的是 Mumu模拟器 ，其它模拟器在测试情况下都出现高版本 QQ 闪退的问题。

**Comment by PisLuanyao** [comment]
> 在Mumu模拟器、逍遥模拟器......各种模拟器，其中对Shamrock兼容较好的是 Mumu模拟器 ，其它模拟器在测试情况下都出现高版本 QQ 闪退的问题。

这个是开启反检测增强之后才爆炸了, 不知道怎么回事 (我技术不行，望谅解

**Comment by PisLuanyao** [comment]
不知道怎么死的，我还Mumu也爆这个 (怀疑是我手气问题

**Comment by ohuo133233** [comment]
重新启动模拟器，先打开QQ登录，再重启模拟器执行下面步骤

**Comment by MoonofBridge24** [comment]
我也崩过，主要是不要乱开一些乱七八糟的开关，能用就行(我还苟在低版本没有检测

**Comment by PisLuanyao** [comment]
本次故障我个人判定为玄学问题，先关了
