### ISSUE TITLE
希望可以添加禁言状态的字段

### ISSUE THREAD

**Issue by kingyangcn** [whitechi73/OpenShamrock#293]
1、全员禁言或者机器人被禁言时，发送群消息返回结果不准确，似乎和QQ版本有关系，使用QQ8.9.83在禁言状态发群消息提示成功，使用QQ9.0.17提示超时次数过多
2、建议在获取群信息和群列表返回禁言状态，虽然可以通过禁言事件来保存禁言状态，但是掉线或者网络不稳的情况下就没办法同步禁言状态的准确性

**Comment by Simplxss** [comment]
第一个是因为原来shamrock采用异步发送无法获取发送结果，现在因为一些原因加上了重试机制导致返回值变化。
第二个的话你有取禁言列表的办法吗，据我所知只能直接拉取群成员列表才能获取。

**Comment by Simplxss** [comment]
补充：群管理员有一个办法直接获取群内禁言列表，不知道普通群员有没有权限调用
