### ISSUE TITLE
bug: 资源图片转发 转发卡住发不出

### ISSUE THREAD

**Issue by qpdbzzz** [whitechi73/OpenShamrock#296]
### 描述 Bug
有一回，转发失败，后面就一直转发不成功

### 复现 Bug
带有图片的转发会导致转发失败

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.0.9.r405.2ac0003
- Android 版本: 9
- qq版本: 9.0.17
- 设备的制造商和型号: oppo r11st
- 设备的 CPU 架构: 骁龙660

**Comment by qpdbzzz** [comment]
![Screenshot_2024-03-14-15-14-31-76_43335dd642141cbc02507d203ca6573f.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/45f88648-08f4-425b-ba7f-d3e88e484103)

![Screenshot_2024-03-14-15-14-40-17_43335dd642141cbc02507d203ca6573f.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/ae7a3711-df05-41b6-82d0-73ed03b57694)

![Screenshot_2024-03-14-15-14-44-31_43335dd642141cbc02507d203ca6573f.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/184b38f7-0ddb-4a80-8b5d-d918dbcaf53d)

![Screenshot_2024-03-14-15-14-52-47_43335dd642141cbc02507d203ca6573f.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/6161e1c3-c1eb-40cb-bc9e-420b0962ce93)

**Comment by ikechan8370** [comment]
试试最新版 1d035fa37861c545d317e206c4d45138433a0680

**Comment by qpdbzzz** [comment]
![Screenshot_2024-03-15-05-14-23-89_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/116e3e1d-8f22-4500-8c97-3731b0ac262b)

椰奶直接报错了

**Comment by qpdbzzz** [comment]
@ikechan8370 帮忙看一下是怎么引起的

**Comment by ikechan8370** [comment]
你发椰奶的报错 我也看不出来他是怎么用的

**Comment by qpdbzzz** [comment]
刚好同一天本体时雨改的白名单用户？
commoc被删了，导致的？
![IMG_20240316_041842.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/8d39b878-0fac-4bce-b4d1-0c404f4269ff)

![Screenshot_2024-03-16-04-13-52-45_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/4d7f3837-e426-4156-b15a-f642fbd4db85)

![IMG_20240316_041812.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/0055cd8f-572b-403f-9812-9bca03fe106d)

**Comment by qpdbzzz** [comment]
@ikechan8370

**Comment by qpdbzzz** [comment]
发现喵喵面板图没图片![Screenshot_2024-03-17-21-55-25-09_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/e12ad074-7145-48e1-b11f-3741a692ad97)

![Screenshot_2024-03-17-21-55-22-53_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/whitechi73/OpenShamrock/assets/145204697/8d691f6e-ddd0-445b-9eac-dae0bd6da9bf)

**Comment by Simplxss** [comment]
设置里资源上传群号随便改下
