### ISSUE TITLE
bug: 发送JSON消息发送不成功

### ISSUE THREAD

**Issue by thazjswe42700** [whitechi73/OpenShamrock#297]
### 描述 Bug
在进行发送的操作时，其他人看到的回复是：发送者版本过低，无法展示内容（电脑和手机都会是这种内容）
但是在机器人客户端查看，这个json卡片是存在的

### 复现 Bug

{
    app: "com.tencent.miniapp",
    desc: "",
    view: "notification",
    ver: "0.0.0.0",
    prompt: "顶部",
    appID: "",
    sourceName: "",
    actionData: "",
    actionData_A: "",
    sourceUrl: "",
    meta: {
      notification: {
        emphasis_keyword: "",
        data: [
          { title: "    1.", value: "选项1" },
          { title: "    2.", value: "选项2" },
        ],
        appInfo: {
          appName: "顶部",
          appType: 4,
          appid: 1108249016,
          iconUrl: "https://z3.ax1x.com/2021/08/12/f06XB8.png",
        },
        button: [{ action: "", name: "呀哈喽~" }],
      },
    },
    text: "",
    extraApps: [],
    sourceAd: "",
    extra: "",
  }

## 系统信息

- Shamrock 版本: 1.0.9.r411
- Android 版本: 12
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: HONOR Magic4 Pro

**Comment by Simplxss** [comment]
1. 你发的这玩意不是json格式的
2. 你json的token呢 你确定没token能发送吗
