### ISSUE TITLE
feat: 能不能获取到QQ天气的每日箴言。想获取到发送到群里哦

### ISSUE THREAD

**Issue by 1158229122** [whitechi73/OpenShamrock#306]
![IMG_1724](https://github.com/whitechi73/OpenShamrock/assets/45034189/6b40da91-dcbd-4f12-808f-187e9aea804c)

**Comment by Loli-Lain** [comment]
你手机没电啦

**Comment by 1158229122** [comment]
你能抓到这个qq的api吗

> 你手机没电啦

**Comment by Loli-Lain** [comment]
> 你能抓到这个qq的api吗
> 
> > 你手机没电啦

来自[@hanhan](https://github.com/hanhan258)
![c0c84e59fd1af20ebc576449bee3cd3a](https://github.com/whitechi73/OpenShamrock/assets/74231782/513e05b0-fbee-48ef-952b-1420d015e591)

![image](https://github.com/whitechi73/OpenShamrock/assets/74231782/44018758-f3a4-435e-89fa-1388096df84f)

**Comment by 1158229122** [comment]
> > 你能抓到这个qq的api吗
> > > 你手机没电啦
> 
> 来自[@hanhan](https://github.com/hanhan258) ![c0c84e59fd1af20ebc576449bee3cd3a](https://private-user-images.githubusercontent.com/74231782/314011223-513e05b0-fbee-48ef-952b-1420d015e591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDUzMDksIm5iZiI6MTcxMDkwNTAwOSwicGF0aCI6Ii83NDIzMTc4Mi8zMTQwMTEyMjMtNTEzZTA1YjAtZmJlZS00OGVmLTk1MmItMTQyMGQwMTVlNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNmE1NTM2MTJhNjQ3ZWYwNjFhNDFkZmE4YWNjMGY2OTcxMGZjZWY3Yzc5MzRmNDQ5YWJlMjAwYmM5NGE3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UNBRZtKE3goeb6XuRwhnTwbZDc6XW1unE9974lCZVU)
> 
> ![image](https://private-user-images.githubusercontent.com/74231782/314011020-44018758-f3a4-435e-89fa-1388096df84f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDUzMDksIm5iZiI6MTcxMDkwNTAwOSwicGF0aCI6Ii83NDIzMTc4Mi8zMTQwMTEwMjAtNDQwMTg3NTgtZjNhNC00MzVlLTg5ZmEtMTM4ODA5NmRmODRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZTJiNTU2ZGYwZmVhNGMyZjViZGM3OWFkNzVhMTEzODEwMDBiODgyMzcyZDlhMGJhMzdiODg3MWYyOWU1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wi3F3KUDjDCrqSif97FaIzmLDQqCOLdtMvbgr-h4hIY)

哦，我的好哥哥。你的appId与秘钥怎么来的哦。求教
