### ISSUE TITLE
bug: QQ V9.0.25.15760使用频繁闪退

### ISSUE THREAD

**Issue by 1143910315** [whitechi73/OpenShamrock#307]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

启动qq后，大约1-5分钟内就会闪退一次。
开启“显示调试日志”未能看到有关错误信息，未找到任何可用日志

## 系统信息

- Shamrock 版本: Shamrock-v1.0.9.r427.7782feb-all.zip、Shamrock-v1.0.8.r296.e68a1ff-all.zip
- Android 版本: 9.0.25.15760
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构: amd

**Comment by 1143910315** [comment]
[Crash.txt](https://github.com/whitechi73/OpenShamrock/files/14667412/Crash.txt)
补充logcat记录，可能为崩溃日志

**Comment by whitechi73** [comment]
该log不具备跟踪意义，请关闭反调用栈检测后再提交log
