### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lookmycat** [whitechi73/OpenShamrock#308]
### 描述 Bug

在mumu12中面具和LSP模块都安装成功并在LSP中激活shamrock
但是启动shamrock显示：未激活1.0.9.r427.7782feb-Xposed

## 系统信息

- Shamrock 版本: 开发版：Shamrock-v1.0.9.r427.7782feb-all
- Android 版本: 12
- LSPosed 框架版本: LSPosed-v1.9.2-7024-zygisk
- 设备的制造商和型号: MUMU12
- 设备的 CPU 架构:

**Comment by lookmycat** [comment]
解决了，原因是需要登录QQ，为什么教程里不写明啊

**Comment by callng** [comment]
> 解决了，原因是需要登录QQ，为什么教程里不写明啊

https://whitechi73.github.io/OpenShamrock/guide/getting-started.html#%E6%9C%89-xp-%E7%8E%AF%E5%A2%83 真的很😅
