### ISSUE TITLE
bug: 最新的开发版本出现频繁未激活框架

### ISSUE THREAD

**Issue by liaofulong** [whitechi73/OpenShamrock#31]
### Bug信息

在使用时我已激活模块并且勾选作用域，但是会出现频繁未激活框架过一段时间又显示激活的情况，正在对之前的版本进行测试，顺便希望加回之前的签名功能（因为某些不可描述原因可不予理会）谢谢

## 系统信息

- Shamrock 版本: 1.0.5-dev.80bb591
- Android 版本: 13
- 设备的制造商和型号: Redmi 12C
- 设备的 CPU 架构: Arm64-v8

**Comment by callng** [comment]
需要登录账号，在未登录成功前显示未激活。
