### ISSUE TITLE
Code: 临时消息参数和判断方法整体拿掉了？

### ISSUE THREAD

**Issue by tobycroft** [whitechi73/OpenShamrock#311]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

我想问下“allow-temp-session”这个我搜不到了，请问是干掉了吗？

这块我本来是这周打算加到Lab里面去做成动态开关的，因为我很早之前提了这个需求，说是全部发送然后让各个框架的开发者自主拦截

后来得到issue回复说只能用config来改，所以我一直用自编的allow-temp-session默认true的版本在跑

但是这块我一直很介意，所以我是想本周给在Lab的消息相关模块选项那边加一个选项，直接控制allow-temp-session

然后刚刚master搜一下发现allow-temp-session整体没了

### 提问

那这块现在就确定移除allow-temp-session配置，然后回报模式调整成“全部发送”然后在自己的bot框架中自主做拦截和处理了对吗？

@ikechan8370 @whitechi73

**Comment by Loli-Lain** [comment]
换分支瞅瞅

**Comment by Simplxss** [comment]
这开关本来就没啥用 现在重构顺便删了
