### ISSUE TITLE
bug: 使用PAD协议不生效

### ISSUE THREAD

**Issue by brokestar233** [whitechi73/OpenShamrock#313]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

设置内开启了使用PAD协议，启动时也**有Toast提示**使用PAD协议，但是并不是使用PAD协议登录，会把别的设备挤下线

启动时日志
![59c158ab1cfead0320bb3a5c6402886d](https://github.com/whitechi73/OpenShamrock/assets/161171586/7da3ddca-26ce-444a-a5ae-1b6a010ab376)

### 复现 Bug

启动QQ

## 系统信息

- Shamrock 版本: v1.1.0.r1.cdc664f
- Android 版本: 10.0
- LSPosed 框架版本: 1.9.2（7024）
- 设备的制造商和型号: vivo-vivo1806
- 设备的 CPU 架构: arm64

**Comment by whitechi73** [comment]
这个是因为qq现在检测是否是平板协议将代码移动到了native，没办法进行注入。
