### ISSUE TITLE
feat: 日志按日期保存

### ISSUE THREAD

**Issue by lindongbin** [whitechi73/OpenShamrock#315]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

日志按照日期保存，目前是从启动开始的日志保存在同一个文件中

.rw-rw----+ 10081 1078 312 B  Mon Feb 12 14:20:22 2024  com.tencent.mobileqq_2024-02-12_5.log
.rw-rw----+ 10081 1078  38 MB Thu Feb 29 15:35:02 2024  com.tencent.mobileqq_2024-02-12_6.log
.rw-rw----+ 10081 1078 1.9 MB Fri Mar  1 09:38:08 2024  com.tencent.mobileqq_2024-02-29_1.log
.rw-rw----+ 10081 1078 3.6 MB Sat Mar  2 08:56:01 2024  com.tencent.mobileqq_2024-03-01_1.log
.rw-rw----+ 10081 1078  16 MB Sat Mar 16 01:45:27 2024  com.tencent.mobileqq_2024-03-02_1.log
.rw-rw----+ 10081 1078 689 KB Mon Mar 18 17:08:32 2024  com.tencent.mobileqq_2024-03-16_1.log
.rw-rw----+ 10081 1078 671 B  Mon Mar 18 17:09:17 2024  com.tencent.mobileqq_2024-03-18_1.log
.rw-rw----+ 10081 1078 2.3 MB Tue Mar 26 11:39:33 2024  com.tencent.mobileqq_2024-03-18_2.log

### 实现方法

日志按照日期保存，第二天的日志新生成一个文件

**Comment by fuqiuluo** [comment]
https://github.com/whitechi73/OpenShamrock/commit/df02f9f872efb1caadb1f21db3e78e34848493c6
