### ISSUE TITLE
feat：能否增加一个延时启动bot连接的设置

### ISSUE THREAD

**Issue by aknyzsd** [whitechi73/OpenShamrock#316]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

由于shamrock和gocq运行原理不同，模拟器在重启后会接收之前没有接收的数据，bot会将信息同时处理并回复导致风控。
能否增加一个设置，在框架激活后留出几秒接收登录前的消息

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by fuqiuluo** [comment]
建议在bot端代码实现，判断消息时间和bot启动时间，做一部分过滤。
