### ISSUE TITLE
bug: 版本v1.0.8报错无常驻包处理器，每半小时断开一次然后又重连

### ISSUE THREAD

**Issue by okashi-ya** [whitechi73/OpenShamrock#320]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

模拟器启动后可以正常连接到bot，但是会有报错：无常驻包处理器，消息接收发送均正常，但是每半小时会断开一次然后重新连接。
![image](https://github.com/whitechi73/OpenShamrock/assets/49012015/802100f6-41f0-4452-83c4-cab207cd0a66)
![image](https://github.com/whitechi73/OpenShamrock/assets/49012015/c1ca82a2-e17d-4716-9490-2ee07319ff34)
![image](https://github.com/whitechi73/OpenShamrock/assets/49012015/53bacd10-914d-4208-8a0e-bcefaa71c99d)

### 复现 Bug

1.启动模拟器
2.连接bot

## 系统信息

- Shamrock 版本: 1.0.8
- Android 版本: 9
- LSPosed 框架版本: v1.9.2
- 设备的制造商和型号: 雷电模拟器v9.0.68
- 设备的 CPU 架构:

**Comment by okashi-ya** [comment]
在bot侧会打印出日志：
04-12 12:16:59 [WARNING] nonebot | OneBot V11 | WebSocket for BotXXX closed by peer
04-12 12:16:59 [INFO] websockets | connection closed

**Comment by fuqiuluo** [comment]
这个是因为QQ进程被杀死之后，又被以莫名其妙的方式复活了，但是这样复活的QQ进程，没办法执行Shamrock的初始化流程。
