### ISSUE TITLE
bug: 软件：v1.1.0  QQ版本：9.0.60 进入软件时只有RPC  服务端口设置，如何连接之前的websocket接口？

### ISSUE THREAD

**Issue by yanXiaoi** [whitechi73/OpenShamrock#326]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
### 描述 Bug

进入软件时只有RPC  服务端口设置，如何连接之前的websocket接口？
![image](https://github.com/whitechi73/OpenShamrock/assets/120445129/11f4f867-ac72-4026-81d3-28531b2b40dc)

### 复现 Bug

安装对应版本后打开

## 系统信息

- Shamrock 版本: 1.1.0
- Android 版本: 12
- LSPosed 框架版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by fuqiuluo** [comment]
自行下载https://github.com/whitechi73/OpenShamrock/actions?query=branch%3Av1.0.9
旧版本的CI构建

**Comment by yanXiaoi** [comment]
好的，就1.1.0版本不支持是吧，谢谢
