### ISSUE TITLE
重大bug: 获取群成员接口报错get_group_member_list

### ISSUE THREAD

**Issue by Wendi056** [whitechi73/OpenShamrock#329]
{
  "status": "failed",
  "retcode": 20002,
  "data": {
    "url": "/get_group_member_list?group_id=711841924",
    "error": "No interface method getAllTroopMembers(Ljava/lang/String;)Ljava/util/List; in class Lcom/tencent/mobileqq/troop/api/ITroopMemberInfoService; or its super classes (declaration of 'com.tencent.mobileqq.troop.api.ITroopMemberInfoService' appears in /data/app/com.tencent.mobileqq-eXeSDYnLATRV4N8twSxUxA==/base.apk!classes3.dex)"
  }
}

**Comment by fuqiuluo** [comment]
QQ版本说一下？大于9.0.20确实会出现这个问题，因为新版本很久没维护了。

**Comment by Wendi056** [comment]
哦，那我降低版本吧，我是：9.0.65

**Comment by ikechan8370** [comment]
试下1.0.9的最新构建

**Comment by fuqiuluo** [comment]
v1.1.0版本修复该问题，等待 @ikechan8370 在onebot分支修复
