### ISSUE TITLE
bug: /get_group_root_files失效了。看其他人的Issue好像和群文件相关的API不行了

### ISSUE THREAD

**Issue by sd3970566** [whitechi73/OpenShamrock#330]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
 /get_group_root_files失效返回值为空
请清晰地描述此 Bug 的具体表现，并提供错误日志。
 /get_group_root_files失效返回值为空
### 复现 Bug
 /get_group_root_files失效返回值为空
请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。
 /get_group_root_files失效返回值为空
## 系统信息

- Shamrock 版本: 1.09
- Android 版本: 9
- LSPosed 框架版本: 
- 设备的制造商和型号: vivo iqooneo3
- 设备的 CPU 架构: arm64

**Comment by fuqiuluo** [comment]
额，给一下QQ版本

**Comment by sd3970566** [comment]
QQ版本V9.0.60.17095

**Comment by fuqiuluo** [comment]
> QQ版本V9.0.60.17095

先挂着吧，有时间看看有没有人修？ @callng

**Comment by callng** [comment]
> > QQ版本V9.0.60.17095
> 
> 先挂着吧，有时间看看有没有人修？ @callng

jesus!，饶过我吧 哈哈哈

**Comment by sd3970566** [comment]
可否帮忙也检查一下。
/upload_group_file
报错 ：{"status":"failed","retcode":20002,"data":{},"message":"上传文件失败","echo":""}

**Comment by sd3970566** [comment]
由于/get_group_root_files失败。    所以/delete_group_file我无法进行测试（因为先要获取，才有参数测试。）

**Comment by fuqiuluo** [comment]
v1.1.0版本修复该问题，等待 @ikechan8370 在onebot分支修复
