### ISSUE TITLE
bug: 群成员发起的非好友临时会话消息，有接口回复他么？

### ISSUE THREAD

**Issue by Wendi056** [whitechi73/OpenShamrock#331]
![1](https://github.com/whitechi73/OpenShamrock/assets/20696395/dfd6bc64-5c51-4784-b856-8ad57ad43d45)

**Comment by fuqiuluo** [comment]
主动发起临时聊天就是：直接调用send_private_msg接口，携带一个群号
如果是对方发过来的，直接send_private_msg就好了

**Comment by Wendi056** [comment]
群里发起来的临时会话消息，管理员好像接收不到？没开发这个接口么？

**Comment by fuqiuluo** [comment]
#332
