### ISSUE TITLE
bug: 1.09版get_group_member_info失效

### ISSUE THREAD

**Issue by cjxzdzh** [whitechi73/OpenShamrock#337]
### 描述 Bug

get_group_member_info失效

### 复现 Bug

调用这个端点会超时。

## 系统信息

- Shamrock 版本: 1.0.9
- Android 版本: 9.0.71.17665
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: 雷电模拟器 64位 9.0
- 设备的 CPU 架构: x64

**Comment by SilianZ** [comment]
@ikechan8370

**Comment by ikechan8370** [comment]
> @ikechan8370 

最近一周没有时间，看下周有没有空吧
