### ISSUE TITLE
bug: get_group_member_list缺少role字段

### ISSUE THREAD

**Issue by lindongbin** [whitechi73/OpenShamrock#345]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

get_group_member_list不能获取role身份信息

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。
get_group_member_list没有role字段

## 系统信息

- Shamrock 版本: 
Shamrock-v1.1.1.r1.40d2911
- Android 版本: 12
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: mumu模拟器
- 设备的 CPU 架构: x86/64

**Comment by fuqiuluo** [comment]
kritor版本吗？kritor标准那边好像不支持从get_group_member_list获取role？

**Comment by lindongbin** [comment]
> kritor版本吗？kritor标准那边好像不支持从get_group_member_list获取role？

对，好的
