### ISSUE TITLE
bug: 获取频道列表错误

### ISSUE THREAD

**Issue by Etcwind-dfl** [whitechi73/OpenShamrock#346]
### 描述 Bug

{
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/get_guild_list",
        "error": "No interface method getGuildService()Lcom/tencent/qqnt/kernel/nativeinterface/IKernelGuildService; in class Lcom/tencent/qqnt/kernel/nativeinterface/IQQNTWrapperSession; or its super classes (declaration of 'com.tencent.qqnt.kernel.nativeinterface.IQQNTWrapperSession' appears in base.apk!classes2.dex)"
    }
}

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本:Shamrock-v1.1.1.onebot.r440.7eaa470-arm64.apk
- QQ 版本: 7.0.71 7.0.75
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: 小米10
- 设备的 CPU 架构: arm64

**Comment by fuqiuluo** [comment]
如果还有问题另开一个issue
