### ISSUE TITLE
bug: appid不匹配

### ISSUE THREAD

**Issue by MDeath** [whitechi73/OpenShamrock#351]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgkxODM3NDQ1MjkSFIYFEX8xp_nUx0xzlW0VSEiqV7HYGLyhAiD_CiiJl_f1ncqHA1CAvaMB&spec=0&rkey=CAMSKMa3OFokB_TlUAxSfplrEci1raV1SyXioLmOZVME6yRo-SuijvdAXys
{
    "retcode": -5503023,
    "retmsg": "appid is not match",
    "retryflag": 1
}

### 复现 Bug

![image](https://github.com/user-attachments/assets/c48967f2-978f-4680-9ead-fb60dd926856)

## 系统信息

- Shamrock 版本:[v1.1.1.onebot.r444.609e87d
- QQ 版本: 9.0.71.17655
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: oppo A2m
- 设备的 CPU 架构: 天机6020

**Comment by siuze** [comment]
可以有临时手动修改appid，让链接变正确，从而获取图片的方法吗？还是说只能等代码修复？

**Comment by MDeath** [comment]
https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml
