### ISSUE TITLE
bug: 收到旧版账号发送的图片，URL域名变更，查看不了

### ISSUE THREAD

**Issue by MDeath** [whitechi73/OpenShamrock#356]
### 描述 Bug

收到旧版（9.0以前的版本）图片URL地址变了：
[以前](https://gchat.qpic.cn/offpic_new/1064393873//1064393873-2504994071-533F973767CA91952D3FC962FFE6ECFA/0?term=2&is_origin=1&rkey=CAESKBkcro_MGujoJc5_GW1mPrP_9B5RtRNIuRzA8dY4UH8H83KMqg4tWv4)
[现在](https://multimedia.nt.qq.com.cn/offpic_new/1064393873//1064393873-2504994071-533F973767CA91952D3FC962FFE6ECFA/0?term=2&is_origin=1&rkey=CAESKBkcro_MGujoJc5_GW1mPrP_9B5RtRNIuRzA8dY4UH8H83KMqg4tWv4)

### 复现 Bug

QQ[v8.9.83](https://www.wandoujia.com/apps/566489/history_v4680)发送图片给bot
目前还可以直接用旧版域名
c2cpicdw.qpic.cn
gchat.qpic.cn
替换新版域名
multimedia.nt.qq.com.cn

## 系统信息

- Shamrock 版本:1.1.1.onebot.r446.976526a
- QQ 版本: v8.9.83
- Android 版本: 13
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: oppo A2m
- 设备的 CPU 架构: 天机6020

**Comment by luyanci** [comment]
https://github.com/whitechi73/OpenShamrock/blob/v1.0.9/README.md

> 仅支持QQ9.0.70以上的版本，低版本问题将不再修复与处理。
