### ISSUE TITLE
feat: 日志保存

### ISSUE THREAD

**Issue by A2Sumie** [whitechi73/OpenShamrock#36]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

希望可以和go-cqhttp一样把日志输出到log文件
经常性遇到bot崩溃后shamrock打开却没有之前日志的情况（虽然我怀疑是设备自己重启了）

**Comment by callng** [comment]
shamrock会保存日志的！输出日志 使用`/log`接口

**Comment by callng** [comment]
> shamrock会保存日志的！输出日志 使用`/log`接口

https://whitechi73.github.io/OpenShamrock/api/shamrock.html#%E8%8E%B7%E5%8F%96shamrock%E6%97%A5%E5%BF%97
