### ISSUE TITLE
feat: 能否支持用户回复消息消息带有引用消息的ID

### ISSUE THREAD

**Issue by foxdad** [whitechi73/OpenShamrock#4]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

现在的sk每次在群聊中引用消息回复，返回的是本次消息的id而不能查询到引用消息的消息ID，
能实现这个功能就好了，

这个地方与gocq稍微有点差别

撤回消息也是，使用消息撤回，会提示，消息message_id 没有映射

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by whitechi73** [comment]
举个例子

**Comment by foxdad** [comment]
> 举个例子

现在sk的实现是
<img width="241" alt="image" src="https://github.com/whitechi73/OpenShamrock/assets/48538835/99229f21-f42b-473e-9c96-605099d64252">
<img width="241" alt="image" src="https://github.com/whitechi73/OpenShamrock/assets/48538835/d6c7f53a-5e5c-4eda-af0d-1ecad2214587">
<img width="241" alt="image" src="https://github.com/whitechi73/OpenShamrock/assets/48538835/2b5dd383-f801-416d-a3ea-7c6e11fbdbfc">

我对同一个消息的引用，他返回的是 我这里以cq码举例
[CQ:reply,id=1234]你好
[CQ:reply,id=1235]你好
[CQ:reply,id=1236]你好

在gocq中的实现，这个id是返回的是 引用用户的消息ID

**Comment by foxdad** [comment]
而不是本次发送的消息ID，大佬可以测试一下，每次都是新的消息ID，不是同一个消息ID，这样就不能定位到用户本次回复的是那条消息

**Comment by foxdad** [comment]
> 举个例子

因为，每次都是新的id，就跟发群消息的时候，是发送的时候，返回了，消息id，都是这个回复里面带的消息id，却是新的消息ID，作用就不太大了，还麻烦作者大大，看这个有没有解决办法了

**Comment by whitechi73** [comment]
テスト（测试）: 

- 发送消息ID为0的消息A
- 发送回复消息A的消息B（reply元素中的id指向消息A）
- 发送回复消息A的消息C（reply元素中的id指向消息A）

无法复现你的问题。

**Comment by foxdad** [comment]
> テスト（测试）:
> 
> * 发送消息ID为0的消息A
> * 发送回复消息A的消息B（reply元素中的id指向消息A）
> * 发送回复消息A的消息C（reply元素中的id指向消息A）
> 
> 无法复现你的问题。

我就刚才测试的，远程可能模糊了点

<img width="416" alt="image" src="https://github.com/whitechi73/OpenShamrock/assets/48538835/7871eb4b-c1b4-4a79-adad-b3c95dbc1bb2">

返回了消息ID:
 {"status":"ok","retcode":0,"data":{"message_id":149643738,"time":1.6987310683830001E9},"echo":""}

<img width="400" alt="image" src="https://github.com/whitechi73/OpenShamrock/assets/48538835/15691538-a34d-49d9-a20f-b83e741407aa">


与返回的消息id对应不上
![9b3afb10874cc1e760d09fffc87c77e0](https://github.com/whitechi73/OpenShamrock/assets/48538835/f8502ca2-d798-4187-8ed8-096404c238cc)

sk的版本是1.0.5-dev的版本

**Comment by fuqiuluo** [comment]
发送消息然后其返回的MessageId不可靠是吗？

**Comment by foxdad** [comment]
> 发送消息然后其返回的MessageId不可靠是吗？

是的，会对应不上，在撤回消息的时候也会有问题

sk的日志里面会出现，没有映射的警告

**Comment by fuqiuluo** [comment]
> > 发送消息然后其返回的MessageId不可靠是吗？
> 
> 是的，会对应不上，在撤回消息的时候也会有问题
> 
> sk的日志里面会出现，没有映射的警告

看了一下，QQ内部设计有问题，Bot发送了消息A(QQ内部接口说这条消息的seq是108)，然而实际上这个seq=109，seq不可信导致映射关系有问题。

**Comment by foxdad** [comment]
> > > 发送消息然后其返回的MessageId不可靠是吗？
> > 
> > 
> > 是的，会对应不上，在撤回消息的时候也会有问题
> > sk的日志里面会出现，没有映射的警告
> 
> 看了一下，QQ内部设计有问题，Bot发送了消息A(QQ内部接口说这条消息的seq是108)，然而实际上这个seq=109，seq不可信导致映射关系有问题。

因为这个问题是qq内的问题，回复消息id问题还能解决吗，这个qq层面sk因为干涉不到了吧，感觉这个问题点解决有点悬

**Comment by fuqiuluo** [comment]
> > > > 发送消息然后其返回的MessageId不可靠是吗？
> > > 
> > > 
> > > 是的，会对应不上，在撤回消息的时候也会有问题
> > > sk的日志里面会出现，没有映射的警告
> > 
> > 看了一下，QQ内部设计有问题，Bot发送了消息A(QQ内部接口说这条消息的seq是108)，然而实际上这个seq=109，seq不可信导致映射关系有问题。
> 
> 因为这个问题是qq内的问题，回复消息id问题还能解决吗，这个qq层面sk因为干涉不到了吧，感觉这个问题点解决有点悬

应该可以解决，白池还没有下课 下课了我去找她。

**Comment by foxdad** [comment]
> > > > > 发送消息然后其返回的MessageId不可靠是吗？
> > > > 
> > > > 
> > > > 是的，会对应不上，在撤回消息的时候也会有问题
> > > > sk的日志里面会出现，没有映射的警告
> > > 
> > > 
> > > 看了一下，QQ内部设计有问题，Bot发送了消息A(QQ内部接口说这条消息的seq是108)，然而实际上这个seq=109，seq不可信导致映射关系有问题。
> > 
> > 
> > 因为这个问题是qq内的问题，回复消息id问题还能解决吗，这个qq层面sk因为干涉不到了吧，感觉这个问题点解决有点悬
> 
> 应该可以解决，白池还没有下课 下课了我去找她。

洛洛 厉害，等待洛洛解决

**Comment by foxdad** [comment]
> > > > > 发送消息然后其返回的MessageId不可靠是吗？
> > > > 
> > > > 
> > > > 是的，会对应不上，在撤回消息的时候也会有问题
> > > > sk的日志里面会出现，没有映射的警告
> > > 
> > > 
> > > 看了一下，QQ内部设计有问题，Bot发送了消息A(QQ内部接口说这条消息的seq是108)，然而实际上这个seq=109，seq不可信导致映射关系有问题。
> > 
> > 
> > 因为这个问题是qq内的问题，回复消息id问题还能解决吗，这个qq层面sk因为干涉不到了吧，感觉这个问题点解决有点悬
> 
> 应该可以解决，白池还没有下课 下课了我去找她。

洛洛，辛苦了，这个解决了是不是也是会关闭这个issue

**Comment by fuqiuluo** [comment]
测试结果如下：
来自接口**onAddSendMsg**所提供的msgSeq并不可靠，其数据无法用于构建映射关系。

需要**onAddSendMsg**触发后，使用其**msgId**调用接口**getMsgByMsgId**获取正确的消息，其中如果消息发送返回包未成功_返回/获取/解析_，仍旧无法获取正确的**msgSeq**，需要实现一个字段保存某个确切**msgId**的消息是否已经成功发送了。

**Comment by Simplxss** [comment]
> 测试结果如下： 来自接口**onAddSendMsg**所提供的msgSeq并不可靠，其数据无法用于构建映射关系。
> 
> 需要**onAddSendMsg**触发后，使用其**msgId**调用接口**getMsgByMsgId**获取正确的消息，其中如果消息发送返回包未成功_返回/获取/解析_，仍旧无法获取正确的**msgSeq**，需要实现一个字段保存某个确切**msgId**的消息是否已经成功发送了。

我之前就提到过这个问题的 发消息返回的msgSeq似乎总是比实际少1 msgId和回复时给的不一致 没什么特别好的办法解决 回头看看其他协议的实现吧

**Comment by foxdad** [comment]
> 测试结果如下： 来自接口**onAddSendMsg**所提供的msgSeq并不可靠，其数据无法用于构建映射关系。
> 
> 需要**onAddSendMsg**触发后，使用其**msgId**调用接口**getMsgByMsgId**获取正确的消息，其中如果消息发送返回包未成功_返回/获取/解析_，仍旧无法获取正确的**msgSeq**，需要实现一个字段保存某个确切**msgId**的消息是否已经成功发送了。

这协议不讲武德

**Comment by CelestialFighter** [comment]
一样遇到该问题，发送消息后响应的message_id和实际的id不一致
