### ISSUE TITLE
bug: 设置群组专属头衔接口报错

### ISSUE THREAD

**Issue by SlightDust** [whitechi73/OpenShamrock#41]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

set_group_special_title接口报错Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference

### 复现 Bug

http get请求http://ip:port/set_group_special_title?group_id=xxxxxx&user_id=xxxxxx&special_title=IMSB&access_token=xxxxxx  
响应如下：
```json
{
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/set_group_special_title?group_id=xxxxxx&user_id=xxxxxx&special_title=IMSB&access_token=xxxxxx",
        "error": "Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference"
    }
}
```

## 系统信息

- Shamrock 版本: 6b4f763
- Android 版本: 12
- 设备的制造商和型号: Redmi K30 5G
- 设备的 CPU 架构: ARM64

**Comment by lindongbin** [comment]
版本 19e3846 没有修复，响应和上面一样？

**Comment by callng** [comment]
> 版本 [19e3846](https://github.com/whitechi73/OpenShamrock/commit/19e3846e40c8aced978fa5bf661a7eafd570857b) 没有修复，响应和上面一样？

版本

**Comment by callng** [comment]
我说是QQ版本 你们反馈问题都不写的吗 我测试后都没问题🕵️

**Comment by lindongbin** [comment]
> 我说是QQ版本 你们反馈问题都不写的吗 我测试后都没问题🕵️

哦哦不好意思，刚部署的，QQ是8.9.88.13035，官网下载的

**Comment by callng** [comment]
![test](https://github.com/whitechi73/OpenShamrock/assets/64207250/f92efc2b-947e-4413-b298-1fcadda644e4)

**Comment by callng** [comment]
> ![test](https://user-images.githubusercontent.com/64207250/282455814-f92efc2b-947e-4413-b298-1fcadda644e4.png)

版本 8.9.88.13035

**Comment by lindongbin** [comment]
> ![test](https://user-images.githubusercontent.com/64207250/282455814-f92efc2b-947e-4413-b298-1fcadda644e4.png)

可以了，谢谢，我在一个小群测试的，不生效，另外一个群有效

**Comment by callng** [comment]
> 可以了，谢谢，我在一个小群测试的，不生效，另外一个群有效

你最好是说的报错。😠
