### ISSUE TITLE
feat: 请求支持 接收和处理加群请求／邀请

### ISSUE THREAD

**Issue by fanfumeiyousuzi** [whitechi73/OpenShamrock#42]
请求支持 接收和处理加群请求／邀请

**Comment by sd3970566** [comment]
希望早点适配群公告的发送···

**Comment by ikechan8370** [comment]
处理请求好了，公告另外发issue吧

**Comment by fuqiuluo** [comment]
> 处理请求好了，公告另外发issue吧

更新一下文档可否？

**Comment by Zyy955** [comment]
> > 处理请求好了，公告另外发issue吧
> 
> 更新一下文档可否？

懒死你

**Comment by ikechan8370** [comment]
> > 处理请求好了，公告另外发issue吧
> 
> 更新一下文档可否？

快速处理那个没看懂。那是shamrock要做的吗？
