### ISSUE TITLE
feat: 接口功能请求 代理执行 Web API 请求

### ISSUE THREAD

**Issue by Stapxs** [whitechi73/OpenShamrock#44]
### 描述功能
QQ 有一些 [Web API](https://github.com/takayama-lily/oicq/blob/main/web-api.md) 可以使用，它需要 uin、bkn（有些需要域名对应的 cookie），不知道在安卓端是否可以实现代为请求 API 返回对应的返回内容的功能。

像是：
~~~js
{
    'http_proxy',
    {
        'url': 'https://find.qq.com/proxy/domain/cgi.find.qq.com/qqfind/find_v11?backver=2',
        'method': 'post',
        'data': '....keyword={uin}&nf=0&of=0&ldw={bkn}'
    },
    'getMoreLoginInfo'
}
~~~

**Comment by ikechan8370** [comment]
可以试试 `get_csrf_token`和`get_cookies` 这两个接口？

**Comment by Stapxs** [comment]
> 可以试试 `get_csrf_token`和`get_cookies` 这两个接口？

嘛，道理是这样（
只是我项目特殊，Web 前端请求会有跨域问题而且把这些敏感信息返回给前端也不安全 emmm 有空我自己研究下实现罢了

**Comment by callng** [comment]
hhh，实际上这种在内部已经“实现”了。

**Comment by callng** [comment]
你按照源代码 改改就成了自定义了（bushi

**Comment by Stapxs** [comment]
> 你按照源代码 改改就成了自定义了（bushi

好好好（x
