### ISSUE TITLE
bug: 群组专属头衔接口问题

### ISSUE THREAD

**Issue by SlightDust** [whitechi73/OpenShamrock#47]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

在#41 中我说`set_group_special_title`接口返回`Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference`错误，目前我用最新版本试，给**未设置昵称**的群成员设置头衔还是有这个问题。  

给他设置头衔会报错
<img src=https://github.com/whitechi73/OpenShamrock/assets/53001305/b6367d1a-d888-4810-a18a-4717c683fc52 height=200px>

给他设置头衔是正常的
<img src=https://github.com/whitechi73/OpenShamrock/assets/53001305/d5b6bb73-096d-4c54-9498-e12c2ebc1c52 height=200px>
（数据来自get_group_member_info接口）

### 复现 Bug

set_group_special_title接口，user_id为某一个未设置过群昵称的群成员。

## 系统信息

- Shamrock 版本: 93cb6fc
- Android 版本: 12
- 设备的制造商和型号: Redmi K30 5G
- 设备的 CPU 架构: ARM64

**Comment by lindongbin** [comment]
#46 同样的问题

**Comment by lindongbin** [comment]
设置群昵称后能设置头衔了，群昵称清空后又不能设置了

**Comment by callng** [comment]
#46

**Comment by ikechan8370** [comment]
#49
