### ISSUE TITLE
bug: 撤回群聊消息的事件无法触发

### ISSUE THREAD

**Issue by zzzzRuby** [whitechi73/OpenShamrock#48]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

在QQ群里面撤回消息的时候，没有上报群聊消息撤回事件，同时日志里面出现异常
![A7A9A08370FC638D871523F66732924A](https://github.com/whitechi73/OpenShamrock/assets/16921327/3671ba21-1cc1-4626-84d1-4f49da89e725)

### 复现 Bug

撤回群聊消息就会触发

## 系统信息

- Shamrock 版本: 1.0.5-dev.19e3846 - Xposed
- Android 版本: 11
- 设备的制造商和型号: 联想YOGA Pad Pro
- 设备的 CPU 架构: arm64

**Comment by ikechan8370** [comment]
类似地，群成员变动、设置管理员等事件目前都不能正常获取。

**Comment by whitechi73** [comment]
> 类似地，群成员变动、设置管理员等事件目前都不能正常获取。

现在可以正常推送了吗？
