### ISSUE TITLE
bug: 无法对QQ隐藏Shamrock

### ISSUE THREAD

**Issue by kuaile10080** [whitechi73/OpenShamrock#5]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

文档-快速开始-部署： 禁止对 QQ 客户端 隐藏 Shamrock，这将导致无法运行。
文档-常见问题-反检测： 使用隐藏应用列表对QQ隐藏Shamrock，否则您可能遭到封禁。

### 复现 Bug

使用隐藏应用列表对QQ隐藏Shamrock后，QQ无限崩溃，无法打开。

## 系统信息

- Shamrock 版本: 
    [Shamrock-v1.0.5-dev.184064d-all](https://github.com/whitechi73/OpenShamrock/suites/17768562285/artifacts/1017952603)
    [Shamrock-v1.0.5-dev.184064d-arm64](https://github.com/whitechi73/OpenShamrock/suites/17768562285/artifacts/1017952604)
- Android 版本: Android 9
- 设备的制造商和型号: LG G7 ThinQ (LM-G710ULM)
- 设备的 CPU 架构: arm64-v8a, armeabi-v7a, armeabi

**Comment by fuqiuluo** [comment]
我会联系白池改一下反检测策略。
