### ISSUE TITLE
bug: 点赞不生效

### ISSUE THREAD

**Issue by ikechan8370** [whitechi73/OpenShamrock#51]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

执行send_like时，正常返回成功：
```
{
    "status": "ok",
    "retcode": 0,
    "data": {},
    "message": "成功",
    "echo": ""
}
```
但是实际没有点赞。好友或陌生人都一样。

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by super1207** [comment]
https://github.com/whitechi73/OpenShamrock/pull/50/commits/e6e03ee3281a413780118156d6639d4c43fcd8d0

应该已经在这个pr中修复了

**Comment by ikechan8370** [comment]
确实修好了
