### ISSUE TITLE
feat: 定时杀死（重启）QQ进程

### ISSUE THREAD

**Issue by A2Sumie** [whitechi73/OpenShamrock#53]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock. O
- 确保您的功能请求尚未在 Issues 列表中提出. O
- 确保您的功能请求是与 Shamrock 相关的，且可以实现. O

### 描述功能
指定周期内自动杀掉QQ进程，再借由QQ保活功能再拉起
我自己的环境上遇到开机几小时后bot失去响应的问题，前端后端的日志都没有任何错误，消息能收，甚至Websocket连接能新建立，但就是没响应，杀掉QQ重启就能解决。
虽然也有外部方法能实现，不知道有无可能加入这个功能。

**Comment by callng** [comment]
为什么要杀死QQ进程？

**Comment by whitechi73** [comment]
可以借住Termux循环执行脚本实习这个功能。
