### ISSUE TITLE
feat: 发送消息前判断账号是否存在此好友/群聊，不存在则取消发送并返回错误

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#54]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

发送消息前判断账号是否存在此好友/群聊，不存在则取消发送并返回错误

**Comment by whitechi73** [comment]
很久以前Shamrock拥有该功能，由于QQ缓存缘故，可能导致新入群的群没有办法发送消息。
