### ISSUE TITLE
feat: 有一个已有功能的加强请求

### ISSUE THREAD

**Issue by tobycroft** [whitechi73/OpenShamrock#56]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

- 现有打开临时消息的方法太繁琐了，因为主目录深度的问题，当然如果只是麻烦，是可以解决的。
- 如果使用“虚拟空间”的情况下，目前大部分手机系统，Google的Pixel，HAVOC，MIUI等，再使用虚拟空间的情况下，虚拟空间的目录授权器会出现授权故障的情况，导致无法进入主目录，这就导致完全无法配置的情况出现了
- 如果默认是开启状态，因为HTTP是有一个临时消息指示器的，所以可以再次拦截无需考虑可能因此带来的风险
- 因为这是Android系统本身授权的问题，所以暂时没办法解决，只能反馈到Issue了，目前我用的系统是Havoc的Android14，虚拟空间只能添加普通APP，系统APP是没办法添加到虚拟空间的，这也导致我无法复制一个目录授权器到虚拟空间来bypass这个问题

### 实现方法

- 能否将临时消息对话功能的开关做到框架控制面板里面呢？
- 如果是因为allow-temp-session初始化为false的问题，那能否把allow-temp-seesion改成disable-temp-session呢？这样默认false的情况下也不会耽误使用

**Comment by whitechi73** [comment]
shamrock提供了`/shell`接口（仅POST Json）。

**Comment by tobycroft** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/24893075/5c26abd4-de1c-4850-914e-79d2830638cd)
@whitechi73 是叫shell吗？
