### ISSUE TITLE
feat: 增加访问外部文件功能

### ISSUE THREAD

**Issue by Pyrokine** [whitechi73/OpenShamrock#57]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

Shamrock版本：Shamrock-v1.0.5-dev.4713310-all
模拟器版本：夜神模拟器安卓9
Magisk版本：24.1（24100）
LSPosed版本：1.9.2（7024）- Zygisk
QQ版本：8.9.88

### 描述功能

没有权限访问 /sdcard/Pictures 下的文件，手动复制到 /sdcard/Android/data/com.tencent.mobileqq/Tencent/Shamrock 下可以访问，不知道是不是bug，或能否新增访问外部文件的功能
![1](https://github.com/whitechi73/OpenShamrock/assets/25692152/9a3e5e36-29d4-4055-b666-22c85978a7f3)

请清晰地描述您想要的功能，并提供相关的信息。

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by whitechi73** [comment]
使用Shamrock提供是`/download_file` | `/upload_file`即可。

**Comment by PA733** [comment]
有赋予QQ访问内部存储的权限吗？

**Comment by Pyrokine** [comment]
> 使用Shamrock提供的`/download_file` | `/upload_file`即可。

`/upload_file`端点访问结果为404，以及，想问下文档中以`file`形式上传是什么意思，上传后发送文件依旧需要使用完整路径吗

**Comment by Pyrokine** [comment]
> 有赋予QQ访问内部存储的权限吗？

赋予后可以了，不过只能发送图片，发送视频`request`就一直卡着直到超时，shamrock日志也没有输出

**Comment by PA733** [comment]
> > 使用Shamrock提供的`/download_file` | `/upload_file`即可。
> 
> `/upload_file`端点访问结果为404，以及，想问下文档中以`file`形式上传是什么意思，上传后发送文件依旧需要使用完整路径吗

在Apifox里，你可以这样上传：
![image](https://github.com/whitechi73/OpenShamrock/assets/67588574/84dbe009-60f0-4fae-92ce-d8a2a6c764ca)

**Comment by Pyrokine** [comment]
> > > 使用Shamrock提供的`/download_file` | `/upload_file`即可。
> > 
> > 
> > `/upload_file`端点访问结果为404，以及，想问下文档中以`file`形式上传是什么意思，上传后发送文件依旧需要使用完整路径吗
> 
> 在Apifox里，你可以这样上传： ![image](https://user-images.githubusercontent.com/67588574/284044004-84dbe009-60f0-4fae-92ce-d8a2a6c764ca.png)

请求结果为404
![image](https://github.com/whitechi73/OpenShamrock/assets/25692152/fda8ae3e-e429-40a4-9a81-072fa620797d)
