### ISSUE TITLE
bug: 无法在对QQ隐藏Shamrock之后激活框架

### ISSUE THREAD

**Issue by luanyaolingwu** [whitechi73/OpenShamrock#58]
### 描述 Bug

暂无日志

### 复现 Bug

`正常情况`: 不进行任何隐藏时，Shamrock中正确显示框架激活
`使用HMA`: 当使用隐藏应用列表对QQ隐藏Shamrock时，QQ可以正常打开，但Shamrock提示未激活 (此时，同时处于被隐藏状态的QA正常工作)

## 系统信息

- Shamrock 版本: 最新构建
- Android 版本: 9.0
- 设备的制造商和型号: NoxAndroidEmu v7.0.5.8
- 设备的 CPU 架构: x86_64

**Comment by DuckBurnIncense** [comment]
文档中有提到不能对 QQ 客户端隐藏 Shamrock

https://github.com/whitechi73/OpenShamrock/blob/d43b53f7ccd07d35f3d39aa00b97265f56e61803/docs/guide/getting-started.md?plain=1#L32

**Comment by DuckBurnIncense** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/87637270/32305f68-007d-41e8-8eb1-98fb2863b9d1)
