### ISSUE TITLE
feat: 能否支持双开qq或者tim

### ISSUE THREAD

**Issue by Asgore-Dreemur** [whitechi73/OpenShamrock#59]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

我有两个qq账号，我需要一个正常使用不挂bot，另一个通过OpenShamrock实现bot
我尝试使用qq+tim，发现Openshamrock不支持tim
我尝试使用爱玩机工具箱中的应用双开，创建了一个工作模式的分区，并加入了OpenShamrock与qq在该分区
在lsp中启用了模块并勾选了qq，但是没有勾选系统框架
LSPosed激活后没有什么问题，但是在重启后，卡第二屏，已经经过排查，确定为Openshamrock问题
已经尝试过将magisk的超级用户权限从`仅设备管理者`到`由设备管理者控制`再到`各用户独立`，问题仍然存在
能否增加对于双开qq或者tim的支持?

### 实现方法

不知

**Comment by Miuzarte** [comment]
能双开啊。。。？
双开用户确实没系统框架可以勾，但是不影响
![9f34b0eaa6fde11733ab48dfdc613b3f](https://github.com/whitechi73/OpenShamrock/assets/66856838/b8915675-d4fd-4b91-ab53-219079209660)
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/37f88772-25f9-4298-9ce5-05cec92c1abb)
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/83559013-28ad-4b0b-9fdb-06331ddfec6b)
![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/e7d6a341-7d04-4668-bdea-4a317359da18)

**Comment by Zyy955** [comment]
一直都能双开

**Comment by Asgore-Dreemur** [comment]
emm，刚才测试了下，如果不激活模块没事，激活模块重启就得卡一次第二屏然后才能正常开机
我用的AlphaDroid类原生，设备代号vince
