### ISSUE TITLE
bug: 发送图片时，发送的为图片链接而非图片

### ISSUE THREAD

**Issue by fatinghenji** [whitechi73/OpenShamrock#64]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
- 返回的是图片链接而非图片，如下：
```
<message><image url="https://i.pixiv.re/img-original/img/2023/08/06/10/42/05/110572731_p0.jpg"/></message>
<message><image url="https://i.pixiv.re/img-original/img/2022/03/10/19/41/31/96815081_p7.jpg"/></message>
<message><image url="https://i.pixiv.re/img-original/img/2022/10/14/10/30/01/101919806_p0.jpg"/></message>
<message><image url="https://i.pixiv.re/img-original/img/2022/11/27/17/52/49/103143640_p2.jpg"/></message>
<message><image url="https://i.pixiv.re/img-original/img/2020/11/05/23/51/20/85485059_p0.jpg"/></message>
```

### 复现 Bug
- koishibot通过ws链接shamrock
- 使用`booru`命令
- 返回链接而非图片

## 系统信息

- Shamrock 版本: Shamrock-v1.0.5-dev.040b132
- Android 版本: 13
- 设备的制造商和型号: 红米K20Pro
- 设备的 CPU 架构: arm64

**Comment by whitechi73** [comment]
该错误为koishbot-booru自身的问题 (call @MaikoTan, @shigma)

**Comment by MaikoTan** [comment]
Nope, the `booru` plugin is following the Koishi spec sending the `<image>` element with the image url. I believe it is not the issue of `booru` plugin.

**Comment by whitechi73** [comment]
So @shigma

**Comment by shigma** [comment]
我都没看懂问题，你是 Koishi 的使用者还是插件开发者？

**Comment by MaikoTan** [comment]
> 抱歉我没看懂问题是啥……问题是 image 格式不对还是这个 message 元素？
> 

Related: https://forum.koishi.xyz/t/topic/5878

**Comment by shigma** [comment]
既然这个 issue 已经关闭，你可以去 [koishi-plugin-adapter-onebot](https://github.com/koishijs/koishi-plugin-adapter-onebot) 再发一个 issue。但 onebot 适配器已经不积极维护了，可以等待有缘人来研究（
