### ISSUE TITLE
feat: 可以加个定期删除qq本地所有聊天记录的功能吗

### ISSUE THREAD

**Issue by zhengyuelai** [whitechi73/OpenShamrock#7]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

qq本地的聊天记录多了以后配置不够就很容易闪退了，删掉本地聊天数据后会稳定很多。

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by whitechi73** [comment]
https://github.com/whitechi73/OpenShamrock/blob/docs/docs/api/message.md#%E6%B8%85%E9%99%A4%E6%9C%AC%E5%9C%B0%E7%BC%93%E5%AD%98%E6%B6%88%E6%81%AF
