### ISSUE TITLE
feat: 群管 禁言功能升级

### ISSUE THREAD

**Issue by Zyy955** [whitechi73/OpenShamrock#72]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

添加获取当前群里被禁言列表接口

添加一键解除全部被禁言成员接口

**Comment by callng** [comment]
哎呀，这玩意HTTP就能做到。😝

**Comment by Zyy955** [comment]
> 哎呀，这玩意HTTP就能做到。😝

洛洛说：没有新的is吗，那我今晚出去玩了！

**Comment by Zyy955** [comment]
> 哎呀，这玩意HTTP就能做到。😝

洛洛说：没有新的is吗，那我今晚出去玩了！

**Comment by jinyu2022** [comment]
这玩意自己封装一下不好了

**Comment by whitechi73** [comment]
https://whitechi73.github.io/OpenShamrock/api/group.html#%E8%8E%B7%E5%8F%96%E8%A2%AB%E7%A6%81%E8%A8%80%E7%9A%84%E7%BE%A4%E6%88%90%E5%91%98%E5%88%97%E8%A1%A8
