### ISSUE TITLE
bug: "error": "Element class kotlinx.serialization.json.JsonObject is not a JsonArray"

### ISSUE THREAD

**Issue by luguoguo** [whitechi73/OpenShamrock#73]
### 描述 Bug

也许这不是一个bug，但是我用gocq测试，这样发是可以发出去的。

测试工具: Postman
以下是向 5700 主动http端口发送数据
```
POST:  http://{{host}}:{{port}}/send_group_msg
{
    "group_id": 123123,
    "auto_escape": false,
    "message": {
        "type": "image",
        "data": {
            "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
        }
    }
}
```
### 复现 Bug

响应如下:
```
{
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/send_group_msg",
        "error": "Element class kotlinx.serialization.json.JsonObject is not a JsonArray"
    }
}
```
## 系统信息

- Shamrock 版本:  1.0.6-dev
- Android 版本: 13
- 设备的制造商和型号: redmi k30
- 设备的 CPU 架构: arm64

**Comment by luguoguo** [comment]
## Request
```
POST:  http://{{host}}:{{port}}/send_group_msg
{
    "group_id": 123123,
    "auto_escape": false,
    "message": "Hello!"
}
```
## Response
```
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "message_id": 646895659,
        "time": 1.700710819961E9
    }
}
```
如果 message 后面只跟字符串是没问题的，可以正常发送。使用消息段如何发图片，AT， 表情等消息呢？

**Comment by whitechi73** [comment]
是不是应该这样？
```json
{
  "action": "send_group_msg",
  "params": {
    "group_id": 123456,
    "message": [
      {
        "type": "image",
        "data": {
          "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
        }
      }
    ]
  }
}
```

**Comment by ikechan8370** [comment]
message下应该是一个[]

**Comment by luguoguo** [comment]
> ```json
> {
>   "action": "send_group_msg",
>   "params": {
>     "group_id": 123456,
>     "message": [
>       {
>         "type": "image",
>         "data": {
>           "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
>         }
>       }
>     ]
>   }
> }
> ```

按照这个格式测试的结果是这样

我发的是HTTP post 请求，而非 WebSocket 请求

## Request

```
POST: http://{{host}}:{{port}}/send_group_msg

{
  "action": "send_group_msg",
  "params": {
    "group_id": 123456,
    "message": [
      {
        "type": "image",
        "data": {
          "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
        }
      }
    ]
  }
}
```

## Response

```
{
    "status": "failed",
    "retcode": 10003,
    "data": {
        "url": "/send_group_msg",
        "error": "Lack of param group_id"
    }
}
```

"缺少参数 group_id" ? 还是发不出去

**Comment by ikechan8370** [comment]
> > ```json
> > {
> >   "action": "send_group_msg",
> >   "params": {
> >     "group_id": 123456,
> >     "message": [
> >       {
> >         "type": "image",
> >         "data": {
> >           "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
> >         }
> >       }
> >     ]
> >   }
> > }
> > ```
> 
> 按照这个格式测试的结果是这样
> 
> 我发的是主动HTTP post 请求，端口是默认的5700，而非 WebSocket 请求
> 
> ## Request
> ```
> POST: http://{{host}}:{{port}}/send_group_msg
> 
> {
>   "action": "send_group_msg",
>   "params": {
>     "group_id": 123456,
>     "message": [
>       {
>         "type": "image",
>         "data": {
>           "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
>         }
>       }
>     ]
>   }
> }
> ```
> 
> ## Response
> ```
> {
>     "status": "failed",
>     "retcode": 10003,
>     "data": {
>         "url": "/send_group_msg",
>         "error": "Lack of param group_id"
>     }
> }
> ```
> 
> "缺少参数 group_id" ? 还是发不出去
> 
> 所以，我看过文档后还是不太清楚，sk作为server时，怎么完全通过http post的方式调用http api

http时候更简单，直接调用对应的接口，比如/send_group_msg，然后POST请求体是你现在的params里的东西，不需要再包一层action和params

**Comment by luguoguo** [comment]
> > > ```json
> > > {
> > >   "action": "send_group_msg",
> > >   "params": {
> > >     "group_id": 123456,
> > >     "message": [
> > >       {
> > >         "type": "image",
> > >         "data": {
> > >           "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
> > >         }
> > >       }
> > >     ]
> > >   }
> > > }
> > > ```
> > 
> > 
> > 按照这个格式测试的结果是这样
> > 我发的是主动HTTP post 请求，端口是默认的5700，而非 WebSocket 请求
> > ## Request
> > ```
> > POST: http://{{host}}:{{port}}/send_group_msg
> > 
> > {
> >   "action": "send_group_msg",
> >   "params": {
> >     "group_id": 123456,
> >     "message": [
> >       {
> >         "type": "image",
> >         "data": {
> >           "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
> >         }
> >       }
> >     ]
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Response
> > ```
> > {
> >     "status": "failed",
> >     "retcode": 10003,
> >     "data": {
> >         "url": "/send_group_msg",
> >         "error": "Lack of param group_id"
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > "缺少参数 group_id" ? 还是发不出去
> > 所以，我看过文档后还是不太清楚，sk作为server时，怎么完全通过http post的方式调用http api
> 
> http时候更简单，直接调用对应的接口，比如/send_group_msg，然后POST请求体是你现在的params里的东西，不需要再包一层action和params

所以是这样？

```
POST http://{{host}}:{{port}}/send_group_msg

{
    "group_id": 123456,
    "auto_escape": false,
    "message": [{
        "type": "image",
        "data": {
            "url": "https://img6.donews.com/img/2023/09/30/img_pic_331696035920.jpeg"
        }
    }]
}

{
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/send_group_msg",
        "error": "消息合成失败，请查看日志或者检查输入。"
    }
}
```
你测试后能成功发送吗？
