### ISSUE TITLE
bug: 返回给服务端数据过大时WebSocket异常断开？

### ISSUE THREAD

**Issue by JUST-HK416D** [whitechi73/OpenShamrock#8]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

服务端在调用一些数据量比较大的端点时可能导致WebSocket异常后断开连接

### 复现 Bug

服务端调用/get_group_member_list时，参数带入一个群成员较多的群号，Shamrock日志页马上打印WebSocket异常，然后断开连接重连
![QQ截图20231101144607](https://github.com/whitechi73/OpenShamrock/assets/90328461/f01d0738-da67-4797-b274-9d280759130b)

## 系统信息

- Shamrock 版本: 
- Android 版本: 
- 设备的制造商和型号: 
- 设备的 CPU 架构:

**Comment by whitechi73** [comment]
无法重现

**Comment by JUST-HK416D** [comment]
> 无法重现
我版本是dev.3f8af38-all，难不成是云手机配置问题？Android10、8核4G，我再试试
