### ISSUE TITLE
bug: 魅族PRO6下的XP环境已按要求打勾模块，并且多次重启，开Q后Shamrock显示未激活

### ISSUE THREAD

**Issue by sd3970566** [whitechi73/OpenShamrock#80]
### 描述 Bug
魅族PRO6下的XP环境已按要求打勾模块，并且多次重启，开Q后Shamrock显示未激活
无论Shamrock先开还是 QQ先开都反复尝试了。

### 复现 Bug
版本：Shamrock-v1.0.5-dev.4713310-all  可以在XP框架的模块里进行打勾启用！
VIVO IQOONEO8是安卓12用的LSP可以成功使用，但是不想用新机 (提到其他设备是因为想表达一下我曾经在其他设备上成功使用过，明白全套操作流程)，老机器魅族pro6是安卓7.1.1必须用XP，因为安卓7用不了LSP，所以XP框架88版本(SDK25 ARM64)已激活，在XP框架的模块选项那边已经打勾Shamrock，并且重启手机多次也无法正常使用(Shamrock总是显示未激活,打开qq没任何反应)！
后来我打算使用Shamrock-v1.0.6-dev.2822331-all版本，但该版本在XP框架APP里的模块中提示(该模块需要XposedBridge 新版9 3 因此无法激活！我不确定安卓7 是否可以安装更高的XP版本)

## 系统信息
- QQ版本 V 8.9.90.13250
- Shamrock 版本: Shamrock-v1.0.5-dev.4713310-all_2.apk
- Android 版本:安卓 7.1.1      Flyme 7.8.4.22 beta
- 设备的制造商和型号: 魅族PRO6  XP框架88版本(SDK25 ARM64)已激活
- 设备的 CPU 架构: 联发科Helio X25

**Comment by callng** [comment]
Shamrock对原始XPosed框架兼容性有那么亿点点问题

**Comment by whitechi73** [comment]
使用LSPosed

**Comment by sd3970566** [comment]
安卓7好像不支持 LSPosed

**Comment by Westlifers** [comment]
@sd3970566 麻烦问一下你在安卓8以前的机器上是否成功激活shamrock？我也遇到了同样的问题，安卓版本较低无法使用lsp
