### ISSUE TITLE
bug: 发不出合并消息，频繁初始化服务

### ISSUE THREAD

**Issue by XM2510136957** [whitechi73/OpenShamrock#83]
版本：v1.0.6-dev
bug：发不出合并消息，频繁初始化服务！
已经将软件都是设置为白名单，无限制，允许自启动，设备小米，系统版本MIUI14.
![4637cff247265bc8e54aad632dad9a36](https://github.com/whitechi73/OpenShamrock/assets/18229485/00da3742-7aa5-4950-a21e-1ad443965c6d)

![image](https://github.com/whitechi73/OpenShamrock/assets/18229485/ef88366c-3dc3-48a4-99e3-f9c6a13a6c63)

**Comment by whitechi73** [comment]
这个问题是您的对接Shamrock的框架的问题，注意的是Shamrock的合并转发和GoCQ的并不一致。

**Comment by XM2510136957** [comment]
不是都是遵循onebot11协议的嘛

**Comment by whitechi73** [comment]
Shamrock不会主动断开任何连接，一般都是网络波动或者另一边抽风断开的

**Comment by Simplxss** [comment]
你有没有嵌套转发消息?
