### ISSUE TITLE
bug: 退群消息返回不正确

### ISSUE THREAD

**Issue by tobycroft** [whitechi73/OpenShamrock#88]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
确保您的问题尚未在 Issues 列表中提出.
确保您的问题不是由于您的代码错误导致的.
描述 Bug

群成员退群后，sub_type返回不正确，因该是：leave，而不是：kick
    "post_type": "notice",
    "notice_type": "group_decrease",
    "sub_type": "kick",

复现 Bug
group_decrease

系统信息
Shamrock 版本: v1.0.6publish
Android 版本: 14
LSPosed 框架版本: 最新
设备的制造商和型号: Mi9
设备的 CPU 架构: arm

**Comment by tobycroft** [comment]
更正一下，退群的时候和被T出时的subtype目前经过测试是写反了T出变成了leave，主动退群变成了kick

**Comment by tobycroft** [comment]
再次补充，另外在开发文档中这两者均有operator_id，但是实测的时候收不到这个operator_id

**Comment by ikechan8370** [comment]
@whitechi73 是不是那个commit fix错issue号了。

**Comment by whitechi73** [comment]
> @whitechi73 是不是那个commit fix错issue号了。

对，看看修复了吗？先close了， @tobycroft
