### ISSUE TITLE
bug: 无法处理加群请求/邀请事件还是我代码写的有问题？

### ISSUE THREAD

**Issue by jackjieYYY** [whitechi73/OpenShamrock#92]
第一次接触QQBOT，请问是我相关的代码写错了吗？感谢您的回复。

错误提示是call api timeout了

![TLXTY6ECGOU0 GO1LW~_A 9](https://github.com/whitechi73/OpenShamrock/assets/53422254/d7eefb51-4e28-4bb6-8a4e-d4edd1727e66)

相关代码
在控制台能看到print(event.message) 正确的输出
![S2T)(2W}9@ AO 9ESH~IYLO](https://github.com/whitechi73/OpenShamrock/assets/53422254/e8a7765a-2e57-4207-8df2-6999ff23fa30)

系统信息
Shamrock 版本: [Shamrock-v1.0.6-dev.8c307c4-arm64](https://github.com/whitechi73/OpenShamrock/suites/18489622314/artifacts/1072767318)
Android 版本: 11
设备的制造商和型号: redroid
设备的 CPU 架构: Arm64

**Comment by ikechan8370** [comment]
实际入群请求有被处理吗？

**Comment by jackjieYYY** [comment]
> 实际入群请求有被处理吗？

您好，谢谢你的回复。实际的入群请求没有被处理到。

**Comment by ikechan8370** [comment]
我没有复现出超时的情况，可能是存在异常没有捕获。
在 https://github.com/whitechi73/OpenShamrock/commit/4932b36ee12c9b3c07a4e8abfa1960e2f35d2df5 优化了一下逻辑，修复了一个可能导致异常的问题。你可以再试试新版本看有没有修复。

**Comment by jackjieYYY** [comment]
> 我没有复现出超时的情况，可能是存在异常没有捕获。 在 [4932b36](https://github.com/whitechi73/OpenShamrock/commit/4932b36ee12c9b3c07a4e8abfa1960e2f35d2df5) 优化了一下逻辑，修复了一个可能导致异常的问题。你可以再试试新版本看有没有修复。

谢谢您的修复，今晚我再试试

**Comment by jackjieYYY** [comment]
> 我没有复现出超时的情况，可能是存在异常没有捕获。 在 [4932b36](https://github.com/whitechi73/OpenShamrock/commit/4932b36ee12c9b3c07a4e8abfa1960e2f35d2df5) 优化了一下逻辑，修复了一个可能导致异常的问题。你可以再试试新版本看有没有修复。

您好，还是相同的报错。以下是相关的截图

![95DU$5M 4})GD{JJHF}(W(M](https://github.com/whitechi73/OpenShamrock/assets/53422254/834869c4-8ff5-4b04-85b1-a7631f2e0505)

![~9 Q2D)G0NKR8$40 GW(NDT](https://github.com/whitechi73/OpenShamrock/assets/53422254/b36fc828-0f8f-4264-86c6-a301a9b22b8f)

![X`}6W064T85@`7I2_%9_IQ](https://github.com/whitechi73/OpenShamrock/assets/53422254/a32cbf3a-23e0-43fd-81d9-bfa4db113704)

![@49 {FKUV_2KRQPS4BXBW0Q](https://github.com/whitechi73/OpenShamrock/assets/53422254/61d84317-410a-4ed1-9c89-2b718db04f04)

![OIWU7SJ%{Q8)(4@Z)`S29C7](https://github.com/whitechi73/OpenShamrock/assets/53422254/567a7ea5-0885-4e88-b7de-ba55fda3bac6)

![QD9F~WZ(EXTU 1R%F8EQT}W](https://github.com/whitechi73/OpenShamrock/assets/53422254/804a2e35-cdce-4be0-afdc-562cfb381601)

![M6$7B$G%$D${N6K}}G14GN7](https://github.com/whitechi73/OpenShamrock/assets/53422254/0fc26bb2-9fd2-4ad5-afaf-57d81cbfeee7)


如果需要更多信息，请告知。

**Comment by Simplxss** [comment]
用action里最新版的 把防止调用栈检测关了再发log

**Comment by jackjieYYY** [comment]
已更新到最新版本

![71B~{9IMLIL8)627V{VARET](https://github.com/whitechi73/OpenShamrock/assets/53422254/9d0000c9-66bc-4581-b08b-3ef9a7c9642b)

![$@ 9UWKM63QEYO1 LYLG{0Z](https://github.com/whitechi73/OpenShamrock/assets/53422254/e1de8b31-61bf-4ca0-864a-9a71b3779499)

![DNEAJV7BQ~1R{MMWH1~U{3J](https://github.com/whitechi73/OpenShamrock/assets/53422254/55bdf2ff-0fdb-46d5-a72a-ca9e7437d073)

![KSETJ@ DDYMJ4GX}ERW3)8V](https://github.com/whitechi73/OpenShamrock/assets/53422254/428fba01-7379-4de5-8132-0499025a6615)

感觉log没有什么特别的

**Comment by ikechan8370** [comment]
已修复
