### ISSUE TITLE
bug: 最新版本出现qq闪退

### ISSUE THREAD

**Issue by mintianzan** [whitechi73/OpenShamrock#96]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

使用最新的
[Shamrock-v1.0.6-dev.4a4507d-all](https://github.com/whitechi73/OpenShamrock/suites/18501405612/artifacts/1073591586)
版本，关闭qq重新启动时qq会闪退

### 复现 Bug

此前使用多个版本版本并未出现此问题
使用不出现问题的版本：Shamrock-v1.0.6-dev.7439622-all
更新之后多次尝试，均在显示类似“强制使用协议”的提示后闪退qq

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.6-dev.4a4507d-all](https://github.com/whitechi73/OpenShamrock/suites/18501405612/artifacts/1073591586)
- Android 版本: 12
- LSPosed 框架版本: 1.8.5（6649）
- 设备的制造商和型号: 华为 mate50(MUMU)
- 设备的 CPU 架构: arm64

**Comment by whitechi73** [comment]
请使用错误捕捉提交错误

**Comment by Simplxss** [comment]
你先用 https://github.com/whitechi73/OpenShamrock/actions/runs/6995017390 这个版本 安装完重启 不要用最新版

**Comment by callng** [comment]
@whitechi73 

https://github.com/whitechi73/OpenShamrock/blob/4a4507dfcdb05f112e136073fab2469a2928d083/app/src/main/AndroidManifest.xml#L22

模块因为属性`extractNativeLibs `的值，没有释放本地库文件，这个属性默认为true

**Comment by callng** [comment]
导致无法加载库文件...
