### ISSUE TITLE
bug: 无法接收QQ临时消息

### ISSUE THREAD

**Issue by liuyue-er** [whitechi73/OpenShamrock#98]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug
无法接收QQ临时消息
![Screenshot_2023-11-27-01-25-43-760_com tencent mobileqq](https://github.com/whitechi73/OpenShamrock/assets/106005062/4660acdc-a7be-4f13-bdd2-0f74e8e1e1de)
![Screenshot_2023-11-27-01-25-46-924_moe fuqiuluo shamrock](https://github.com/whitechi73/OpenShamrock/assets/106005062/a50827a2-ec02-4400-9286-06515855e8e9)
发送了临时消息，无接收日志

### 复现 Bug
非好友，从任意群发起消息即可

## 系统信息

- Shamrock 版本: Shamrock-v1.0.6-dev.3518f97-all
- Android 版本: 11
- LSPosed 框架版本: LSPosed - 1.9.2 (7042) - Zygisk
- 设备的制造商和型号: 小米Redmi K20Pro
- 设备的 CPU 架构: arm64

**Comment by sanlic** [comment]
我也是这个问题，在配置文件设置了还是收不到
